/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetMyQrCodeQueryResponse } from "../../types/paymentController/GetMyQrCode.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getMyQrCodeQueryKey = () => [{ url: '/api/payment/qr/my-qr' }] as const

export type GetMyQrCodeQueryKey = ReturnType<typeof getMyQrCodeQueryKey>

/**
 * @description Generate a reusable VietQR code for depositing balance via bank transfer. The QR code contains a unique payment code that identifies the user. Can be saved and used multiple times with different amounts.
 * @summary Get my payment QR code
 * {@link /api/payment/qr/my-qr}
 */
export async function getMyQrCode(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMyQrCodeQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/payment/qr/my-qr`, ... requestConfig })  
  return res.data
}

export function getMyQrCodeQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMyQrCodeQueryKey()
  return queryOptions<GetMyQrCodeQueryResponse, ResponseErrorConfig<Error>, GetMyQrCodeQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMyQrCode(config)
   },
  })
}

/**
 * @description Generate a reusable VietQR code for depositing balance via bank transfer. The QR code contains a unique payment code that identifies the user. Can be saved and used multiple times with different amounts.
 * @summary Get my payment QR code
 * {@link /api/payment/qr/my-qr}
 */
export function useGetMyQrCode<TData = GetMyQrCodeQueryResponse, TQueryData = GetMyQrCodeQueryResponse, TQueryKey extends QueryKey = GetMyQrCodeQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetMyQrCodeQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMyQrCodeQueryKey()

  const query = useQuery({
   ...getMyQrCodeQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}