/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetAllNewsQueryResponse, GetAllNewsQueryParams } from "../../types/GetAllNews.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetAllNewsUrl() {
  const res = { method: 'GET', url: `/api/news` as const }  
  return res
}

/**
 * @description Retrieve a paginated list of news with optional status, category, and pinning filtering. Use query params: ?status=PUBLISHED&category=HEALTH_TIPS&isPinned=true&page=0&size=10&sort=createdAt,desc
 * @summary Get paginated news with filtering
 * {@link /api/news}
 */
export async function getAllNews(params: GetAllNewsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetAllNewsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetAllNewsUrl().url.toString(), params, ... requestConfig })  
  return res.data
}