/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetNewsByIdQueryResponse, GetNewsByIdPathParams } from "../../types/GetNewsById.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetNewsByIdUrl(id: GetNewsByIdPathParams["id"]) {
  const res = { method: 'GET', url: `/api/news/${id}` as const }  
  return res
}

/**
 * @description Retrieve a specific news article by its ID
 * @summary Get news by ID
 * {@link /api/news/:id}
 */
export async function getNewsById(id: GetNewsByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetNewsByIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetNewsByIdUrl(id).url.toString(), ... requestConfig })  
  return res.data
}