/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { BuyCourseMutationResponse, BuyCoursePathParams, BuyCourseQueryParams } from "../../types/BuyCourse.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getBuyCourseUrl(courseId: BuyCoursePathParams["courseId"]) {
  const res = { method: 'POST', url: `/api/purchases/course/${courseId}` as const }  
  return res
}

/**
 * @description Purchase a course. Optionally provide a coupon code for discount. System automatically applies the best available discount (course discount vs coupon).
 * @summary Buy course
 * {@link /api/purchases/course/:courseId}
 */
export async function buyCourse(courseId: BuyCoursePathParams["courseId"], params?: BuyCourseQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<BuyCourseMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getBuyCourseUrl(courseId).url.toString(), params, ... requestConfig })  
  return res.data
}