/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetMyPurchasesPaginatedQueryResponse, GetMyPurchasesPaginatedQueryParams } from "../../types/GetMyPurchasesPaginated.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetMyPurchasesPaginatedUrl() {
  const res = { method: 'GET', url: `/api/purchases/paginated` as const }  
  return res
}

/**
 * @description Get current user's purchase history with pagination
 * @summary Get my purchases with pagination
 * {@link /api/purchases/paginated}
 */
export async function getMyPurchasesPaginated(params: GetMyPurchasesPaginatedQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMyPurchasesPaginatedQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetMyPurchasesPaginatedUrl().url.toString(), params, ... requestConfig })  
  return res.data
}