/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetCategoriesByTypeQueryResponse, GetCategoriesByTypePathParams } from "../../types/exerciseCategoriesController/GetCategoriesByType.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getCategoriesByType } from "../../clients/exerciseCategoriesController/getCategoriesByType.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getCategoriesByTypeQueryKey = (type: GetCategoriesByTypePathParams["type"]) => [{ url: '/api/exercise-categories/type/:type', params: {type:type} }] as const

export type GetCategoriesByTypeQueryKey = ReturnType<typeof getCategoriesByTypeQueryKey>

export function getCategoriesByTypeQueryOptions(type: GetCategoriesByTypePathParams["type"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getCategoriesByTypeQueryKey(type)
  return queryOptions<GetCategoriesByTypeQueryResponse, ResponseErrorConfig<Error>, GetCategoriesByTypeQueryResponse, typeof queryKey>({
   enabled: !!(type),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getCategoriesByType(type, config)
   },
  })
}

/**
 * @description Retrieve exercise categories filtered by type (BODY_PART, RECOVERY_STAGE, HEALTH_CONDITION, DIFFICULTY_LEVEL, EXERCISE_TYPE)
 * @summary Get categories by type
 * {@link /api/exercise-categories/type/:type}
 */
export function useGetCategoriesByType<TData = GetCategoriesByTypeQueryResponse, TQueryData = GetCategoriesByTypeQueryResponse, TQueryKey extends QueryKey = GetCategoriesByTypeQueryKey>(type: GetCategoriesByTypePathParams["type"], options: 
{
  query?: Partial<QueryObserverOptions<GetCategoriesByTypeQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getCategoriesByTypeQueryKey(type)

  const query = useQuery({
   ...getCategoriesByTypeQueryOptions(type, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}