/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { SearchCategoriesByNameQueryResponse, SearchCategoriesByNameQueryParams } from "../../types/exerciseCategoriesController/SearchCategoriesByName.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const searchCategoriesByNameQueryKey = (params: SearchCategoriesByNameQueryParams) => [{ url: '/api/exercise-categories/search' }, ...(params ? [params] : [])] as const

export type SearchCategoriesByNameQueryKey = ReturnType<typeof searchCategoriesByNameQueryKey>

/**
 * @description Search exercise categories by name (case-insensitive, partial match)
 * @summary Search categories by name
 * {@link /api/exercise-categories/search}
 */
export async function searchCategoriesByName(params: SearchCategoriesByNameQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<SearchCategoriesByNameQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/exercise-categories/search`, params, ... requestConfig })  
  return res.data
}

export function searchCategoriesByNameQueryOptions(params: SearchCategoriesByNameQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = searchCategoriesByNameQueryKey(params)
  return queryOptions<SearchCategoriesByNameQueryResponse, ResponseErrorConfig<Error>, SearchCategoriesByNameQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return searchCategoriesByName(params, config)
   },
  })
}

/**
 * @description Search exercise categories by name (case-insensitive, partial match)
 * @summary Search categories by name
 * {@link /api/exercise-categories/search}
 */
export function useSearchCategoriesByName<TData = SearchCategoriesByNameQueryResponse, TQueryData = SearchCategoriesByNameQueryResponse, TQueryKey extends QueryKey = SearchCategoriesByNameQueryKey>(params: SearchCategoriesByNameQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<SearchCategoriesByNameQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? searchCategoriesByNameQueryKey(params)

  const query = useQuery({
   ...searchCategoriesByNameQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}