/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/api-client'
import type {
  CreatePopupMutationRequest,
  CreatePopupMutationResponse,
} from '../../types/startupPopupController/CreatePopup.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/api-client'
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from '@tanstack/react-query'
import { mutationOptions, useMutation } from '@tanstack/react-query'

export const createPopupMutationKey = () =>
  [{ url: '/api/startup-popup' }] as const

export type CreatePopupMutationKey = ReturnType<typeof createPopupMutationKey>

/**
 * @description Creates a new startup popup. If active=true, all other popups are deactivated.
 * @summary Create startup popup
 * {@link /api/startup-popup}
 */
export async function createPopup(
  data: CreatePopupMutationRequest,
  config: Partial<RequestConfig<CreatePopupMutationRequest>> & {
    client?: typeof fetch
  } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    CreatePopupMutationResponse,
    ResponseErrorConfig<Error>,
    CreatePopupMutationRequest
  >({
    method: 'POST',
    url: `/api/startup-popup`,
    data: requestData,
    ...requestConfig,
  })
  return res.data
}

export function createPopupMutationOptions(
  config: Partial<RequestConfig<CreatePopupMutationRequest>> & {
    client?: typeof fetch
  } = {}
) {
  const mutationKey = createPopupMutationKey()
  return mutationOptions<
    CreatePopupMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreatePopupMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return createPopup(data, config)
    },
  })
}

/**
 * @description Creates a new startup popup. If active=true, all other popups are deactivated.
 * @summary Create startup popup
 * {@link /api/startup-popup}
 */
export function useCreatePopup<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CreatePopupMutationResponse,
      ResponseErrorConfig<Error>,
      { data: CreatePopupMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<CreatePopupMutationRequest>> & {
      client?: typeof fetch
    }
  } = {}
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? createPopupMutationKey()

  const baseOptions = createPopupMutationOptions(config) as UseMutationOptions<
    CreatePopupMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreatePopupMutationRequest },
    TContext
  >

  return useMutation<
    CreatePopupMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreatePopupMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient
  ) as UseMutationResult<
    CreatePopupMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CreatePopupMutationRequest },
    TContext
  >
}
