/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetPopupByIdQueryResponse, GetPopupByIdPathParams } from "../../types/startupPopupController/GetPopupById.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getPopupByIdSuspenseQueryKey = (id: GetPopupByIdPathParams["id"]) => [{ url: '/api/startup-popup/:id', params: {id:id} }] as const

export type GetPopupByIdSuspenseQueryKey = ReturnType<typeof getPopupByIdSuspenseQueryKey>

/**
 * @summary Get startup popup by ID
 * {@link /api/startup-popup/:id}
 */
export async function getPopupByIdSuspense(id: GetPopupByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPopupByIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/startup-popup/${id}`, ... requestConfig })  
  return res.data
}

export function getPopupByIdSuspenseQueryOptions(id: GetPopupByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPopupByIdSuspenseQueryKey(id)
  return queryOptions<GetPopupByIdQueryResponse, ResponseErrorConfig<Error>, GetPopupByIdQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPopupByIdSuspense(id, config)
   },
  })
}

/**
 * @summary Get startup popup by ID
 * {@link /api/startup-popup/:id}
 */
export function useGetPopupByIdSuspense<TData = GetPopupByIdQueryResponse, TQueryKey extends QueryKey = GetPopupByIdSuspenseQueryKey>(id: GetPopupByIdPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetPopupByIdQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPopupByIdSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...getPopupByIdSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}