/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/api-client'
import type {
  GetAllPopupsQueryResponse,
  GetAllPopupsQueryParams,
} from '../../types/startupPopupController/GetAllPopups.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/api-client'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getAllPopupsSuspenseQueryKey = (params: GetAllPopupsQueryParams) =>
  [{ url: '/api/startup-popup' }, ...(params ? [params] : [])] as const

export type GetAllPopupsSuspenseQueryKey = ReturnType<
  typeof getAllPopupsSuspenseQueryKey
>

/**
 * @description Returns all popups with pagination. Staff only.
 * @summary Get all startup popups
 * {@link /api/startup-popup}
 */
export async function getAllPopupsSuspense(
  params: GetAllPopupsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetAllPopupsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/api/startup-popup`, params, ...requestConfig })
  return res.data
}

export function getAllPopupsSuspenseQueryOptions(
  params: GetAllPopupsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = getAllPopupsSuspenseQueryKey(params)
  return queryOptions<
    GetAllPopupsQueryResponse,
    ResponseErrorConfig<Error>,
    GetAllPopupsQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getAllPopupsSuspense(params, config)
    },
  })
}

/**
 * @description Returns all popups with pagination. Staff only.
 * @summary Get all startup popups
 * {@link /api/startup-popup}
 */
export function useGetAllPopupsSuspense<
  TData = GetAllPopupsQueryResponse,
  TQueryKey extends QueryKey = GetAllPopupsSuspenseQueryKey,
>(
  params: GetAllPopupsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetAllPopupsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey =
    queryOptions?.queryKey ?? getAllPopupsSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...getAllPopupsSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
