/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/api-client'
import type {
  GetMyFormsQueryResponse,
  GetMyFormsQueryParams,
} from '../../types/rehabilitationExaminationFormManagementController/GetMyForms.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/api-client'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getMyFormsSuspenseQueryKey = (params: GetMyFormsQueryParams) =>
  [
    { url: '/api/rehabilitation-examination-forms/me' },
    ...(params ? [params] : []),
  ] as const

export type GetMyFormsSuspenseQueryKey = ReturnType<
  typeof getMyFormsSuspenseQueryKey
>

/**
 * @description Retrieve paginated rehabilitation examination forms for the authenticated mobile user
 * @summary Get my rehabilitation examination forms
 * {@link /api/rehabilitation-examination-forms/me}
 */
export async function getMyFormsSuspense(
  params: GetMyFormsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetMyFormsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: `/api/rehabilitation-examination-forms/me`,
    params,
    ...requestConfig,
  })
  return res.data
}

export function getMyFormsSuspenseQueryOptions(
  params: GetMyFormsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = getMyFormsSuspenseQueryKey(params)
  return queryOptions<
    GetMyFormsQueryResponse,
    ResponseErrorConfig<Error>,
    GetMyFormsQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getMyFormsSuspense(params, config)
    },
  })
}

/**
 * @description Retrieve paginated rehabilitation examination forms for the authenticated mobile user
 * @summary Get my rehabilitation examination forms
 * {@link /api/rehabilitation-examination-forms/me}
 */
export function useGetMyFormsSuspense<
  TData = GetMyFormsQueryResponse,
  TQueryKey extends QueryKey = GetMyFormsSuspenseQueryKey,
>(
  params: GetMyFormsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetMyFormsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMyFormsSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...getMyFormsSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
