/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PagedModel } from "../PagedModel.ts";

export type GetMyTransactionHistoryQueryParams = {
    /**
     * @default 0
     * @type integer | undefined, int32
    */
    page?: number;
    /**
     * @default 20
     * @type integer | undefined, int32
    */
    size?: number;
};

/**
 * @description OK
*/
export type GetMyTransactionHistory200 = PagedModel;

export type GetMyTransactionHistoryQueryResponse = GetMyTransactionHistory200;

export type GetMyTransactionHistoryQuery = {
    Response: GetMyTransactionHistory200;
    QueryParams: GetMyTransactionHistoryQueryParams;
    Errors: any;
};