/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SpendingSummaryResponse } from "../SpendingSummaryResponse.ts";

/**
 * @description OK
*/
export type GetMyTotalSpending200 = SpendingSummaryResponse;

export type GetMyTotalSpendingQueryResponse = GetMyTotalSpending200;

export type GetMyTotalSpendingQuery = {
    Response: GetMyTotalSpending200;
    Errors: any;
};