/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AppointmentStatsResponse } from "../AppointmentStatsResponse.ts";

export type GetAppointmentStatsQueryParams = {
  /**
   * @description Time grouping: day or week (default: day)
   * @default "day"
   * @type string | undefined
   */
  groupBy?: string;
  /**
   * @description Start of date range (ISO date-time, defaults to 30 days ago)
   * @type string | undefined, date-time
   */
  start?: string;
  /**
   * @description End of date range (ISO date-time, defaults to now)
   * @type string | undefined, date-time
   */
  end?: string;
};

/**
 * @description OK
 */
export type GetAppointmentStats200 = AppointmentStatsResponse;

export type GetAppointmentStatsQueryResponse = GetAppointmentStats200;

export type GetAppointmentStatsQuery = {
  Response: GetAppointmentStats200;
  QueryParams: GetAppointmentStatsQueryParams;
  Errors: any;
};
