/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RegistrationResponse } from "../RegistrationResponse.ts";

export type GetRegistrationsQueryParams = {
    /**
     * @description Time grouping: day, week, or month (default: day)
     * @default "day"
     * @type string | undefined
    */
    groupBy?: string;
    /**
     * @description Start of date range (ISO date-time, defaults to 30 days ago)
     * @type string | undefined, date-time
    */
    start?: string;
    /**
     * @description End of date range (ISO date-time, defaults to now)
     * @type string | undefined, date-time
    */
    end?: string;
};

/**
 * @description OK
*/
export type GetRegistrations200 = RegistrationResponse;

export type GetRegistrationsQueryResponse = GetRegistrations200;

export type GetRegistrationsQuery = {
    Response: GetRegistrations200;
    QueryParams: GetRegistrationsQueryParams;
    Errors: any;
};