/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TopSpenderResponse } from "../TopSpenderResponse.ts";

export type GetTopSpendersQueryParams = {
    /**
     * @description Number of top spenders to return (default: 20)
     * @default 20
     * @type integer | undefined, int32
    */
    limit?: number;
};

/**
 * @description OK
*/
export type GetTopSpenders200 = TopSpenderResponse[];

export type GetTopSpendersQueryResponse = GetTopSpenders200;

export type GetTopSpendersQuery = {
    Response: GetTopSpenders200;
    QueryParams: GetTopSpendersQueryParams;
    Errors: any;
};