/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pageable } from "../Pageable.ts";
import type { PagedModel } from "../PagedModel.ts";

export type GetMyAssignedCoursesQueryParams = {
    /**
     * @type object
    */
    pageable: Pageable;
};

/**
 * @description OK
*/
export type GetMyAssignedCourses200 = PagedModel;

export type GetMyAssignedCoursesQueryResponse = GetMyAssignedCourses200;

export type GetMyAssignedCoursesQuery = {
    Response: GetMyAssignedCourses200;
    QueryParams: GetMyAssignedCoursesQueryParams;
    Errors: any;
};