/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pageable } from '../Pageable.ts'
import type { PagedModelTrainerResponse } from '../PagedModelTrainerResponse.ts'

export type GetMyTrainersQueryParams = {
  /**
   * @description Search by fullName or email (case-insensitive)
   * @type string | undefined
   */
  query?: string
  /**
   * @type object
   */
  pageable: Pageable
}

/**
 * @description OK
 */
export type GetMyTrainers200 = PagedModelTrainerResponse

export type GetMyTrainersQueryResponse = GetMyTrainers200

export type GetMyTrainersQuery = {
  Response: GetMyTrainers200
  QueryParams: GetMyTrainersQueryParams
  Errors: any
}
