export type { ApproveCourseRequestPathParams, ApproveCourseRequest200, ApproveCourseRequestMutationRequest, ApproveCourseRequestMutationResponse, ApproveCourseRequestMutation } from "./ApproveCourseRequest.ts";
export type { AssignCourseToPatientPathParams, AssignCourseToPatient200, AssignCourseToPatientMutationRequest, AssignCourseToPatientMutationResponse, AssignCourseToPatientMutation } from "./AssignCourseToPatient.ts";
export type { CreateAndAssignCustomCoursePathParams, CreateAndAssignCustomCourse200, CreateAndAssignCustomCourseMutationRequest, CreateAndAssignCustomCourseMutationResponse, CreateAndAssignCustomCourseMutation } from "./CreateAndAssignCustomCourse.ts";
export type { GetCourseRequestsQueryParamsStatusEnumKey, GetCourseRequestsQueryParams, GetCourseRequests200, GetCourseRequestsQueryResponse, GetCourseRequestsQuery } from "./GetCourseRequests.ts";
export type { GetMyAssignedCoursesQueryParams, GetMyAssignedCourses200, GetMyAssignedCoursesQueryResponse, GetMyAssignedCoursesQuery } from "./GetMyAssignedCourses.ts";
export type { GetMyPatientsQueryParams, GetMyPatients200, GetMyPatientsQueryResponse, GetMyPatientsQuery } from "./GetMyPatients.ts";
export type { GetMyTrainersQueryParams, GetMyTrainers200, GetMyTrainersQueryResponse, GetMyTrainersQuery } from "./GetMyTrainers.ts";
export type { GetPatientCoursesPathParams, GetPatientCourses200, GetPatientCoursesQueryResponse, GetPatientCoursesQuery } from "./GetPatientCourses.ts";
export type { RejectCourseRequestPathParams, RejectCourseRequest200, RejectCourseRequestMutationRequest, RejectCourseRequestMutationResponse, RejectCourseRequestMutation } from "./RejectCourseRequest.ts";
export type { RevokeCourseAssignmentPathParams, RevokeCourseAssignment200, RevokeCourseAssignmentMutationResponse, RevokeCourseAssignmentMutation } from "./RevokeCourseAssignment.ts";
export { getCourseRequestsQueryParamsStatusEnum } from "./GetCourseRequests.ts";