/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AppointmentResponse } from "./AppointmentResponse.ts";
import type { UpdateAppointmentStatusRequest } from "./UpdateAppointmentStatusRequest.ts";

export type ApproveAppointmentPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type ApproveAppointment200 = AppointmentResponse;

export type ApproveAppointmentMutationRequest = UpdateAppointmentStatusRequest;

export type ApproveAppointmentMutationResponse = ApproveAppointment200;

export type ApproveAppointmentMutation = {
    Response: ApproveAppointment200;
    Request: ApproveAppointmentMutationRequest;
    PathParams: ApproveAppointmentPathParams;
    Errors: any;
};