/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PurchaseResponse } from "./PurchaseResponse.ts";

export type BuyCoursePathParams = {
    /**
     * @type integer, int64
    */
    courseId: number;
};

/**
 * @description OK
*/
export type BuyCourse200 = PurchaseResponse;

export type BuyCourseMutationResponse = BuyCourse200;

export type BuyCourseMutation = {
    Response: BuyCourse200;
    PathParams: BuyCoursePathParams;
    Errors: any;
};