/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CourseProgressResponse } from "./CourseProgressResponse.ts";

export type CompleteExercisePathParams = {
    /**
     * @type integer, int64
    */
    courseId: number;
    /**
     * @type integer, int64
    */
    dayExerciseId: number;
};

export type CompleteExerciseQueryParams = {
    /**
     * @default false
     * @type boolean | undefined
    */
    bypassRestriction?: boolean;
};

/**
 * @description OK
*/
export type CompleteExercise200 = CourseProgressResponse;

export type CompleteExerciseMutationResponse = CompleteExercise200;

export type CompleteExerciseMutation = {
    Response: CompleteExercise200;
    PathParams: CompleteExercisePathParams;
    QueryParams: CompleteExerciseQueryParams;
    Errors: any;
};