/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AppointmentResponse } from "./AppointmentResponse.ts";

export type CompleteAppointmentPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type CompleteAppointment200 = AppointmentResponse;

export type CompleteAppointmentMutationResponse = CompleteAppointment200;

export type CompleteAppointmentMutation = {
    Response: CompleteAppointment200;
    PathParams: CompleteAppointmentPathParams;
    Errors: any;
};