/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DayProgressResponse } from "./DayProgressResponse.ts";

export type CourseProgressResponse = {
    /**
     * @type integer | undefined, int64
    */
    userCourseProgressId?: number;
    /**
     * @type integer | undefined, int64
    */
    courseId?: number;
    /**
     * @type string | undefined
    */
    courseTitle?: string;
    /**
     * @type string | undefined
    */
    courseDescription?: string;
    /**
     * @type string | undefined
    */
    courseImageUrl?: string;
    /**
     * @type integer | undefined, int32
    */
    currentDayNumber?: number;
    /**
     * @type integer | undefined, int32
    */
    totalDays?: number;
    /**
     * @type integer | undefined, int32
    */
    totalExercises?: number;
    /**
     * @type integer | undefined, int32
    */
    completedExercises?: number;
    /**
     * @type number | undefined, double
    */
    progressPercentage?: number;
    /**
     * @type boolean | undefined
    */
    isCompleted?: boolean;
    /**
     * @type string | undefined, date-time
    */
    startedAt?: string;
    /**
     * @type string | undefined, date-time
    */
    completedAt?: string;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
    /**
     * @type string | undefined, date
    */
    lastDayCompletedDate?: string;
    /**
     * @type boolean | undefined
    */
    isCurrentDayRestricted?: boolean;
    /**
     * @type array | undefined
    */
    days?: DayProgressResponse[];
};