/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CourseRatingResponse = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type integer | undefined, int64
    */
    userId?: number;
    /**
     * @type string | undefined
    */
    userName?: string;
    /**
     * @type integer | undefined, int64
    */
    courseId?: number;
    /**
     * @type string | undefined
    */
    courseTitle?: string;
    /**
     * @type integer | undefined, int32
    */
    rating?: number;
    /**
     * @type string | undefined
    */
    review?: string;
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
};