/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Course } from "./Course.ts";
import type { DayExercise } from "./DayExercise.ts";

export type CourseDay = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type object
    */
    course: Course;
    /**
     * @type integer, int32
    */
    dayNumber: number;
    /**
     * @type string | undefined
    */
    dayDescription?: string;
    /**
     * @type array | undefined
    */
    dayExercises?: DayExercise[];
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
};