/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CourseCategory } from "./CourseCategory.ts";
import type { CourseDay } from "./CourseDay.ts";

export type Course = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @minLength 1
     * @type string
    */
    title: string;
    /**
     * @minLength 1
     * @type string
    */
    description: string;
    /**
     * @minLength 1
     * @type string
    */
    imageUrl: string;
    /**
     * @type integer, int64
    */
    price: number;
    /**
     * @type array | undefined
    */
    courseDays?: CourseDay[];
    /**
     * @type integer | undefined, int32
    */
    durationDays?: number;
    /**
     * @type object | undefined
    */
    courseCategory?: CourseCategory;
    /**
     * @type boolean | undefined
    */
    isCustom?: boolean;
    /**
     * @type integer | undefined, int64
    */
    createdByUserId?: number;
    /**
     * @type string | undefined
    */
    createdByRole?: string;
    /**
     * @type boolean | undefined
    */
    isPublic?: boolean;
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
};