/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateDoctorRequest } from "./CreateDoctorRequest.ts";
import type { DoctorResponse } from "./DoctorResponse.ts";

/**
 * @description OK
*/
export type CreateDoctor200 = DoctorResponse;

export type CreateDoctorMutationRequest = CreateDoctorRequest;

export type CreateDoctorMutationResponse = CreateDoctor200;

export type CreateDoctorMutation = {
    Response: CreateDoctor200;
    Request: CreateDoctorMutationRequest;
    Errors: any;
};