/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateCarouselBannerRequest = {
    /**
     * @minLength 1
     * @type string
    */
    title: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @minLength 1
     * @type string
    */
    imageUrl: string;
    /**
     * @type string | undefined
    */
    linkUrl?: string;
    /**
     * @type integer | undefined, int32
    */
    displayOrder?: number;
    /**
     * @type string | undefined, date-time
    */
    startDate?: string;
    /**
     * @type string | undefined, date-time
    */
    endDate?: string;
};