/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CategoryResponse } from "./CategoryResponse.ts";
import type { CreateCategoryRequest } from "./CreateCategoryRequest.ts";

/**
 * @description OK
*/
export type CreateCategory200 = CategoryResponse;

export type CreateCategoryMutationRequest = CreateCategoryRequest;

export type CreateCategoryMutationResponse = CreateCategory200;

export type CreateCategoryMutation = {
    Response: CreateCategory200;
    Request: CreateCategoryMutationRequest;
    Errors: any;
};