/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CourseResponse } from "./CourseResponse.ts";
import type { CreateCourseRequest } from "./CreateCourseRequest.ts";

/**
 * @description OK
*/
export type CreateCourse200 = CourseResponse;

export type CreateCourseMutationRequest = CreateCourseRequest;

export type CreateCourseMutationResponse = CreateCourse200;

export type CreateCourseMutation = {
    Response: CreateCourse200;
    Request: CreateCourseMutationRequest;
    Errors: any;
};