/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteCodePathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type DeleteCode200 = any;

export type DeleteCodeMutationResponse = DeleteCode200;

export type DeleteCodeMutation = {
    Response: DeleteCode200;
    PathParams: DeleteCodePathParams;
    Errors: any;
};