/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteCategory1PathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type DeleteCategory1200 = any;

export type DeleteCategory1MutationResponse = DeleteCategory1200;

export type DeleteCategory1Mutation = {
    Response: DeleteCategory1200;
    PathParams: DeleteCategory1PathParams;
    Errors: any;
};