/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteNewsPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type DeleteNews200 = any;

export type DeleteNewsMutationResponse = DeleteNews200;

export type DeleteNewsMutation = {
    Response: DeleteNews200;
    PathParams: DeleteNewsPathParams;
    Errors: any;
};