/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type DeleteAdminPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type DeleteAdmin200 = any;

export type DeleteAdminMutationResponse = DeleteAdmin200;

export type DeleteAdminMutation = {
    Response: DeleteAdmin200;
    PathParams: DeleteAdminPathParams;
    Errors: any;
};