/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Exercise } from "./Exercise.ts";

export const exerciseCategoryTypeEnum = {
    "BODY_PART": "BODY_PART",
    "RECOVERY_STAGE": "RECOVERY_STAGE",
    "HEALTH_CONDITION": "HEALTH_CONDITION",
    "DIFFICULTY_LEVEL": "DIFFICULTY_LEVEL",
    "EXERCISE_TYPE": "EXERCISE_TYPE"
} as const;

export type ExerciseCategoryTypeEnumKey = (typeof exerciseCategoryTypeEnum)[keyof typeof exerciseCategoryTypeEnum];

export type ExerciseCategory = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @minLength 1
     * @type string
    */
    name: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type string | undefined
    */
    type?: ExerciseCategoryTypeEnumKey;
    /**
     * @type array | undefined
    */
    exercises?: Exercise[];
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
};