/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DayExercise } from "./DayExercise.ts";
import type { ExerciseCategory } from "./ExerciseCategory.ts";

export type Exercise = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @minLength 1
     * @type string
    */
    title: string;
    /**
     * @minLength 1
     * @type string
    */
    description: string;
    /**
     * @minLength 1
     * @type string
    */
    imageUrl: string;
    /**
     * @minLength 1
     * @type string
    */
    videoUrl: string;
    /**
     * @type integer | undefined, int32
    */
    durationMinutes?: number;
    /**
     * @type array | undefined
    */
    dayExercises?: DayExercise[];
    /**
     * @type object | undefined
    */
    exerciseCategory?: ExerciseCategory;
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
};