/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ExerciseCategoryResponse } from "./ExerciseCategoryResponse.ts";

/**
 * @description OK
*/
export type GetAllCategories200 = ExerciseCategoryResponse[];

export type GetAllCategoriesQueryResponse = GetAllCategories200;

export type GetAllCategoriesQuery = {
    Response: GetAllCategories200;
    Errors: any;
};