/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pageable } from "./Pageable.ts";
import type { PageUserResponse } from "./PageUserResponse.ts";

export type GetAllUsersPaginatedQueryParams = {
    /**
     * @type object
    */
    pageable: Pageable;
};

/**
 * @description OK
*/
export type GetAllUsersPaginated200 = PageUserResponse;

export type GetAllUsersPaginatedQueryResponse = GetAllUsersPaginated200;

export type GetAllUsersPaginatedQuery = {
    Response: GetAllUsersPaginated200;
    QueryParams: GetAllUsersPaginatedQueryParams;
    Errors: any;
};