/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pageable } from "./Pageable.ts";
import type { PageCourseResponse } from "./PageCourseResponse.ts";

export type GetAllCoursesPaginatedQueryParams = {
    /**
     * @type object
    */
    pageable: Pageable;
    /**
     * @type integer | undefined, int64
    */
    categoryId?: number;
    /**
     * @type string | undefined
    */
    keyword?: string;
};

/**
 * @description OK
*/
export type GetAllCoursesPaginated200 = PageCourseResponse;

export type GetAllCoursesPaginatedQueryResponse = GetAllCoursesPaginated200;

export type GetAllCoursesPaginatedQuery = {
    Response: GetAllCoursesPaginated200;
    QueryParams: GetAllCoursesPaginatedQueryParams;
    Errors: any;
};