/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pageable } from "./Pageable.ts";
import type { PagedModelAdminResponse } from "./PagedModelAdminResponse.ts";

export type GetAllAdminsQueryParams = {
    /**
     * @type object
    */
    pageable: Pageable;
};

/**
 * @description OK
*/
export type GetAllAdmins200 = PagedModelAdminResponse;

export type GetAllAdminsQueryResponse = GetAllAdmins200;

export type GetAllAdminsQuery = {
    Response: GetAllAdmins200;
    QueryParams: GetAllAdminsQueryParams;
    Errors: any;
};