/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GetAdminPermissionsPathParams = {
    /**
     * @type integer, int64
    */
    adminId: number;
};

/**
 * @description OK
*/
export type GetAdminPermissions200 = string[];

export type GetAdminPermissionsQueryResponse = GetAdminPermissions200;

export type GetAdminPermissionsQuery = {
    Response: GetAdminPermissions200;
    PathParams: GetAdminPermissionsPathParams;
    Errors: any;
};