/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CourseResponse } from "./CourseResponse.ts";

/**
 * @description OK
*/
export type GetAllCourses200 = CourseResponse[];

export type GetAllCoursesQueryResponse = GetAllCourses200;

export type GetAllCoursesQuery = {
    Response: GetAllCourses200;
    Errors: any;
};