/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ExerciseCategoryResponse } from "./ExerciseCategoryResponse.ts";

export type GetCategoryByIdPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type GetCategoryById200 = ExerciseCategoryResponse;

export type GetCategoryByIdQueryResponse = GetCategoryById200;

export type GetCategoryByIdQuery = {
    Response: GetCategoryById200;
    PathParams: GetCategoryByIdPathParams;
    Errors: any;
};