/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CourseProgressSummaryResponse } from "./CourseProgressSummaryResponse.ts";

/**
 * @description OK
*/
export type GetCurrentCourseProgress200 = CourseProgressSummaryResponse;

export type GetCurrentCourseProgressQueryResponse = GetCurrentCourseProgress200;

export type GetCurrentCourseProgressQuery = {
    Response: GetCurrentCourseProgress200;
    Errors: any;
};