/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pageable } from "./Pageable.ts";
import type { PagedModelRehabilitationExaminationFormResponse } from "./PagedModelRehabilitationExaminationFormResponse.ts";

export type GetFormsByUserIdPathParams = {
    /**
     * @type integer, int64
    */
    userId: number;
};

export type GetFormsByUserIdQueryParams = {
    /**
     * @type object
    */
    pageable: Pageable;
};

/**
 * @description OK
*/
export type GetFormsByUserId200 = PagedModelRehabilitationExaminationFormResponse;

export type GetFormsByUserIdQueryResponse = GetFormsByUserId200;

export type GetFormsByUserIdQuery = {
    Response: GetFormsByUserId200;
    PathParams: GetFormsByUserIdPathParams;
    QueryParams: GetFormsByUserIdQueryParams;
    Errors: any;
};