/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pageable } from "./Pageable.ts";
import type { PagedModelAppointmentResponse } from "./PagedModelAppointmentResponse.ts";

export type GetMyAppointmentsQueryParams = {
    /**
     * @type object
    */
    pageable: Pageable;
};

/**
 * @description OK
*/
export type GetMyAppointments200 = PagedModelAppointmentResponse;

export type GetMyAppointmentsQueryResponse = GetMyAppointments200;

export type GetMyAppointmentsQuery = {
    Response: GetMyAppointments200;
    QueryParams: GetMyAppointmentsQueryParams;
    Errors: any;
};