/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NonCompulsoryHealthInsuranceResponse } from "./NonCompulsoryHealthInsuranceResponse.ts";

/**
 * @description OK
*/
export type GetMyNonCompulsoryHealthInsurance200 = NonCompulsoryHealthInsuranceResponse;

export type GetMyNonCompulsoryHealthInsuranceQueryResponse = GetMyNonCompulsoryHealthInsurance200;

export type GetMyNonCompulsoryHealthInsuranceQuery = {
    Response: GetMyNonCompulsoryHealthInsurance200;
    Errors: any;
};