/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pageable } from "./Pageable.ts";
import type { PagedModelActivityResponse } from "./PagedModelActivityResponse.ts";

export type GetRecentActivityQueryParams = {
    /**
     * @type object
    */
    pageable: Pageable;
};

/**
 * @description OK
*/
export type GetRecentActivity200 = PagedModelActivityResponse;

export type GetRecentActivityQueryResponse = GetRecentActivity200;

export type GetRecentActivityQuery = {
    Response: GetRecentActivity200;
    QueryParams: GetRecentActivityQueryParams;
    Errors: any;
};