/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserBasicInfoResponse } from "./UserBasicInfoResponse.ts";

export type GetUserBasicInfoPathParams = {
    /**
     * @type integer, int64
    */
    userId: number;
};

/**
 * @description OK
*/
export type GetUserBasicInfo200 = UserBasicInfoResponse;

export type GetUserBasicInfoQueryResponse = GetUserBasicInfo200;

export type GetUserBasicInfoQuery = {
    Response: GetUserBasicInfo200;
    PathParams: GetUserBasicInfoPathParams;
    Errors: any;
};