/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type GlobalDiscountResponse = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type integer | undefined, int32
    */
    discountPercentage?: number;
    /**
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
};