export type { ActivityResponse } from "./ActivityResponse.ts";
export type { ActivityStatsResponse } from "./ActivityStatsResponse.ts";
export type { AddBalance200, AddBalanceMutationRequest, AddBalanceMutationResponse, AddBalanceMutation } from "./AddBalance.ts";
export type { AddBalanceRequest } from "./AddBalanceRequest.ts";
export type { AddBalanceToUserPathParams, AddBalanceToUser200, AddBalanceToUserMutationRequest, AddBalanceToUserMutationResponse, AddBalanceToUserMutation } from "./AddBalanceToUser.ts";
export type { AdminResponse } from "./AdminResponse.ts";
export type { AssignCourse200, AssignCourseMutationRequest, AssignCourseMutationResponse, AssignCourseMutation } from "./AssignCourse.ts";
export type { AssignCourseRequest } from "./AssignCourseRequest.ts";
export type { AssignPermissionRequest } from "./AssignPermissionRequest.ts";
export type { AssignPermissionToAdminPathParams, AssignPermissionToAdmin200, AssignPermissionToAdminMutationRequest, AssignPermissionToAdminMutationResponse, AssignPermissionToAdminMutation } from "./AssignPermissionToAdmin.ts";
export type { AssignPermissionToDoctorPathParams, AssignPermissionToDoctor200, AssignPermissionToDoctorMutationRequest, AssignPermissionToDoctorMutationResponse, AssignPermissionToDoctorMutation } from "./AssignPermissionToDoctor.ts";
export type { AuthResponseRoleEnumKey, AuthResponse } from "./AuthResponse.ts";
export type { BalanceResponse } from "./BalanceResponse.ts";
export type { BuyCoursePathParams, BuyCourse200, BuyCourseMutationResponse, BuyCourseMutation } from "./BuyCourse.ts";
export type { CarouselBannerListResponse } from "./CarouselBannerListResponse.ts";
export type { CarouselBannerResponse } from "./CarouselBannerResponse.ts";
export type { CheckCourseOwnershipPathParams, CheckCourseOwnership200, CheckCourseOwnershipQueryResponse, CheckCourseOwnershipQuery } from "./CheckCourseOwnership.ts";
export type { CompleteCourse200, CompleteCourseMutationResponse, CompleteCourseMutation } from "./CompleteCourse.ts";
export type { CompletedCourseResponse } from "./CompletedCourseResponse.ts";
export type { CompleteExercisePathParams, CompleteExercise200, CompleteExerciseMutationResponse, CompleteExerciseMutation } from "./CompleteExercise.ts";
export type { Course } from "./Course.ts";
export type { CourseCategoryTypeEnumKey, CourseCategory } from "./CourseCategory.ts";
export type { CourseCategoryResponse } from "./CourseCategoryResponse.ts";
export type { CourseDay } from "./CourseDay.ts";
export type { CourseDayResponse } from "./CourseDayResponse.ts";
export type { CourseProgressSummaryResponse } from "./CourseProgressSummaryResponse.ts";
export type { CourseRatingResponse } from "./CourseRatingResponse.ts";
export type { CourseRatingSummary } from "./CourseRatingSummary.ts";
export type { CourseResponse } from "./CourseResponse.ts";
export type { CreateAdmin200, CreateAdminMutationRequest, CreateAdminMutationResponse, CreateAdminMutation } from "./CreateAdmin.ts";
export type { CreateAdminRequest } from "./CreateAdminRequest.ts";
export type { CreateBanner200, CreateBannerMutationRequest, CreateBannerMutationResponse, CreateBannerMutation } from "./CreateBanner.ts";
export type { CreateCarouselBannerRequest } from "./CreateCarouselBannerRequest.ts";
export type { CreateCategory1200, CreateCategory1MutationRequest, CreateCategory1MutationResponse, CreateCategory1Mutation } from "./CreateCategory1.ts";
export type { CreateCategory200, CreateCategoryMutationRequest, CreateCategoryMutationResponse, CreateCategoryMutation } from "./CreateCategory.ts";
export type { CreateCourse200, CreateCourseMutationRequest, CreateCourseMutationResponse, CreateCourseMutation } from "./CreateCourse.ts";
export type { CreateCourseCategoryRequestTypeEnumKey, CreateCourseCategoryRequest } from "./CreateCourseCategoryRequest.ts";
export type { CreateCourseDayRequest } from "./CreateCourseDayRequest.ts";
export type { CreateCourseRatingRequest } from "./CreateCourseRatingRequest.ts";
export type { CreateCourseRequest } from "./CreateCourseRequest.ts";
export type { CreateDayExerciseRequest } from "./CreateDayExerciseRequest.ts";
export type { CreateDoctor200, CreateDoctorMutationRequest, CreateDoctorMutationResponse, CreateDoctorMutation } from "./CreateDoctor.ts";
export type { CreateDoctorRequest } from "./CreateDoctorRequest.ts";
export type { CreateExercise200, CreateExerciseMutationRequest, CreateExerciseMutationResponse, CreateExerciseMutation } from "./CreateExercise.ts";
export type { CreateExerciseCategoryRequestTypeEnumKey, CreateExerciseCategoryRequest } from "./CreateExerciseCategoryRequest.ts";
export type { CreateExerciseRequest } from "./CreateExerciseRequest.ts";
export type { CreateForm200, CreateFormMutationRequest, CreateFormMutationResponse, CreateFormMutation } from "./CreateForm.ts";
export type { CreateNews200, CreateNewsMutationRequest, CreateNewsMutationResponse, CreateNewsMutation } from "./CreateNews.ts";
export type { CreateNewsRequestStatusEnumKey, CreateNewsRequest } from "./CreateNewsRequest.ts";
export type { CreateRating200, CreateRatingMutationRequest, CreateRatingMutationResponse, CreateRatingMutation } from "./CreateRating.ts";
export type { CreateRehabilitationExaminationFormRequest } from "./CreateRehabilitationExaminationFormRequest.ts";
export type { DayExercise } from "./DayExercise.ts";
export type { DayExerciseResponse } from "./DayExerciseResponse.ts";
export type { DeleteAdminPathParams, DeleteAdmin200, DeleteAdminMutationResponse, DeleteAdminMutation } from "./DeleteAdmin.ts";
export type { DeleteBannerPathParams, DeleteBanner200, DeleteBannerMutationResponse, DeleteBannerMutation } from "./DeleteBanner.ts";
export type { DeleteCategory1PathParams, DeleteCategory1200, DeleteCategory1MutationResponse, DeleteCategory1Mutation } from "./DeleteCategory1.ts";
export type { DeleteCategoryPathParams, DeleteCategory200, DeleteCategoryMutationResponse, DeleteCategoryMutation } from "./DeleteCategory.ts";
export type { DeleteCoursePathParams, DeleteCourse200, DeleteCourseMutationResponse, DeleteCourseMutation } from "./DeleteCourse.ts";
export type { DeleteDoctorPathParams, DeleteDoctor200, DeleteDoctorMutationResponse, DeleteDoctorMutation } from "./DeleteDoctor.ts";
export type { DeleteExercisePathParams, DeleteExercise200, DeleteExerciseMutationResponse, DeleteExerciseMutation } from "./DeleteExercise.ts";
export type { DeleteFileQueryParams, DeleteFile200, DeleteFileMutationResponse, DeleteFileMutation } from "./DeleteFile.ts";
export type { DeleteMyCompanyInfo200, DeleteMyCompanyInfoMutationResponse, DeleteMyCompanyInfoMutation } from "./DeleteMyCompanyInfo.ts";
export type { DeleteMyNationalHealthInsurance200, DeleteMyNationalHealthInsuranceMutationResponse, DeleteMyNationalHealthInsuranceMutation } from "./DeleteMyNationalHealthInsurance.ts";
export type { DeleteMyNonCompulsoryHealthInsurance200, DeleteMyNonCompulsoryHealthInsuranceMutationResponse, DeleteMyNonCompulsoryHealthInsuranceMutation } from "./DeleteMyNonCompulsoryHealthInsurance.ts";
export type { DeleteMyProfile200, DeleteMyProfileMutationResponse, DeleteMyProfileMutation } from "./DeleteMyProfile.ts";
export type { DeleteNationalHealthInsurancePathParams, DeleteNationalHealthInsurance200, DeleteNationalHealthInsuranceMutationResponse, DeleteNationalHealthInsuranceMutation } from "./DeleteNationalHealthInsurance.ts";
export type { DeleteNewsPathParams, DeleteNews200, DeleteNewsMutationResponse, DeleteNewsMutation } from "./DeleteNews.ts";
export type { DeleteNonCompulsoryHealthInsurancePathParams, DeleteNonCompulsoryHealthInsurance200, DeleteNonCompulsoryHealthInsuranceMutationResponse, DeleteNonCompulsoryHealthInsuranceMutation } from "./DeleteNonCompulsoryHealthInsurance.ts";
export type { DeleteRatingPathParams, DeleteRating200, DeleteRatingMutationResponse, DeleteRatingMutation } from "./DeleteRating.ts";
export type { DeleteUserCompanyInfoPathParams, DeleteUserCompanyInfo200, DeleteUserCompanyInfoMutationResponse, DeleteUserCompanyInfoMutation } from "./DeleteUserCompanyInfo.ts";
export type { DeleteUserProfilePathParams, DeleteUserProfile200, DeleteUserProfileMutationResponse, DeleteUserProfileMutation } from "./DeleteUserProfile.ts";
export type { DoctorResponse } from "./DoctorResponse.ts";
export type { Exercise } from "./Exercise.ts";
export type { ExerciseCategoryTypeEnumKey, ExerciseCategory } from "./ExerciseCategory.ts";
export type { ExerciseCategoryResponse } from "./ExerciseCategoryResponse.ts";
export type { ExerciseInfo } from "./ExerciseInfo.ts";
export type { ExerciseProgressResponse } from "./ExerciseProgressResponse.ts";
export type { ExerciseResponse } from "./ExerciseResponse.ts";
export type { FileUploadResponse } from "./FileUploadResponse.ts";
export type { GeneratePresignedAccessUrlPathParams, GeneratePresignedAccessUrlQueryParams, GeneratePresignedAccessUrl200, GeneratePresignedAccessUrlQueryResponse, GeneratePresignedAccessUrlQuery } from "./GeneratePresignedAccessUrl.ts";
export type { GeneratePresignedUploadUrl200, GeneratePresignedUploadUrlMutationRequest, GeneratePresignedUploadUrlMutationResponse, GeneratePresignedUploadUrlMutation } from "./GeneratePresignedUploadUrl.ts";
export type { GenerateVideoViewingUrlQueryParams, GenerateVideoViewingUrl200, GenerateVideoViewingUrlQueryResponse, GenerateVideoViewingUrlQuery } from "./GenerateVideoViewingUrl.ts";
export type { GetActiveBanners200, GetActiveBannersQueryResponse, GetActiveBannersQuery } from "./GetActiveBanners.ts";
export type { GetActivityByDateRangeQueryParams, GetActivityByDateRange200, GetActivityByDateRangeQueryResponse, GetActivityByDateRangeQuery } from "./GetActivityByDateRange.ts";
export type { GetActivityStats200, GetActivityStatsQueryResponse, GetActivityStatsQuery } from "./GetActivityStats.ts";
export type { GetAdminByEmailPathParams, GetAdminByEmail200, GetAdminByEmailQueryResponse, GetAdminByEmailQuery } from "./GetAdminByEmail.ts";
export type { GetAdminByIdPathParams, GetAdminById200, GetAdminByIdQueryResponse, GetAdminByIdQuery } from "./GetAdminById.ts";
export type { GetAdminPermissionsPathParams, GetAdminPermissions200, GetAdminPermissionsQueryResponse, GetAdminPermissionsQuery } from "./GetAdminPermissions.ts";
export type { GetAllAdminsQueryParams, GetAllAdmins200, GetAllAdminsQueryResponse, GetAllAdminsQuery } from "./GetAllAdmins.ts";
export type { GetAllBanners200, GetAllBannersQueryResponse, GetAllBannersQuery } from "./GetAllBanners.ts";
export type { GetAllCategories1200, GetAllCategories1QueryResponse, GetAllCategories1Query } from "./GetAllCategories1.ts";
export type { GetAllCategories200, GetAllCategoriesQueryResponse, GetAllCategoriesQuery } from "./GetAllCategories.ts";
export type { GetAllCategoriesPaginated1QueryParams, GetAllCategoriesPaginated1200, GetAllCategoriesPaginated1QueryResponse, GetAllCategoriesPaginated1Query } from "./GetAllCategoriesPaginated1.ts";
export type { GetAllCategoriesPaginatedQueryParams, GetAllCategoriesPaginated200, GetAllCategoriesPaginatedQueryResponse, GetAllCategoriesPaginatedQuery } from "./GetAllCategoriesPaginated.ts";
export type { GetAllCoursesPaginatedQueryParamsCategoryTypeEnumKey, GetAllCoursesPaginatedQueryParams, GetAllCoursesPaginated200, GetAllCoursesPaginatedQueryResponse, GetAllCoursesPaginatedQuery } from "./GetAllCoursesPaginated.ts";
export type { GetAllDoctorsQueryParams, GetAllDoctors200, GetAllDoctorsQueryResponse, GetAllDoctorsQuery } from "./GetAllDoctors.ts";
export type { GetAllExercisesPaginatedQueryParams, GetAllExercisesPaginated200, GetAllExercisesPaginatedQueryResponse, GetAllExercisesPaginatedQuery } from "./GetAllExercisesPaginated.ts";
export type { GetAllFormsQueryParams, GetAllForms200, GetAllFormsQueryResponse, GetAllFormsQuery } from "./GetAllForms.ts";
export type { GetAllNewsQueryParamsStatusEnumKey, GetAllNewsQueryParams, GetAllNews200, GetAllNewsQueryResponse, GetAllNewsQuery } from "./GetAllNews.ts";
export type { GetAllPermissions200, GetAllPermissionsQueryResponse, GetAllPermissionsQuery } from "./GetAllPermissions.ts";
export type { GetAllUsers1QueryParams, GetAllUsers1200, GetAllUsers1QueryResponse, GetAllUsers1Query } from "./GetAllUsers1.ts";
export type { GetAllUsers200, GetAllUsersQueryResponse, GetAllUsersQuery } from "./GetAllUsers.ts";
export type { GetBannerByIdPathParams, GetBannerById200, GetBannerByIdQueryResponse, GetBannerByIdQuery } from "./GetBannerById.ts";
export type { GetCategoriesByType1PathParamsTypeEnumKey, GetCategoriesByType1PathParams, GetCategoriesByType1200, GetCategoriesByType1QueryResponse, GetCategoriesByType1Query } from "./GetCategoriesByType1.ts";
export type { GetCategoriesByTypePathParamsTypeEnumKey, GetCategoriesByTypePathParams, GetCategoriesByType200, GetCategoriesByTypeQueryResponse, GetCategoriesByTypeQuery } from "./GetCategoriesByType.ts";
export type { GetCategoriesByTypePaginated1PathParamsTypeEnumKey, GetCategoriesByTypePaginated1PathParams, GetCategoriesByTypePaginated1QueryParams, GetCategoriesByTypePaginated1200, GetCategoriesByTypePaginated1QueryResponse, GetCategoriesByTypePaginated1Query } from "./GetCategoriesByTypePaginated1.ts";
export type { GetCategoriesByTypePaginatedPathParamsTypeEnumKey, GetCategoriesByTypePaginatedPathParams, GetCategoriesByTypePaginatedQueryParams, GetCategoriesByTypePaginated200, GetCategoriesByTypePaginatedQueryResponse, GetCategoriesByTypePaginatedQuery } from "./GetCategoriesByTypePaginated.ts";
export type { GetCategoryById1PathParams, GetCategoryById1200, GetCategoryById1QueryResponse, GetCategoryById1Query } from "./GetCategoryById1.ts";
export type { GetCategoryByIdPathParams, GetCategoryById200, GetCategoryByIdQueryResponse, GetCategoryByIdQuery } from "./GetCategoryById.ts";
export type { GetCompletedCourses200, GetCompletedCoursesQueryResponse, GetCompletedCoursesQuery } from "./GetCompletedCourses.ts";
export type { GetCourseAssignmentsPathParams, GetCourseAssignments200, GetCourseAssignmentsQueryResponse, GetCourseAssignmentsQuery } from "./GetCourseAssignments.ts";
export type { GetCourseByIdPathParams, GetCourseById200, GetCourseByIdQueryResponse, GetCourseByIdQuery } from "./GetCourseById.ts";
export type { GetCurrentCourseProgress200, GetCurrentCourseProgressQueryResponse, GetCurrentCourseProgressQuery } from "./GetCurrentCourseProgress.ts";
export type { GetCurrentUser200, GetCurrentUserQueryResponse, GetCurrentUserQuery } from "./GetCurrentUser.ts";
export type { GetDayProgressPathParams, GetDayProgressQueryParams, GetDayProgress200, GetDayProgressQueryResponse, GetDayProgressQuery } from "./GetDayProgress.ts";
export type { GetDoctorByEmailPathParams, GetDoctorByEmail200, GetDoctorByEmailQueryResponse, GetDoctorByEmailQuery } from "./GetDoctorByEmail.ts";
export type { GetDoctorByIdPathParams, GetDoctorById200, GetDoctorByIdQueryResponse, GetDoctorByIdQuery } from "./GetDoctorById.ts";
export type { GetDoctorPermissionsPathParams, GetDoctorPermissions200, GetDoctorPermissionsQueryResponse, GetDoctorPermissionsQuery } from "./GetDoctorPermissions.ts";
export type { GetExerciseByIdPathParams, GetExerciseById200, GetExerciseByIdQueryResponse, GetExerciseByIdQuery } from "./GetExerciseById.ts";
export type { GetFormByIdPathParams, GetFormById200, GetFormByIdQueryResponse, GetFormByIdQuery } from "./GetFormById.ts";
export type { GetFormsByUserIdPathParams, GetFormsByUserIdQueryParams, GetFormsByUserId200, GetFormsByUserIdQueryResponse, GetFormsByUserIdQuery } from "./GetFormsByUserId.ts";
export type { GetGlobalDiscount200, GetGlobalDiscountQueryResponse, GetGlobalDiscountQuery } from "./GetGlobalDiscount.ts";
export type { GetMyBasicInfo200, GetMyBasicInfoQueryResponse, GetMyBasicInfoQuery } from "./GetMyBasicInfo.ts";
export type { GetMyCompanyInfo200, GetMyCompanyInfoQueryResponse, GetMyCompanyInfoQuery } from "./GetMyCompanyInfo.ts";
export type { GetMyCustomCoursesQueryParams, GetMyCustomCourses200, GetMyCustomCoursesQueryResponse, GetMyCustomCoursesQuery } from "./GetMyCustomCourses.ts";
export type { GetMyNationalHealthInsurance200, GetMyNationalHealthInsuranceQueryResponse, GetMyNationalHealthInsuranceQuery } from "./GetMyNationalHealthInsurance.ts";
export type { GetMyNonCompulsoryHealthInsurance200, GetMyNonCompulsoryHealthInsuranceQueryResponse, GetMyNonCompulsoryHealthInsuranceQuery } from "./GetMyNonCompulsoryHealthInsurance.ts";
export type { GetMyOwnedCoursesQueryParams, GetMyOwnedCourses200, GetMyOwnedCoursesQueryResponse, GetMyOwnedCoursesQuery } from "./GetMyOwnedCourses.ts";
export type { GetMyProfile200, GetMyProfileQueryResponse, GetMyProfileQuery } from "./GetMyProfile.ts";
export type { GetMyPurchases200, GetMyPurchasesQueryResponse, GetMyPurchasesQuery } from "./GetMyPurchases.ts";
export type { GetMyPurchasesPaginatedQueryParams, GetMyPurchasesPaginated200, GetMyPurchasesPaginatedQueryResponse, GetMyPurchasesPaginatedQuery } from "./GetMyPurchasesPaginated.ts";
export type { GetMyRatingForCoursePathParams, GetMyRatingForCourse200, GetMyRatingForCourseQueryResponse, GetMyRatingForCourseQuery } from "./GetMyRatingForCourse.ts";
export type { GetMyRatings200, GetMyRatingsQueryResponse, GetMyRatingsQuery } from "./GetMyRatings.ts";
export type { GetNationalHealthInsurancePathParams, GetNationalHealthInsurance200, GetNationalHealthInsuranceQueryResponse, GetNationalHealthInsuranceQuery } from "./GetNationalHealthInsurance.ts";
export type { GetNewsByIdPathParams, GetNewsById200, GetNewsByIdQueryResponse, GetNewsByIdQuery } from "./GetNewsById.ts";
export type { GetNewsBySlugPathParams, GetNewsBySlug200, GetNewsBySlugQueryResponse, GetNewsBySlugQuery } from "./GetNewsBySlug.ts";
export type { GetNonCompulsoryHealthInsurancePathParams, GetNonCompulsoryHealthInsurance200, GetNonCompulsoryHealthInsuranceQueryResponse, GetNonCompulsoryHealthInsuranceQuery } from "./GetNonCompulsoryHealthInsurance.ts";
export type { GetRatingsForCoursePathParams, GetRatingsForCourse200, GetRatingsForCourseQueryResponse, GetRatingsForCourseQuery } from "./GetRatingsForCourse.ts";
export type { GetRatingSummaryPathParams, GetRatingSummary200, GetRatingSummaryQueryResponse, GetRatingSummaryQuery } from "./GetRatingSummary.ts";
export type { GetRecentActivityQueryParams, GetRecentActivity200, GetRecentActivityQueryResponse, GetRecentActivityQuery } from "./GetRecentActivity.ts";
export type { GetTransactionHistory200, GetTransactionHistoryQueryResponse, GetTransactionHistoryQuery } from "./GetTransactionHistory.ts";
export type { GetUserBalance200, GetUserBalanceQueryResponse, GetUserBalanceQuery } from "./GetUserBalance.ts";
export type { GetUserBasicInfoPathParams, GetUserBasicInfo200, GetUserBasicInfoQueryResponse, GetUserBasicInfoQuery } from "./GetUserBasicInfo.ts";
export type { GetUserCompanyInfoPathParams, GetUserCompanyInfo200, GetUserCompanyInfoQueryResponse, GetUserCompanyInfoQuery } from "./GetUserCompanyInfo.ts";
export type { GetUserProfilePathParams, GetUserProfile200, GetUserProfileQueryResponse, GetUserProfileQuery } from "./GetUserProfile.ts";
export type { GlobalDiscountResponse } from "./GlobalDiscountResponse.ts";
export type { GrantedAuthority } from "./GrantedAuthority.ts";
export type { LoginRequest } from "./LoginRequest.ts";
export type { Logout200, LogoutMutationRequest, LogoutMutationResponse, LogoutMutation } from "./Logout.ts";
export type { NationalHealthInsuranceRequest } from "./NationalHealthInsuranceRequest.ts";
export type { NationalHealthInsuranceResponse } from "./NationalHealthInsuranceResponse.ts";
export type { NewsResponseStatusEnumKey, NewsResponse } from "./NewsResponse.ts";
export type { NonCompulsoryHealthInsuranceRequest } from "./NonCompulsoryHealthInsuranceRequest.ts";
export type { NonCompulsoryHealthInsuranceResponse } from "./NonCompulsoryHealthInsuranceResponse.ts";
export type { OtpLoginRequest } from "./OtpLoginRequest.ts";
export type { OtpVerificationRequest } from "./OtpVerificationRequest.ts";
export type { Pageable } from "./Pageable.ts";
export type { PagedModelActivityResponse } from "./PagedModelActivityResponse.ts";
export type { PagedModelAdminResponse } from "./PagedModelAdminResponse.ts";
export type { PagedModelCourse } from "./PagedModelCourse.ts";
export type { PagedModelCourseCategoryResponse } from "./PagedModelCourseCategoryResponse.ts";
export type { PagedModelCourseResponse } from "./PagedModelCourseResponse.ts";
export type { PagedModelDoctorResponse } from "./PagedModelDoctorResponse.ts";
export type { PagedModelExerciseCategoryResponse } from "./PagedModelExerciseCategoryResponse.ts";
export type { PagedModelExerciseResponse } from "./PagedModelExerciseResponse.ts";
export type { PagedModelNewsResponse } from "./PagedModelNewsResponse.ts";
export type { PagedModelPurchaseResponse } from "./PagedModelPurchaseResponse.ts";
export type { PagedModelRehabilitationExaminationFormResponse } from "./PagedModelRehabilitationExaminationFormResponse.ts";
export type { PagedModelUserResponse } from "./PagedModelUserResponse.ts";
export type { PageMetadata } from "./PageMetadata.ts";
export type { PresignedUrlRequest } from "./PresignedUrlRequest.ts";
export type { PresignedUrlResponse } from "./PresignedUrlResponse.ts";
export type { PurchaseTypeEnumKey, PurchaseDiscountTypeEnumKey, Purchase } from "./Purchase.ts";
export type { PurchaseResponse } from "./PurchaseResponse.ts";
export type { RefreshToken200, RefreshTokenMutationRequest, RefreshTokenMutationResponse, RefreshTokenMutation } from "./RefreshToken.ts";
export type { RefreshTokenRequest } from "./RefreshTokenRequest.ts";
export type { RehabilitationExaminationForm } from "./RehabilitationExaminationForm.ts";
export type { RehabilitationExaminationFormResponse } from "./RehabilitationExaminationFormResponse.ts";
export type { RemoveCourseDiscountPathParams, RemoveCourseDiscount200, RemoveCourseDiscountMutationResponse, RemoveCourseDiscountMutation } from "./RemoveCourseDiscount.ts";
export type { RemovePermissionFromAdminPathParams, RemovePermissionFromAdmin200, RemovePermissionFromAdminMutationRequest, RemovePermissionFromAdminMutationResponse, RemovePermissionFromAdminMutation } from "./RemovePermissionFromAdmin.ts";
export type { RemovePermissionFromDoctorPathParams, RemovePermissionFromDoctor200, RemovePermissionFromDoctorMutationRequest, RemovePermissionFromDoctorMutationResponse, RemovePermissionFromDoctorMutation } from "./RemovePermissionFromDoctor.ts";
export type { ReorderBanners200, ReorderBannersMutationRequest, ReorderBannersMutationResponse, ReorderBannersMutation } from "./ReorderBanners.ts";
export type { ReorderBannersRequest } from "./ReorderBannersRequest.ts";
export type { RevokeAssignmentPathParams, RevokeAssignment200, RevokeAssignmentMutationResponse, RevokeAssignmentMutation } from "./RevokeAssignment.ts";
export type { SearchCategories1QueryParams, SearchCategories1200, SearchCategories1QueryResponse, SearchCategories1Query } from "./SearchCategories1.ts";
export type { SearchCategoriesQueryParams, SearchCategories200, SearchCategoriesQueryResponse, SearchCategoriesQuery } from "./SearchCategories.ts";
export type { SearchCategoriesPaginated1QueryParams, SearchCategoriesPaginated1200, SearchCategoriesPaginated1QueryResponse, SearchCategoriesPaginated1Query } from "./SearchCategoriesPaginated1.ts";
export type { SearchCategoriesPaginatedQueryParams, SearchCategoriesPaginated200, SearchCategoriesPaginatedQueryResponse, SearchCategoriesPaginatedQuery } from "./SearchCategoriesPaginated.ts";
export type { SendOtpForUser200, SendOtpForUserMutationRequest, SendOtpForUserMutationResponse, SendOtpForUserMutation } from "./SendOtpForUser.ts";
export type { SetAdminPermissionsPathParams, SetAdminPermissions200, SetAdminPermissionsMutationRequest, SetAdminPermissionsMutationResponse, SetAdminPermissionsMutation } from "./SetAdminPermissions.ts";
export type { SetCourseDiscountPathParams, SetCourseDiscount200, SetCourseDiscountMutationRequest, SetCourseDiscountMutationResponse, SetCourseDiscountMutation } from "./SetCourseDiscount.ts";
export type { SetCourseDiscountRequest } from "./SetCourseDiscountRequest.ts";
export type { SetDoctorPermissionsPathParams, SetDoctorPermissions200, SetDoctorPermissionsMutationRequest, SetDoctorPermissionsMutationResponse, SetDoctorPermissionsMutation } from "./SetDoctorPermissions.ts";
export type { SetPermissionsRequest } from "./SetPermissionsRequest.ts";
export type { SingleDayProgressResponse } from "./SingleDayProgressResponse.ts";
export type { StaffLogin200, StaffLoginMutationRequest, StaffLoginMutationResponse, StaffLoginMutation } from "./StaffLogin.ts";
export type { StartCourse200, StartCourseMutationRequest, StartCourseMutationResponse, StartCourseMutation } from "./StartCourse.ts";
export type { StartCourseRequest } from "./StartCourseRequest.ts";
export type { StopCourse200, StopCourseMutationResponse, StopCourseMutation } from "./StopCourse.ts";
export type { ToggleBannerStatusPathParams, ToggleBannerStatus200, ToggleBannerStatusMutationRequest, ToggleBannerStatusMutationResponse, ToggleBannerStatusMutation } from "./ToggleBannerStatus.ts";
export type { ToggleEnabled1PathParams, ToggleEnabled1200, ToggleEnabled1MutationResponse, ToggleEnabled1Mutation } from "./ToggleEnabled1.ts";
export type { ToggleEnabledPathParams, ToggleEnabled200, ToggleEnabledMutationResponse, ToggleEnabledMutation } from "./ToggleEnabled.ts";
export type { TransactionTypeEnumKey, Transaction } from "./Transaction.ts";
export type { TransactionResponse } from "./TransactionResponse.ts";
export type { UpdateAdminPathParams, UpdateAdmin200, UpdateAdminMutationRequest, UpdateAdminMutationResponse, UpdateAdminMutation } from "./UpdateAdmin.ts";
export type { UpdateAdminRequest } from "./UpdateAdminRequest.ts";
export type { UpdateBannerPathParams, UpdateBanner200, UpdateBannerMutationRequest, UpdateBannerMutationResponse, UpdateBannerMutation } from "./UpdateBanner.ts";
export type { UpdateBannerStatusRequest } from "./UpdateBannerStatusRequest.ts";
export type { UpdateCarouselBannerRequest } from "./UpdateCarouselBannerRequest.ts";
export type { UpdateCategory1PathParams, UpdateCategory1200, UpdateCategory1MutationRequest, UpdateCategory1MutationResponse, UpdateCategory1Mutation } from "./UpdateCategory1.ts";
export type { UpdateCategoryPathParams, UpdateCategory200, UpdateCategoryMutationRequest, UpdateCategoryMutationResponse, UpdateCategoryMutation } from "./UpdateCategory.ts";
export type { UpdateCoursePathParams, UpdateCourse200, UpdateCourseMutationRequest, UpdateCourseMutationResponse, UpdateCourseMutation } from "./UpdateCourse.ts";
export type { UpdateCourseCategoryRequestTypeEnumKey, UpdateCourseCategoryRequest } from "./UpdateCourseCategoryRequest.ts";
export type { UpdateCourseDayRequest } from "./UpdateCourseDayRequest.ts";
export type { UpdateCourseRatingRequest } from "./UpdateCourseRatingRequest.ts";
export type { UpdateCourseRequest } from "./UpdateCourseRequest.ts";
export type { UpdateDayExerciseRequest } from "./UpdateDayExerciseRequest.ts";
export type { UpdateDoctorPathParams, UpdateDoctor200, UpdateDoctorMutationRequest, UpdateDoctorMutationResponse, UpdateDoctorMutation } from "./UpdateDoctor.ts";
export type { UpdateDoctorRequest } from "./UpdateDoctorRequest.ts";
export type { UpdateExercisePathParams, UpdateExercise200, UpdateExerciseMutationRequest, UpdateExerciseMutationResponse, UpdateExerciseMutation } from "./UpdateExercise.ts";
export type { UpdateExerciseCategoryRequestTypeEnumKey, UpdateExerciseCategoryRequest } from "./UpdateExerciseCategoryRequest.ts";
export type { UpdateExerciseRequest } from "./UpdateExerciseRequest.ts";
export type { UpdateFormPathParams, UpdateForm200, UpdateFormMutationRequest, UpdateFormMutationResponse, UpdateFormMutation } from "./UpdateForm.ts";
export type { UpdateGlobalDiscount200, UpdateGlobalDiscountMutationRequest, UpdateGlobalDiscountMutationResponse, UpdateGlobalDiscountMutation } from "./UpdateGlobalDiscount.ts";
export type { UpdateGlobalDiscountRequest } from "./UpdateGlobalDiscountRequest.ts";
export type { UpdateMyBasicInfo200, UpdateMyBasicInfoMutationRequest, UpdateMyBasicInfoMutationResponse, UpdateMyBasicInfoMutation } from "./UpdateMyBasicInfo.ts";
export type { UpdateMyCompanyInfo200, UpdateMyCompanyInfoMutationRequest, UpdateMyCompanyInfoMutationResponse, UpdateMyCompanyInfoMutation } from "./UpdateMyCompanyInfo.ts";
export type { UpdateMyNationalHealthInsurance200, UpdateMyNationalHealthInsuranceMutationRequest, UpdateMyNationalHealthInsuranceMutationResponse, UpdateMyNationalHealthInsuranceMutation } from "./UpdateMyNationalHealthInsurance.ts";
export type { UpdateMyNonCompulsoryHealthInsurance200, UpdateMyNonCompulsoryHealthInsuranceMutationRequest, UpdateMyNonCompulsoryHealthInsuranceMutationResponse, UpdateMyNonCompulsoryHealthInsuranceMutation } from "./UpdateMyNonCompulsoryHealthInsurance.ts";
export type { UpdateMyProfile200, UpdateMyProfileMutationRequest, UpdateMyProfileMutationResponse, UpdateMyProfileMutation } from "./UpdateMyProfile.ts";
export type { UpdateNationalHealthInsurancePathParams, UpdateNationalHealthInsurance200, UpdateNationalHealthInsuranceMutationRequest, UpdateNationalHealthInsuranceMutationResponse, UpdateNationalHealthInsuranceMutation } from "./UpdateNationalHealthInsurance.ts";
export type { UpdateNewsPathParams, UpdateNews200, UpdateNewsMutationRequest, UpdateNewsMutationResponse, UpdateNewsMutation } from "./UpdateNews.ts";
export type { UpdateNewsRequestStatusEnumKey, UpdateNewsRequest } from "./UpdateNewsRequest.ts";
export type { UpdateNonCompulsoryHealthInsurancePathParams, UpdateNonCompulsoryHealthInsurance200, UpdateNonCompulsoryHealthInsuranceMutationRequest, UpdateNonCompulsoryHealthInsuranceMutationResponse, UpdateNonCompulsoryHealthInsuranceMutation } from "./UpdateNonCompulsoryHealthInsurance.ts";
export type { UpdateRatingPathParams, UpdateRating200, UpdateRatingMutationRequest, UpdateRatingMutationResponse, UpdateRatingMutation } from "./UpdateRating.ts";
export type { UpdateRehabilitationExaminationFormRequest } from "./UpdateRehabilitationExaminationFormRequest.ts";
export type { UpdateUserBasicInfoPathParams, UpdateUserBasicInfo200, UpdateUserBasicInfoMutationRequest, UpdateUserBasicInfoMutationResponse, UpdateUserBasicInfoMutation } from "./UpdateUserBasicInfo.ts";
export type { UpdateUserCompanyInfoPathParams, UpdateUserCompanyInfo200, UpdateUserCompanyInfoMutationRequest, UpdateUserCompanyInfoMutationResponse, UpdateUserCompanyInfoMutation } from "./UpdateUserCompanyInfo.ts";
export type { UpdateUserProfilePathParams, UpdateUserProfile200, UpdateUserProfileMutationRequest, UpdateUserProfileMutationResponse, UpdateUserProfileMutation } from "./UpdateUserProfile.ts";
export type { UploadImage200, UploadImageMutationRequest, UploadImageMutationResponse, UploadImageMutation } from "./UploadImage.ts";
export type { UploadVideo200, UploadVideoMutationRequest, UploadVideoMutationResponse, UploadVideoMutation } from "./UploadVideo.ts";
export type { UserRoleEnumKey, User } from "./User.ts";
export type { UserBalance } from "./UserBalance.ts";
export type { UserBasicInfoRequest } from "./UserBasicInfoRequest.ts";
export type { UserBasicInfoResponse } from "./UserBasicInfoResponse.ts";
export type { UserCompanyInfo } from "./UserCompanyInfo.ts";
export type { UserCompanyInfoRequest } from "./UserCompanyInfoRequest.ts";
export type { UserCompanyInfoResponse } from "./UserCompanyInfoResponse.ts";
export type { UserInfoResponseRoleEnumKey, UserInfoResponse } from "./UserInfoResponse.ts";
export type { UserNationalHealthInsurance } from "./UserNationalHealthInsurance.ts";
export type { UserNonCompulsoryHealthInsurance } from "./UserNonCompulsoryHealthInsurance.ts";
export type { UserProfile } from "./UserProfile.ts";
export type { UserProfileRequest } from "./UserProfileRequest.ts";
export type { UserProfileResponse } from "./UserProfileResponse.ts";
export type { UserResponse } from "./UserResponse.ts";
export type { VerifyOtpAndLogin200, VerifyOtpAndLoginMutationRequest, VerifyOtpAndLoginMutationResponse, VerifyOtpAndLoginMutation } from "./VerifyOtpAndLogin.ts";
export { authResponseRoleEnum } from "./AuthResponse.ts";
export { courseCategoryTypeEnum } from "./CourseCategory.ts";
export { createCourseCategoryRequestTypeEnum } from "./CreateCourseCategoryRequest.ts";
export { createExerciseCategoryRequestTypeEnum } from "./CreateExerciseCategoryRequest.ts";
export { createNewsRequestStatusEnum } from "./CreateNewsRequest.ts";
export { exerciseCategoryTypeEnum } from "./ExerciseCategory.ts";
export { getAllCoursesPaginatedQueryParamsCategoryTypeEnum } from "./GetAllCoursesPaginated.ts";
export { getAllNewsQueryParamsStatusEnum } from "./GetAllNews.ts";
export { getCategoriesByType1PathParamsTypeEnum } from "./GetCategoriesByType1.ts";
export { getCategoriesByTypePathParamsTypeEnum } from "./GetCategoriesByType.ts";
export { getCategoriesByTypePaginated1PathParamsTypeEnum } from "./GetCategoriesByTypePaginated1.ts";
export { getCategoriesByTypePaginatedPathParamsTypeEnum } from "./GetCategoriesByTypePaginated.ts";
export { newsResponseStatusEnum } from "./NewsResponse.ts";
export { purchaseTypeEnum, purchaseDiscountTypeEnum } from "./Purchase.ts";
export { transactionTypeEnum } from "./Transaction.ts";
export { updateCourseCategoryRequestTypeEnum } from "./UpdateCourseCategoryRequest.ts";
export { updateExerciseCategoryRequestTypeEnum } from "./UpdateExerciseCategoryRequest.ts";
export { updateNewsRequestStatusEnum } from "./UpdateNewsRequest.ts";
export { userRoleEnum } from "./User.ts";
export { userInfoResponseRoleEnum } from "./UserInfoResponse.ts";