/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type NationalHealthInsuranceRequest = {
    /**
     * @type string | undefined
    */
    insuranceNumber?: string;
    /**
     * @type string | undefined
    */
    placeOfRegistration?: string;
};