/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type OtpLoginRequest = {
    /**
     * @minLength 1
     * @pattern ^\+?[1-9]\d{1,14}$
     * @type string
    */
    phoneNumber: string;
};