/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ExerciseResponse } from "./ExerciseResponse.ts";
import type { PageMetadata } from "./PageMetadata.ts";

export type PagedModelExerciseResponse = {
    /**
     * @type array | undefined
    */
    content?: ExerciseResponse[];
    /**
     * @type object | undefined
    */
    page?: PageMetadata;
};