/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PresignedUrlRequest = {
    /**
     * @minLength 1
     * @type string
    */
    fileName: string;
    /**
     * @minLength 1
     * @pattern ^(video|image)/.*
     * @type string
    */
    contentType: string;
    /**
     * @pattern ^(video|image)$
     * @type string | undefined
    */
    fileType?: string;
    /**
     * @type integer | undefined, int32
    */
    durationMinutes?: number;
};