/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { User } from "./User.ts";

export const purchaseTypeEnum = {
    "PURCHASED": "PURCHASED",
    "ASSIGNED": "ASSIGNED"
} as const;

export type PurchaseTypeEnumKey = (typeof purchaseTypeEnum)[keyof typeof purchaseTypeEnum];

export const purchaseDiscountTypeEnum = {
    "NONE": "NONE",
    "COURSE_DISCOUNT": "COURSE_DISCOUNT",
    "GLOBAL_DISCOUNT": "GLOBAL_DISCOUNT"
} as const;

export type PurchaseDiscountTypeEnumKey = (typeof purchaseDiscountTypeEnum)[keyof typeof purchaseDiscountTypeEnum];

export type Purchase = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type object | undefined
    */
    user?: User;
    /**
     * @type integer, int64
    */
    courseId: number;
    /**
     * @type integer, int64
    */
    price: number;
    /**
     * @type string | undefined
    */
    type?: PurchaseTypeEnumKey;
    /**
     * @type integer | undefined, int64
    */
    assignedByUserId?: number;
    /**
     * @type string | undefined
    */
    assignedByRole?: string;
    /**
     * @type string | undefined
    */
    assignedNotes?: string;
    /**
     * @type integer, int64
    */
    originalPrice: number;
    /**
     * @type integer, int64
    */
    discountAmount: number;
    /**
     * @type integer, int64
    */
    finalPrice: number;
    /**
     * @type string | undefined
    */
    discountType?: PurchaseDiscountTypeEnumKey;
    /**
     * @type string | undefined, date-time
    */
    purchasedAt?: string;
};