/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AssignPermissionRequest } from "./AssignPermissionRequest.ts";

export type RemovePermissionFromAdminPathParams = {
    /**
     * @type integer, int64
    */
    adminId: number;
};

/**
 * @description OK
*/
export type RemovePermissionFromAdmin200 = any;

export type RemovePermissionFromAdminMutationRequest = AssignPermissionRequest;

export type RemovePermissionFromAdminMutationResponse = RemovePermissionFromAdmin200;

export type RemovePermissionFromAdminMutation = {
    Response: RemovePermissionFromAdmin200;
    Request: RemovePermissionFromAdminMutationRequest;
    PathParams: RemovePermissionFromAdminPathParams;
    Errors: any;
};