/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AssignPermissionRequest } from "./AssignPermissionRequest.ts";

export type RemovePermissionFromDoctorPathParams = {
    /**
     * @type integer, int64
    */
    doctorId: number;
};

/**
 * @description OK
*/
export type RemovePermissionFromDoctor200 = any;

export type RemovePermissionFromDoctorMutationRequest = AssignPermissionRequest;

export type RemovePermissionFromDoctorMutationResponse = RemovePermissionFromDoctor200;

export type RemovePermissionFromDoctorMutation = {
    Response: RemovePermissionFromDoctor200;
    Request: RemovePermissionFromDoctorMutationRequest;
    PathParams: RemovePermissionFromDoctorPathParams;
    Errors: any;
};