/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CourseResponse } from "./CourseResponse.ts";

export type RemoveCourseDiscountPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type RemoveCourseDiscount200 = CourseResponse;

export type RemoveCourseDiscountMutationResponse = RemoveCourseDiscount200;

export type RemoveCourseDiscountMutation = {
    Response: RemoveCourseDiscount200;
    PathParams: RemoveCourseDiscountPathParams;
    Errors: any;
};