/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CourseCategoryResponse } from "./CourseCategoryResponse.ts";

export type SearchCategories1QueryParams = {
    /**
     * @type string
    */
    keyword: string;
};

/**
 * @description OK
*/
export type SearchCategories1200 = CourseCategoryResponse[];

export type SearchCategories1QueryResponse = SearchCategories1200;

export type SearchCategories1Query = {
    Response: SearchCategories1200;
    QueryParams: SearchCategories1QueryParams;
    Errors: any;
};