/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PageCategoryResponse } from "./PageCategoryResponse.ts";

export type SearchCategoriesPaginatedQueryParams = {
    /**
     * @description Search keyword
     * @type string
    */
    keyword: string;
    /**
     * @description Page number (0-based)
     * @default 0
     * @type integer | undefined, int32
    */
    page?: number;
    /**
     * @description Number of items per page
     * @default 10
     * @type integer | undefined, int32
    */
    size?: number;
    /**
     * @description Sort by field
     * @default "name"
     * @type string | undefined
    */
    sortBy?: string;
    /**
     * @description Sort direction
     * @default "asc"
     * @type string | undefined
    */
    sortDir?: string;
};

/**
 * @description OK
*/
export type SearchCategoriesPaginated200 = PageCategoryResponse;

export type SearchCategoriesPaginatedQueryResponse = SearchCategoriesPaginated200;

export type SearchCategoriesPaginatedQuery = {
    Response: SearchCategoriesPaginated200;
    QueryParams: SearchCategoriesPaginatedQueryParams;
    Errors: any;
};