/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pageable } from "./Pageable.ts";
import type { PageCourseCategoryResponse } from "./PageCourseCategoryResponse.ts";

export type SearchCategoriesPaginated1QueryParams = {
    /**
     * @type string
    */
    keyword: string;
    /**
     * @type object
    */
    pageable: Pageable;
};

/**
 * @description OK
*/
export type SearchCategoriesPaginated1200 = PageCourseCategoryResponse;

export type SearchCategoriesPaginated1QueryResponse = SearchCategoriesPaginated1200;

export type SearchCategoriesPaginated1Query = {
    Response: SearchCategoriesPaginated1200;
    QueryParams: SearchCategoriesPaginated1QueryParams;
    Errors: any;
};