/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CourseResponse } from "./CourseResponse.ts";
import type { SetCourseDiscountRequest } from "./SetCourseDiscountRequest.ts";

export type SetCourseDiscountPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type SetCourseDiscount200 = CourseResponse;

export type SetCourseDiscountMutationRequest = SetCourseDiscountRequest;

export type SetCourseDiscountMutationResponse = SetCourseDiscount200;

export type SetCourseDiscountMutation = {
    Response: SetCourseDiscount200;
    Request: SetCourseDiscountMutationRequest;
    PathParams: SetCourseDiscountPathParams;
    Errors: any;
};