/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ExerciseProgressResponse } from "./ExerciseProgressResponse.ts";

export type SingleDayProgressResponse = {
    /**
     * @type integer | undefined, int32
    */
    dayNumber?: number;
    /**
     * @type string | undefined
    */
    dayDescription?: string;
    /**
     * @type array | undefined
    */
    exercises?: ExerciseProgressResponse[];
    /**
     * @type integer | undefined, int32
    */
    totalExercises?: number;
    /**
     * @type integer | undefined, int32
    */
    completedExercises?: number;
    /**
     * @type boolean | undefined
    */
    isCompleted?: boolean;
};