/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StartCourseRequest } from "./StartCourseRequest.ts";

/**
 * @description OK
*/
export type StartCourse200 = any;

export type StartCourseMutationRequest = StartCourseRequest;

export type StartCourseMutationResponse = StartCourse200;

export type StartCourseMutation = {
    Response: StartCourse200;
    Request: StartCourseMutationRequest;
    Errors: any;
};