/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminResponse } from "./AdminResponse.ts";

export type ToggleEnabled1PathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type ToggleEnabled1200 = AdminResponse;

export type ToggleEnabled1MutationResponse = ToggleEnabled1200;

export type ToggleEnabled1Mutation = {
    Response: ToggleEnabled1200;
    PathParams: ToggleEnabled1PathParams;
    Errors: any;
};