/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NationalHealthInsuranceRequest } from "./NationalHealthInsuranceRequest.ts";
import type { NationalHealthInsuranceResponse } from "./NationalHealthInsuranceResponse.ts";

export type UpdateNationalHealthInsurancePathParams = {
    /**
     * @type integer, int64
    */
    userId: number;
};

/**
 * @description OK
*/
export type UpdateNationalHealthInsurance200 = NationalHealthInsuranceResponse;

export type UpdateNationalHealthInsuranceMutationRequest = NationalHealthInsuranceRequest;

export type UpdateNationalHealthInsuranceMutationResponse = UpdateNationalHealthInsurance200;

export type UpdateNationalHealthInsuranceMutation = {
    Response: UpdateNationalHealthInsurance200;
    Request: UpdateNationalHealthInsuranceMutationRequest;
    PathParams: UpdateNationalHealthInsurancePathParams;
    Errors: any;
};