/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NonCompulsoryHealthInsuranceRequest } from "./NonCompulsoryHealthInsuranceRequest.ts";
import type { NonCompulsoryHealthInsuranceResponse } from "./NonCompulsoryHealthInsuranceResponse.ts";

/**
 * @description OK
*/
export type UpdateMyNonCompulsoryHealthInsurance200 = NonCompulsoryHealthInsuranceResponse;

export type UpdateMyNonCompulsoryHealthInsuranceMutationRequest = NonCompulsoryHealthInsuranceRequest;

export type UpdateMyNonCompulsoryHealthInsuranceMutationResponse = UpdateMyNonCompulsoryHealthInsurance200;

export type UpdateMyNonCompulsoryHealthInsuranceMutation = {
    Response: UpdateMyNonCompulsoryHealthInsurance200;
    Request: UpdateMyNonCompulsoryHealthInsuranceMutationRequest;
    Errors: any;
};