/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NationalHealthInsuranceRequest } from "./NationalHealthInsuranceRequest.ts";
import type { NationalHealthInsuranceResponse } from "./NationalHealthInsuranceResponse.ts";

/**
 * @description OK
*/
export type UpdateMyNationalHealthInsurance200 = NationalHealthInsuranceResponse;

export type UpdateMyNationalHealthInsuranceMutationRequest = NationalHealthInsuranceRequest;

export type UpdateMyNationalHealthInsuranceMutationResponse = UpdateMyNationalHealthInsurance200;

export type UpdateMyNationalHealthInsuranceMutation = {
    Response: UpdateMyNationalHealthInsurance200;
    Request: UpdateMyNationalHealthInsuranceMutationRequest;
    Errors: any;
};