/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const updateAppointmentStatusRequestStatusEnum = {
    "PENDING": "PENDING",
    "APPROVED": "APPROVED",
    "REJECTED": "REJECTED",
    "CANCELLED": "CANCELLED",
    "COMPLETED": "COMPLETED"
} as const;

export type UpdateAppointmentStatusRequestStatusEnumKey = (typeof updateAppointmentStatusRequestStatusEnum)[keyof typeof updateAppointmentStatusRequestStatusEnum];

export type UpdateAppointmentStatusRequest = {
    /**
     * @type string
    */
    status: UpdateAppointmentStatusRequestStatusEnumKey;
    /**
     * @type string | undefined
    */
    notes?: string;
    /**
     * @type string | undefined
    */
    rejectionReason?: string;
};