/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DoctorResponse } from "./DoctorResponse.ts";
import type { UpdateDoctorRequest } from "./UpdateDoctorRequest.ts";

export type UpdateDoctorPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type UpdateDoctor200 = DoctorResponse;

export type UpdateDoctorMutationRequest = UpdateDoctorRequest;

export type UpdateDoctorMutationResponse = UpdateDoctor200;

export type UpdateDoctorMutation = {
    Response: UpdateDoctor200;
    Request: UpdateDoctorMutationRequest;
    PathParams: UpdateDoctorPathParams;
    Errors: any;
};