/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FileUploadResponse } from "./FileUploadResponse.ts";

/**
 * @description OK
*/
export type UploadVideo200 = FileUploadResponse;

export type UploadVideoMutationRequest = {
    /**
     * @description Video file to upload
     * @type string, binary
    */
    file: Blob;
};

export type UploadVideoMutationResponse = UploadVideo200;

export type UploadVideoMutation = {
    Response: UploadVideo200;
    Request: UploadVideoMutationRequest;
    Errors: any;
};