/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UserInfo = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    fullName?: string;
    /**
     * @type string | undefined
    */
    phoneNumber?: string;
    /**
     * @type string | undefined
    */
    email?: string;
};