/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ValidateDoctorCodeResponse } from "./ValidateDoctorCodeResponse.ts";

export type ValidateCodePathParams = {
    /**
     * @type string
    */
    code: string;
};

/**
 * @description OK
*/
export type ValidateCode200 = ValidateDoctorCodeResponse;

export type ValidateCodeQueryResponse = ValidateCode200;

export type ValidateCodeQuery = {
    Response: ValidateCode200;
    PathParams: ValidateCodePathParams;
    Errors: any;
};