/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { CheckPhoneMutationRequest, CheckPhoneMutationResponse } from "../../types/authenticationController/CheckPhone.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getCheckPhoneUrl() {
  const res = { method: 'POST', url: `/api/auth/user/check-phone` as const }  
  return res
}

/**
 * @description Verify if a phone number is already registered in the system
 * @summary Check if phone number exists
 * {@link /api/auth/user/check-phone}
 */
export async function checkPhone(data: CheckPhoneMutationRequest, config: Partial<RequestConfig<CheckPhoneMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CheckPhoneMutationResponse, ResponseErrorConfig<Error>, CheckPhoneMutationRequest>({ method : "POST", url : getCheckPhoneUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}