/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { LoginWithPinMutationRequest, LoginWithPinMutationResponse } from "../../types/authenticationController/LoginWithPin.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getLoginWithPinUrl() {
  const res = { method: 'POST', url: `/api/auth/user/login-with-pin` as const }  
  return res
}

/**
 * @description Authenticate mobile user using phone number and 6-digit PIN
 * @summary Login mobile user with PIN
 * {@link /api/auth/user/login-with-pin}
 */
export async function loginWithPin(data: LoginWithPinMutationRequest, config: Partial<RequestConfig<LoginWithPinMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<LoginWithPinMutationResponse, ResponseErrorConfig<Error>, LoginWithPinMutationRequest>({ method : "POST", url : getLoginWithPinUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}