/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { SendRegistrationOtpMutationRequest, SendRegistrationOtpMutationResponse } from "../../types/authenticationController/SendRegistrationOtp.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getSendRegistrationOtpUrl() {
  const res = { method: 'POST', url: `/api/auth/user/send-registration-otp` as const }  
  return res
}

/**
 * @description Generate and send a 6-digit OTP to the provided phone number for registration
 * @summary Send registration OTP
 * {@link /api/auth/user/send-registration-otp}
 */
export async function sendRegistrationOtp(data: SendRegistrationOtpMutationRequest, config: Partial<RequestConfig<SendRegistrationOtpMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SendRegistrationOtpMutationResponse, ResponseErrorConfig<Error>, SendRegistrationOtpMutationRequest>({ method : "POST", url : getSendRegistrationOtpUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}