/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { CreateBannerMutationRequest, CreateBannerMutationResponse } from "../../types/carouselBannersController/CreateBanner.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createBannerMutationKey = () => [{ url: '/api/banners' }] as const

export type CreateBannerMutationKey = ReturnType<typeof createBannerMutationKey>

/**
 * @description Create a new carousel banner
 * @summary Create new banner
 * {@link /api/banners}
 */
export async function createBanner(data: CreateBannerMutationRequest, config: Partial<RequestConfig<CreateBannerMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateBannerMutationResponse, ResponseErrorConfig<Error>, CreateBannerMutationRequest>({ method : "POST", url : `/api/banners`, data : requestData, ... requestConfig })  
  return res.data
}

export function createBannerMutationOptions(config: Partial<RequestConfig<CreateBannerMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = createBannerMutationKey()
  return mutationOptions<CreateBannerMutationResponse, ResponseErrorConfig<Error>, {data: CreateBannerMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return createBanner(data, config)
    },
  })
}

/**
 * @description Create a new carousel banner
 * @summary Create new banner
 * {@link /api/banners}
 */
export function useCreateBanner<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateBannerMutationResponse, ResponseErrorConfig<Error>, {data: CreateBannerMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateBannerMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createBannerMutationKey()

  const baseOptions = createBannerMutationOptions(config) as UseMutationOptions<CreateBannerMutationResponse, ResponseErrorConfig<Error>, {data: CreateBannerMutationRequest}, TContext>

  return useMutation<CreateBannerMutationResponse, ResponseErrorConfig<Error>, {data: CreateBannerMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateBannerMutationResponse, ResponseErrorConfig<Error>, {data: CreateBannerMutationRequest}, TContext>
}