/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetActiveBannersQueryResponse } from "../../types/carouselBannersController/GetActiveBanners.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getActiveBannersQueryKey = () => [{ url: '/api/banners/active' }] as const

export type GetActiveBannersQueryKey = ReturnType<typeof getActiveBannersQueryKey>

/**
 * @description Retrieve all active banners that are within their display date range, ordered by display order
 * @summary Get active banners for display
 * {@link /api/banners/active}
 */
export async function getActiveBanners(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetActiveBannersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/banners/active`, ... requestConfig })  
  return res.data
}

export function getActiveBannersQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getActiveBannersQueryKey()
  return queryOptions<GetActiveBannersQueryResponse, ResponseErrorConfig<Error>, GetActiveBannersQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getActiveBanners(config)
   },
  })
}

/**
 * @description Retrieve all active banners that are within their display date range, ordered by display order
 * @summary Get active banners for display
 * {@link /api/banners/active}
 */
export function useGetActiveBanners<TData = GetActiveBannersQueryResponse, TQueryData = GetActiveBannersQueryResponse, TQueryKey extends QueryKey = GetActiveBannersQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetActiveBannersQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getActiveBannersQueryKey()

  const query = useQuery({
   ...getActiveBannersQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}