/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { CompleteAppointmentMutationResponse, CompleteAppointmentPathParams } from "../../types/CompleteAppointment.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getCompleteAppointmentUrl(id: CompleteAppointmentPathParams["id"]) {
  const res = { method: 'PUT', url: `/api/appointments/${id}/complete` as const }  
  return res
}

/**
 * @summary Mark appointment as completed (Doctor or Admin)
 * {@link /api/appointments/:id/complete}
 */
export async function completeAppointment(id: CompleteAppointmentPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<CompleteAppointmentMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "PUT", url : getCompleteAppointmentUrl(id).url.toString(), ... requestConfig })  
  return res.data
}