/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type {
  AssignPatientToDoctorMutationRequest,
  AssignPatientToDoctorMutationResponse,
  AssignPatientToDoctorPathParams,
} from "../../types/patientManagementController/AssignPatientToDoctor.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const assignPatientToDoctorMutationKey = () =>
  [{ url: "/api/admin/doctors/:doctorId/patients" }] as const;

export type AssignPatientToDoctorMutationKey = ReturnType<
  typeof assignPatientToDoctorMutationKey
>;

/**
 * @description Assign a patient (user) to a doctor
 * @summary Assign patient to doctor
 * {@link /api/admin/doctors/:doctorId/patients}
 */
export async function assignPatientToDoctor(
  doctorId: AssignPatientToDoctorPathParams["doctorId"],
  data: AssignPatientToDoctorMutationRequest,
  config: Partial<RequestConfig<AssignPatientToDoctorMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AssignPatientToDoctorMutationResponse,
    ResponseErrorConfig<Error>,
    AssignPatientToDoctorMutationRequest
  >({
    method: "POST",
    url: `/api/admin/doctors/${doctorId}/patients`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function assignPatientToDoctorMutationOptions(
  config: Partial<RequestConfig<AssignPatientToDoctorMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = assignPatientToDoctorMutationKey();
  return mutationOptions<
    AssignPatientToDoctorMutationResponse,
    ResponseErrorConfig<Error>,
    {
      doctorId: AssignPatientToDoctorPathParams["doctorId"];
      data: AssignPatientToDoctorMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ doctorId, data }) => {
      return assignPatientToDoctor(doctorId, data, config);
    },
  });
}

/**
 * @description Assign a patient (user) to a doctor
 * @summary Assign patient to doctor
 * {@link /api/admin/doctors/:doctorId/patients}
 */
export function useAssignPatientToDoctor<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AssignPatientToDoctorMutationResponse,
      ResponseErrorConfig<Error>,
      {
        doctorId: AssignPatientToDoctorPathParams["doctorId"];
        data: AssignPatientToDoctorMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AssignPatientToDoctorMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? assignPatientToDoctorMutationKey();

  const baseOptions = assignPatientToDoctorMutationOptions(
    config,
  ) as UseMutationOptions<
    AssignPatientToDoctorMutationResponse,
    ResponseErrorConfig<Error>,
    {
      doctorId: AssignPatientToDoctorPathParams["doctorId"];
      data: AssignPatientToDoctorMutationRequest;
    },
    TContext
  >;

  return useMutation<
    AssignPatientToDoctorMutationResponse,
    ResponseErrorConfig<Error>,
    {
      doctorId: AssignPatientToDoctorPathParams["doctorId"];
      data: AssignPatientToDoctorMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    AssignPatientToDoctorMutationResponse,
    ResponseErrorConfig<Error>,
    {
      doctorId: AssignPatientToDoctorPathParams["doctorId"];
      data: AssignPatientToDoctorMutationRequest;
    },
    TContext
  >;
}
