/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { appointmentContextSchema } from "./appointmentContextSchema.ts";
import { z } from "zod";

export const agoraTokenResponseSchema = z.object({
    "token": z.optional(z.string()),
"channelName": z.optional(z.string()),
"uid": z.optional(z.number().int()),
"expiryTimestamp": z.optional(z.number().int()),
"appId": z.optional(z.string()),
"appointment": z.optional(z.lazy(() => appointmentContextSchema))
    })