/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { adminInfoSchema } from "./adminInfoSchema.ts";
import { doctorInfoSchema } from "./doctorInfoSchema.ts";
import { userInfoSchema } from "./userInfoSchema.ts";
import { z } from "zod";

export const appointmentResponseSchema = z.object({
    "id": z.optional(z.number().int()),
"type": z.optional(z.enum(["IN_PERSON", "ONLINE"])),
"status": z.optional(z.enum(["PENDING", "APPROVED", "REJECTED", "CANCELLED", "COMPLETED"])),
"appointmentDateTime": z.optional(z.string().datetime()),
"durationMinutes": z.optional(z.number().int()),
"user": z.optional(z.lazy(() => userInfoSchema)),
"doctor": z.optional(z.lazy(() => doctorInfoSchema)),
"assignedByAdmin": z.optional(z.lazy(() => adminInfoSchema)),
"userNotes": z.optional(z.string()),
"adminNotes": z.optional(z.string()),
"rejectionReason": z.optional(z.string()),
"doctorCodeUsed": z.optional(z.string()),
"agoraChannelName": z.optional(z.string()),
"createdAt": z.optional(z.string().datetime()),
"updatedAt": z.optional(z.string().datetime())
    })