/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const appointmentContextSchema = z.object({
    "id": z.optional(z.number().int()),
"appointmentDateTime": z.optional(z.string().datetime()),
"durationMinutes": z.optional(z.number().int()),
"calculatedEndTime": z.optional(z.string().datetime())
    })