/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { appointmentResponseSchema } from "./appointmentResponseSchema.ts";
import { updateAppointmentStatusRequestSchema } from "./updateAppointmentStatusRequestSchema.ts";
import { z } from "zod";

export const approveAppointmentPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const approveAppointment200Schema = appointmentResponseSchema

export const approveAppointmentMutationRequestSchema = updateAppointmentStatusRequestSchema

export const approveAppointmentMutationResponseSchema = approveAppointment200Schema