/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const assignCourseRequestSchema = z.object({
    "courseId": z.number().int(),
"userIds": z.array(z.number().int()).min(1),
"notes": z.optional(z.string())
    })