/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { assignPermissionRequestSchema } from "./assignPermissionRequestSchema.ts";
import { z } from "zod";

export const assignPermissionToAdminPathParamsSchema = z.object({
    "adminId": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const assignPermissionToAdmin200Schema = z.any()

export const assignPermissionToAdminMutationRequestSchema = z.lazy(() => assignPermissionRequestSchema)

export const assignPermissionToAdminMutationResponseSchema = z.lazy(() => assignPermissionToAdmin200Schema)