/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { purchaseResponseSchema } from "./purchaseResponseSchema.ts";
import { z } from "zod";

export const buyCoursePathParamsSchema = z.object({
    "courseId": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const buyCourse200Schema = purchaseResponseSchema

export const buyCourseMutationResponseSchema = buyCourse200Schema