/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const carouselBannerListResponseSchema = z.object({
    "id": z.optional(z.number().int()),
"title": z.optional(z.string()),
"description": z.optional(z.string()),
"imageUrl": z.optional(z.string()),
"linkUrl": z.optional(z.string()),
"displayOrder": z.optional(z.number().int())
    })