/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { courseSchema } from "./courseSchema.ts";
import { z } from "zod";

export const courseCategorySchema = z.object({
    "id": z.optional(z.number().int()),
"name": z.string().min(1),
"description": z.optional(z.string()),
"type": z.optional(z.enum(["BODY_PART", "RECOVERY_STAGE", "HEALTH_CONDITION", "DIFFICULTY_LEVEL", "EXERCISE_TYPE"])),
"courses": z.optional(z.array(z.lazy(() => courseSchema))),
"createdAt": z.optional(z.string().datetime()),
"updatedAt": z.optional(z.string().datetime())
    })