/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { dayProgressResponseSchema } from "./dayProgressResponseSchema.ts";
import { z } from "zod";

export const courseProgressResponseSchema = z.object({
    "userCourseProgressId": z.optional(z.number().int()),
"courseId": z.optional(z.number().int()),
"courseTitle": z.optional(z.string()),
"courseDescription": z.optional(z.string()),
"courseImageUrl": z.optional(z.string()),
"currentDayNumber": z.optional(z.number().int()),
"totalDays": z.optional(z.number().int()),
"totalExercises": z.optional(z.number().int()),
"completedExercises": z.optional(z.number().int()),
"progressPercentage": z.optional(z.number()),
"isCompleted": z.optional(z.boolean()),
"startedAt": z.optional(z.string().datetime()),
"completedAt": z.optional(z.string().datetime()),
"updatedAt": z.optional(z.string().datetime()),
"lastDayCompletedDate": z.optional(z.string().date()),
"isCurrentDayRestricted": z.optional(z.boolean()),
"days": z.optional(z.array(z.lazy(() => dayProgressResponseSchema)))
    })