/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { courseCategorySchema } from "./courseCategorySchema.ts";
import { courseDaySchema } from "./courseDaySchema.ts";
import { z } from "zod";

export const courseSchema = z.object({
    "id": z.optional(z.number().int()),
"title": z.string().min(1),
"description": z.string().min(1),
"imageUrl": z.string().min(1),
"price": z.number().int(),
"courseDays": z.optional(z.array(z.lazy(() => courseDaySchema))),
"durationDays": z.optional(z.number().int()),
"courseCategory": z.optional(z.lazy(() => courseCategorySchema)),
"isCustom": z.optional(z.boolean()),
"createdByUserId": z.optional(z.number().int()),
"createdByRole": z.optional(z.string()),
"isPublic": z.optional(z.boolean()),
"createdAt": z.optional(z.string().datetime()),
"updatedAt": z.optional(z.string().datetime())
    })