/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { adminResponseSchema } from "./adminResponseSchema.ts";
import { createAdminRequestSchema } from "./createAdminRequestSchema.ts";
import { z } from "zod";

/**
 * @description OK
 */
export const createAdmin200Schema = z.lazy(() => adminResponseSchema)

export const createAdminMutationRequestSchema = z.lazy(() => createAdminRequestSchema)

export const createAdminMutationResponseSchema = z.lazy(() => createAdmin200Schema)