/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createRehabilitationExaminationFormRequestSchema } from "./createRehabilitationExaminationFormRequestSchema.ts";
import { rehabilitationExaminationFormResponseSchema } from "./rehabilitationExaminationFormResponseSchema.ts";
import { z } from "zod";

/**
 * @description OK
 */
export const createForm200Schema = z.lazy(() => rehabilitationExaminationFormResponseSchema)

export const createFormMutationRequestSchema = z.lazy(() => createRehabilitationExaminationFormRequestSchema)

export const createFormMutationResponseSchema = z.lazy(() => createForm200Schema)