/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { courseRatingResponseSchema } from "./courseRatingResponseSchema.ts";
import { createCourseRatingRequestSchema } from "./createCourseRatingRequestSchema.ts";

/**
 * @description OK
 */
export const createRating200Schema = courseRatingResponseSchema

export const createRatingMutationRequestSchema = createCourseRatingRequestSchema

export const createRatingMutationResponseSchema = createRating200Schema