/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const createCarouselBannerRequestSchema = z.object({
    "title": z.string().min(1),
"description": z.optional(z.string()),
"imageUrl": z.string().min(1),
"linkUrl": z.optional(z.string()),
"displayOrder": z.number().int(),
"startDate": z.optional(z.string().datetime()),
"endDate": z.optional(z.string().datetime())
    })