/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const deleteCategory1PathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const deleteCategory1200Schema = z.any()

export const deleteCategory1MutationResponseSchema = deleteCategory1200Schema