/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const deleteRatingPathParamsSchema = z.object({
    "courseId": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const deleteRating200Schema = z.any()

export const deleteRatingMutationResponseSchema = deleteRating200Schema