/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const deleteAdminPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const deleteAdmin200Schema = z.any()

export const deleteAdminMutationResponseSchema = z.lazy(() => deleteAdmin200Schema)