/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const doctorAccessCodeResponseSchema = z.object({
    "id": z.optional(z.number().int()),
"doctorId": z.optional(z.number().int()),
"doctorName": z.optional(z.string()),
"code": z.optional(z.string()),
"isActive": z.optional(z.boolean()),
"expiresAt": z.optional(z.string().datetime()),
"isExpired": z.optional(z.boolean()),
"createdAt": z.optional(z.string().datetime()),
"updatedAt": z.optional(z.string().datetime())
    })