/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const generateVideoViewingUrlQueryParamsSchema = z.object({
    "fileUrl": z.string().describe("Full video file URL"),
"durationMinutes": z.optional(z.coerce.number().int().default(5).describe("URL expiration duration in minutes"))
    })

/**
 * @description OK
 */
export const generateVideoViewingUrl200Schema = z.string()

export const generateVideoViewingUrlQueryResponseSchema = generateVideoViewingUrl200Schema