/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { adminResponseSchema } from "./adminResponseSchema.ts";
import { z } from "zod";

export const getAdminByIdPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const getAdminById200Schema = z.lazy(() => adminResponseSchema)

export const getAdminByIdQueryResponseSchema = z.lazy(() => getAdminById200Schema)