/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableSchema } from "./pageableSchema.ts";
import { pagedModelRehabilitationExaminationFormResponseSchema } from "./pagedModelRehabilitationExaminationFormResponseSchema.ts";
import { z } from "zod";

export const getAllFormsQueryParamsSchema = z.object({
    "pageable": z.lazy(() => pageableSchema)
    })

/**
 * @description OK
 */
export const getAllForms200Schema = pagedModelRehabilitationExaminationFormResponseSchema

export const getAllFormsQueryResponseSchema = getAllForms200Schema