/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { courseCategoryResponseSchema } from "./courseCategoryResponseSchema.ts";
import { z } from "zod";

/**
 * @description OK
 */
export const getAllCategories1200Schema = z.array(z.lazy(() => courseCategoryResponseSchema))

export const getAllCategories1QueryResponseSchema = z.lazy(() => getAllCategories1200Schema)