/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { carouselBannerListResponseSchema } from "./carouselBannerListResponseSchema.ts";
import { z } from "zod";

/**
 * @description OK
 */
export const getActiveBanners200Schema = z.array(carouselBannerListResponseSchema)

export const getActiveBannersQueryResponseSchema = getActiveBanners200Schema