/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableSchema } from "./pageableSchema.ts";
import { pageUserResponseSchema } from "./pageUserResponseSchema.ts";
import { z } from "zod";

export const getAllUsersPaginatedQueryParamsSchema = z.object({
    "pageable": z.lazy(() => pageableSchema)
    })

/**
 * @description OK
 */
export const getAllUsersPaginated200Schema = z.lazy(() => pageUserResponseSchema)

export const getAllUsersPaginatedQueryResponseSchema = z.lazy(() => getAllUsersPaginated200Schema)