/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { availableTimeSlotsResponseSchema } from "./availableTimeSlotsResponseSchema.ts";
import { z } from "zod";

export const getAvailableSlotsQueryParamsSchema = z.object({
    "doctorId": z.coerce.number().int(),
"date": z.string().date()
    })

/**
 * @description OK
 */
export const getAvailableSlots200Schema = availableTimeSlotsResponseSchema

export const getAvailableSlotsQueryResponseSchema = getAvailableSlots200Schema