/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableSchema } from "./pageableSchema.ts";
import { pagedModelAdminResponseSchema } from "./pagedModelAdminResponseSchema.ts";
import { z } from "zod";

export const getAllAdminsQueryParamsSchema = z.object({
    "pageable": z.lazy(() => pageableSchema)
    })

/**
 * @description OK
 */
export const getAllAdmins200Schema = pagedModelAdminResponseSchema

export const getAllAdminsQueryResponseSchema = getAllAdmins200Schema