/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { courseCategoryResponseSchema } from "./courseCategoryResponseSchema.ts";
import { z } from "zod";

export const getCategoryById1PathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const getCategoryById1200Schema = z.lazy(() => courseCategoryResponseSchema)

export const getCategoryById1QueryResponseSchema = z.lazy(() => getCategoryById1200Schema)