/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { courseCategoryResponseSchema } from "./courseCategoryResponseSchema.ts";
import { z } from "zod";

export const getCategoriesByType1PathParamsSchema = z.object({
    "type": z.enum(["BODY_PART", "RECOVERY_STAGE", "HEALTH_CONDITION", "DIFFICULTY_LEVEL", "EXERCISE_TYPE"])
    })

/**
 * @description OK
 */
export const getCategoriesByType1200Schema = z.array(z.lazy(() => courseCategoryResponseSchema))

export const getCategoriesByType1QueryResponseSchema = z.lazy(() => getCategoriesByType1200Schema)