/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { courseResponseSchema } from "./courseResponseSchema.ts";
import { z } from "zod";

export const getCoursesByCategoryPathParamsSchema = z.object({
    "categoryId": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const getCoursesByCategory200Schema = z.array(z.lazy(() => courseResponseSchema))

export const getCoursesByCategoryQueryResponseSchema = z.lazy(() => getCoursesByCategory200Schema)