/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { globalDiscountResponseSchema } from "./globalDiscountResponseSchema.ts";

/**
 * @description OK
 */
export const getGlobalDiscount200Schema = globalDiscountResponseSchema

export const getGlobalDiscountQueryResponseSchema = getGlobalDiscount200Schema