/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { nonCompulsoryHealthInsuranceResponseSchema } from "./nonCompulsoryHealthInsuranceResponseSchema.ts";
import { z } from "zod";

/**
 * @description OK
 */
export const getMyNonCompulsoryHealthInsurance200Schema = z.lazy(() => nonCompulsoryHealthInsuranceResponseSchema)

export const getMyNonCompulsoryHealthInsuranceQueryResponseSchema = z.lazy(() => getMyNonCompulsoryHealthInsurance200Schema)