/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { purchaseResponseSchema } from "./purchaseResponseSchema.ts";
import { z } from "zod";

/**
 * @description OK
 */
export const getMyPurchases200Schema = z.array(purchaseResponseSchema)

export const getMyPurchasesQueryResponseSchema = getMyPurchases200Schema