/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableSchema } from "./pageableSchema.ts";
import { pagePurchaseResponseSchema } from "./pagePurchaseResponseSchema.ts";
import { z } from "zod";

export const getMyPurchasesPaginatedQueryParamsSchema = z.object({
    "pageable": z.lazy(() => pageableSchema)
    })

/**
 * @description OK
 */
export const getMyPurchasesPaginated200Schema = z.lazy(() => pagePurchaseResponseSchema)

export const getMyPurchasesPaginatedQueryResponseSchema = z.lazy(() => getMyPurchasesPaginated200Schema)