/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { doctorAccessCodeResponseSchema } from "./doctorAccessCodeResponseSchema.ts";
import { z } from "zod";

/**
 * @description OK
 */
export const getMyCodes200Schema = z.array(doctorAccessCodeResponseSchema)

export const getMyCodesQueryResponseSchema = getMyCodes200Schema