/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableSchema } from "./pageableSchema.ts";
import { pagedModelCourseResponseSchema } from "./pagedModelCourseResponseSchema.ts";
import { z } from "zod";

export const getMyOwnedCoursesQueryParamsSchema = z.object({
    "pageable": z.lazy(() => pageableSchema)
    })

/**
 * @description OK
 */
export const getMyOwnedCourses200Schema = z.lazy(() => pagedModelCourseResponseSchema)

export const getMyOwnedCoursesQueryResponseSchema = z.lazy(() => getMyOwnedCourses200Schema)