/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableSchema } from "./pageableSchema.ts";
import { pagedModelAppointmentResponseSchema } from "./pagedModelAppointmentResponseSchema.ts";
import { z } from "zod";

export const getMyAppointmentsQueryParamsSchema = z.object({
    "pageable": z.lazy(() => pageableSchema)
    })

/**
 * @description OK
 */
export const getMyAppointments200Schema = pagedModelAppointmentResponseSchema

export const getMyAppointmentsQueryResponseSchema = getMyAppointments200Schema