/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { newsResponseSchema } from "./newsResponseSchema.ts";
import { z } from "zod";

export const getNewsByIdPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const getNewsById200Schema = newsResponseSchema

export const getNewsByIdQueryResponseSchema = getNewsById200Schema