/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { nationalHealthInsuranceResponseSchema } from "./nationalHealthInsuranceResponseSchema.ts";
import { z } from "zod";

export const getNationalHealthInsurancePathParamsSchema = z.object({
    "userId": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const getNationalHealthInsurance200Schema = z.lazy(() => nationalHealthInsuranceResponseSchema)

export const getNationalHealthInsuranceQueryResponseSchema = z.lazy(() => getNationalHealthInsurance200Schema)