/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableSchema } from "./pageableSchema.ts";
import { pagedModelActivityResponseSchema } from "./pagedModelActivityResponseSchema.ts";
import { z } from "zod";

export const getRecentActivityQueryParamsSchema = z.object({
    "pageable": z.lazy(() => pageableSchema)
    })

/**
 * @description OK
 */
export const getRecentActivity200Schema = pagedModelActivityResponseSchema

export const getRecentActivityQueryResponseSchema = getRecentActivity200Schema