/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const nationalHealthInsuranceResponseSchema = z.object({
    "id": z.optional(z.number().int()),
"userId": z.optional(z.number().int()),
"insuranceNumber": z.optional(z.string()),
"placeOfRegistration": z.optional(z.string()),
"createdAt": z.optional(z.string().datetime()),
"updatedAt": z.optional(z.string().datetime())
    })