/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageMetadataSchema } from "./pageMetadataSchema.ts";
import { purchaseResponseSchema } from "./purchaseResponseSchema.ts";
import { z } from "zod";

export const pagedModelPurchaseResponseSchema = z.object({
    "content": z.optional(z.array(z.lazy(() => purchaseResponseSchema))),
"page": z.optional(z.lazy(() => pageMetadataSchema))
    })