/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { newsResponseSchema } from "./newsResponseSchema.ts";
import { pageMetadataSchema } from "./pageMetadataSchema.ts";
import { z } from "zod";

export const pagedModelNewsResponseSchema = z.object({
    "content": z.optional(z.array(z.lazy(() => newsResponseSchema))),
"page": z.optional(z.lazy(() => pageMetadataSchema))
    })