/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { newsResponseSchema } from "./newsResponseSchema.ts";
import { pageableObjectSchema } from "./pageableObjectSchema.ts";
import { sortObjectSchema } from "./sortObjectSchema.ts";
import { z } from "zod";

export const pageNewsResponseSchema = z.object({
    "totalElements": z.optional(z.number().int()),
"totalPages": z.optional(z.number().int()),
"first": z.optional(z.boolean()),
"last": z.optional(z.boolean()),
"size": z.optional(z.number().int()),
"content": z.optional(z.array(z.lazy(() => newsResponseSchema))),
"number": z.optional(z.number().int()),
"sort": z.optional(z.lazy(() => sortObjectSchema)),
"numberOfElements": z.optional(z.number().int()),
"pageable": z.optional(z.lazy(() => pageableObjectSchema)),
"empty": z.optional(z.boolean())
    })