/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { courseResponseSchema } from "./courseResponseSchema.ts";
import { pageMetadataSchema } from "./pageMetadataSchema.ts";
import { z } from "zod";

export const pagedModelCourseResponseSchema = z.object({
    "content": z.optional(z.array(z.lazy(() => courseResponseSchema))),
"page": z.optional(z.lazy(() => pageMetadataSchema))
    })