/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { userSchema } from "./userSchema.ts";
import { z } from "zod";

export const purchaseSchema = z.object({
    "id": z.optional(z.number().int()),
"user": z.optional(z.lazy(() => userSchema)),
"courseId": z.number().int(),
"price": z.number().int(),
"type": z.optional(z.enum(["PURCHASED", "ASSIGNED"])),
"assignedByUserId": z.optional(z.number().int()),
"assignedByRole": z.optional(z.string()),
"assignedNotes": z.optional(z.string()),
"originalPrice": z.number().int(),
"discountAmount": z.number().int(),
"finalPrice": z.number().int(),
"discountType": z.optional(z.enum(["NONE", "COURSE_DISCOUNT", "GLOBAL_DISCOUNT"])),
"purchasedAt": z.optional(z.string().datetime())
    })