/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { appointmentResponseSchema } from "./appointmentResponseSchema.ts";
import { rejectAppointmentRequestSchema } from "./rejectAppointmentRequestSchema.ts";
import { z } from "zod";

export const rejectAppointmentPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const rejectAppointment200Schema = appointmentResponseSchema

export const rejectAppointmentMutationRequestSchema = rejectAppointmentRequestSchema

export const rejectAppointmentMutationResponseSchema = rejectAppointment200Schema