/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableSchema } from "./pageableSchema.ts";
import { pagedModelExerciseCategoryResponseSchema } from "./pagedModelExerciseCategoryResponseSchema.ts";
import { z } from "zod";

export const searchCategoriesPaginatedQueryParamsSchema = z.object({
    "keyword": z.string(),
"pageable": z.lazy(() => pageableSchema)
    })

/**
 * @description OK
 */
export const searchCategoriesPaginated200Schema = z.lazy(() => pagedModelExerciseCategoryResponseSchema)

export const searchCategoriesPaginatedQueryResponseSchema = z.lazy(() => searchCategoriesPaginated200Schema)