/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { courseResponseSchema } from "./courseResponseSchema.ts";
import { setCourseDiscountRequestSchema } from "./setCourseDiscountRequestSchema.ts";
import { z } from "zod";

export const setCourseDiscountPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const setCourseDiscount200Schema = courseResponseSchema

export const setCourseDiscountMutationRequestSchema = setCourseDiscountRequestSchema

export const setCourseDiscountMutationResponseSchema = setCourseDiscount200Schema