/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { carouselBannerResponseSchema } from "./carouselBannerResponseSchema.ts";
import { updateBannerStatusRequestSchema } from "./updateBannerStatusRequestSchema.ts";
import { z } from "zod";

export const toggleBannerStatusPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const toggleBannerStatus200Schema = carouselBannerResponseSchema

export const toggleBannerStatusMutationRequestSchema = updateBannerStatusRequestSchema

export const toggleBannerStatusMutationResponseSchema = toggleBannerStatus200Schema