/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { newsResponseSchema } from "./newsResponseSchema.ts";
import { z } from "zod";

export const togglePinPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const togglePin200Schema = z.lazy(() => newsResponseSchema)

export const togglePinMutationResponseSchema = z.lazy(() => togglePin200Schema)