/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const transactionSchema = z.object({
    "id": z.optional(z.number().int()),
"user": z.optional(z.any()),
"type": z.enum(["CREDIT", "DEBIT"]),
"amount": z.number().int(),
"description": z.optional(z.string()),
"createdAt": z.optional(z.string().datetime())
    })