/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const transactionResponseSchema = z.object({
    "id": z.optional(z.number().int()),
"type": z.optional(z.string()),
"amount": z.optional(z.number().int()),
"description": z.optional(z.string()),
"createdAt": z.optional(z.string().datetime())
    })