/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { nationalHealthInsuranceRequestSchema } from "./nationalHealthInsuranceRequestSchema.ts";
import { nationalHealthInsuranceResponseSchema } from "./nationalHealthInsuranceResponseSchema.ts";

/**
 * @description OK
 */
export const updateMyNationalHealthInsurance200Schema = nationalHealthInsuranceResponseSchema

export const updateMyNationalHealthInsuranceMutationRequestSchema = nationalHealthInsuranceRequestSchema

export const updateMyNationalHealthInsuranceMutationResponseSchema = updateMyNationalHealthInsurance200Schema