/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { exerciseResponseSchema } from "./exerciseResponseSchema.ts";
import { updateExerciseRequestSchema } from "./updateExerciseRequestSchema.ts";
import { z } from "zod";

export const updateExercisePathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const updateExercise200Schema = exerciseResponseSchema

export const updateExerciseMutationRequestSchema = updateExerciseRequestSchema

export const updateExerciseMutationResponseSchema = updateExercise200Schema