/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { doctorAccessCodeResponseSchema } from "./doctorAccessCodeResponseSchema.ts";
import { updateDoctorAccessCodeRequestSchema } from "./updateDoctorAccessCodeRequestSchema.ts";
import { z } from "zod";

export const updateCodePathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const updateCode200Schema = doctorAccessCodeResponseSchema

export const updateCodeMutationRequestSchema = updateDoctorAccessCodeRequestSchema

export const updateCodeMutationResponseSchema = updateCode200Schema