/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { exerciseResponseSchema } from "./exerciseResponseSchema.ts";
import { updateExerciseRequestSchema } from "./updateExerciseRequestSchema.ts";
import { z } from "zod";

export const updateExercisePathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const updateExercise200Schema = z.lazy(() => exerciseResponseSchema)

export const updateExerciseMutationRequestSchema = z.lazy(() => updateExerciseRequestSchema)

export const updateExerciseMutationResponseSchema = z.lazy(() => updateExercise200Schema)