/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { doctorResponseSchema } from "./doctorResponseSchema.ts";
import { updateDoctorRequestSchema } from "./updateDoctorRequestSchema.ts";
import { z } from "zod";

export const updateDoctorPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const updateDoctor200Schema = z.lazy(() => doctorResponseSchema)

export const updateDoctorMutationRequestSchema = z.lazy(() => updateDoctorRequestSchema)

export const updateDoctorMutationResponseSchema = z.lazy(() => updateDoctor200Schema)