/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { userProfileRequestSchema } from "./userProfileRequestSchema.ts";
import { userProfileResponseSchema } from "./userProfileResponseSchema.ts";

/**
 * @description OK
 */
export const updateMyProfile200Schema = userProfileResponseSchema

export const updateMyProfileMutationRequestSchema = userProfileRequestSchema

export const updateMyProfileMutationResponseSchema = updateMyProfile200Schema