/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { exerciseCategoryResponseSchema } from "./exerciseCategoryResponseSchema.ts";
import { updateExerciseCategoryRequestSchema } from "./updateExerciseCategoryRequestSchema.ts";
import { z } from "zod";

export const updateCategoryPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const updateCategory200Schema = z.lazy(() => exerciseCategoryResponseSchema)

export const updateCategoryMutationRequestSchema = z.lazy(() => updateExerciseCategoryRequestSchema)

export const updateCategoryMutationResponseSchema = z.lazy(() => updateCategory200Schema)