/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const userCompanyInfoSchema = z.object({
    "id": z.optional(z.number().int()),
"user": z.optional(z.any()),
"companyName": z.optional(z.string()),
"companyTaxNumber": z.optional(z.string()),
"invoiceIssuanceAddress": z.optional(z.string()),
"createdAt": z.optional(z.string().datetime()),
"updatedAt": z.optional(z.string().datetime())
    })