/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { userSchema } from "./userSchema.ts";
import { z } from "zod";

export const userBalanceSchema = z.object({
    "id": z.optional(z.number().int()),
"user": z.optional(z.lazy(() => userSchema)),
"balance": z.number().int(),
"createdAt": z.optional(z.string().datetime()),
"updatedAt": z.optional(z.string().datetime())
    })