/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod";

export const userProfileResponseSchema = z.object({
    "id": z.optional(z.number().int()),
"userId": z.optional(z.number().int()),
"vietnameseIdentityCard": z.optional(z.string()),
"jobTitle": z.optional(z.string()),
"address": z.optional(z.string()),
"nationality": z.optional(z.string()),
"ethnic": z.optional(z.string()),
"createdAt": z.optional(z.string().datetime()),
"updatedAt": z.optional(z.string().datetime())
    })