/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { couponValidationResponseSchema } from "./couponValidationResponseSchema.ts";
import { validateCouponRequestSchema } from "./validateCouponRequestSchema.ts";

/**
 * @description OK
 */
export const validateCoupon200Schema = couponValidationResponseSchema

export const validateCouponMutationRequestSchema = validateCouponRequestSchema

export const validateCouponMutationResponseSchema = validateCoupon200Schema