/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { authResponseSchema } from "./authResponseSchema.ts";
import { otpVerificationRequestSchema } from "./otpVerificationRequestSchema.ts";
import { z } from "zod";

/**
 * @description OK
 */
export const verifyOtpAndLogin200Schema = z.lazy(() => authResponseSchema)

export const verifyOtpAndLoginMutationRequestSchema = z.lazy(() => otpVerificationRequestSchema)

export const verifyOtpAndLoginMutationResponseSchema = z.lazy(() => verifyOtpAndLogin200Schema)