/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { courseAssignmentRequestResponseSchema } from "../courseAssignmentRequestResponseSchema.ts";
import { createCourseRequestRequestSchema } from "../createCourseRequestRequestSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const createCourseRequest200Schema = z.lazy(
  () => courseAssignmentRequestResponseSchema,
);

export const createCourseRequestMutationRequestSchema = z.lazy(
  () => createCourseRequestRequestSchema,
);

export const createCourseRequestMutationResponseSchema = z.lazy(
  () => createCourseRequest200Schema,
);
