/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BalanceResponse } from "../BalanceResponse.ts";

/**
 * @description OK
 */
export type GetMyBalance200 = BalanceResponse;

export type GetMyBalanceQueryResponse = GetMyBalance200;

export type GetMyBalanceQuery = {
  Response: GetMyBalance200;
  Errors: any;
};
