/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pageable } from "../Pageable.ts";
import type { PagedModel } from "../PagedModel.ts";

export type GetAllCategoriesQueryParams = {
    /**
     * @type object
    */
    pageable: Pageable;
};

/**
 * @description OK
*/
export type GetAllCategories200 = PagedModel;

export type GetAllCategoriesQueryResponse = GetAllCategories200;

export type GetAllCategoriesQuery = {
    Response: GetAllCategories200;
    QueryParams: GetAllCategoriesQueryParams;
    Errors: any;
};