/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CategoryResponse } from "../CategoryResponse.ts";

export const getCategoriesByTypePathParamsTypeEnum = {
    "BODY_PART": "BODY_PART",
    "RECOVERY_STAGE": "RECOVERY_STAGE",
    "HEALTH_CONDITION": "HEALTH_CONDITION",
    "DIFFICULTY_LEVEL": "DIFFICULTY_LEVEL",
    "EXERCISE_TYPE": "EXERCISE_TYPE"
} as const;

export type GetCategoriesByTypePathParamsTypeEnumKey = (typeof getCategoriesByTypePathParamsTypeEnum)[keyof typeof getCategoriesByTypePathParamsTypeEnum];

export type GetCategoriesByTypePathParams = {
    /**
     * @description Category type
     * @type string
    */
    type: GetCategoriesByTypePathParamsTypeEnumKey;
};

/**
 * @description OK
*/
export type GetCategoriesByType200 = CategoryResponse[];

export type GetCategoriesByTypeQueryResponse = GetCategoriesByType200;

export type GetCategoriesByTypeQuery = {
    Response: GetCategoriesByType200;
    PathParams: GetCategoriesByTypePathParams;
    Errors: any;
};