/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pageable } from "../Pageable.ts";
import type { PageCategoryResponse } from "../PageCategoryResponse.ts";

export type SearchCategoriesByNameQueryParams = {
    /**
     * @description Search query
     * @type string
    */
    query: string;
    /**
     * @type object
    */
    pageable: Pageable;
};

/**
 * @description OK
*/
export type SearchCategoriesByName200 = PageCategoryResponse;

export type SearchCategoriesByNameQueryResponse = SearchCategoriesByName200;

export type SearchCategoriesByNameQuery = {
    Response: SearchCategoriesByName200;
    QueryParams: SearchCategoriesByNameQueryParams;
    Errors: any;
};