/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { CreateScheduleMutationRequest, CreateScheduleMutationResponse } from "../../types/CreateSchedule.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getCreateScheduleUrl() {
  const res = { method: 'POST', url: `/api/doctor-schedules` as const }  
  return res
}

/**
 * @summary Create weekly schedule (Doctor only)
 * {@link /api/doctor-schedules}
 */
export async function createSchedule(data: CreateScheduleMutationRequest, config: Partial<RequestConfig<CreateScheduleMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateScheduleMutationResponse, ResponseErrorConfig<Error>, CreateScheduleMutationRequest>({ method : "POST", url : getCreateScheduleUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}