/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetMyScheduleQueryResponse } from "../../types/GetMySchedule.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetMyScheduleUrl() {
  const res = { method: 'GET', url: `/api/doctor-schedules/my-schedule` as const }  
  return res
}

/**
 * @summary Get own schedule (Doctor only)
 * {@link /api/doctor-schedules/my-schedule}
 */
export async function getMySchedule(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMyScheduleQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetMyScheduleUrl().url.toString(), ... requestConfig })  
  return res.data
}