/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableSchema } from "../pageableSchema.ts";
import { pagedModelSchema } from "../pagedModelSchema.ts";
import { z } from "zod/v4";

export const getMyFormsQueryParamsSchema = z.object({
    get "pageable"(){
                return pageableSchema
              }
    })

/**
 * @description OK
 */
export const getMyForms200Schema = z.lazy(() => pagedModelSchema)

export const getMyFormsQueryResponseSchema = z.lazy(() => getMyForms200Schema)