/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetCoursesByCategoryQueryResponse, GetCoursesByCategoryPathParams } from "../../types/GetCoursesByCategory.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetCoursesByCategoryUrl(categoryId: GetCoursesByCategoryPathParams["categoryId"]) {
  const res = { method: 'GET', url: `/api/courses/category/${categoryId}` as const }  
  return res
}

/**
 * @description Retrieve all courses belonging to a specific category
 * @summary Get courses by category
 * {@link /api/courses/category/:categoryId}
 */
export async function getCoursesByCategory(categoryId: GetCoursesByCategoryPathParams["categoryId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCoursesByCategoryQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetCoursesByCategoryUrl(categoryId).url.toString(), ... requestConfig })  
  return res.data
}