/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { SetCourseDiscountMutationRequest, SetCourseDiscountMutationResponse, SetCourseDiscountPathParams } from "../../types/SetCourseDiscount.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getSetCourseDiscountUrl(id: SetCourseDiscountPathParams["id"]) {
  const res = { method: 'PATCH', url: `/api/courses/${id}/discount` as const }  
  return res
}

/**
 * @description Set or update discount for a course (Admin only)
 * @summary Set course discount
 * {@link /api/courses/:id/discount}
 */
export async function setCourseDiscount(id: SetCourseDiscountPathParams["id"], data: SetCourseDiscountMutationRequest, config: Partial<RequestConfig<SetCourseDiscountMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SetCourseDiscountMutationResponse, ResponseErrorConfig<Error>, SetCourseDiscountMutationRequest>({ method : "PATCH", url : getSetCourseDiscountUrl(id).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}