/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CheckPackageAccessPathParams = {
    /**
     * @description Exercise Package ID
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type CheckPackageAccess200 = boolean;

export type CheckPackageAccessQueryResponse = CheckPackageAccess200;

export type CheckPackageAccessQuery = {
    Response: CheckPackageAccess200;
    PathParams: CheckPackageAccessPathParams;
    Errors: any;
};