/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ExercisePackageResponse } from "../ExercisePackageResponse.ts";

export type GetRandomAvailablePackagesQueryParams = {
    /**
     * @description Number of random packages to return (default 5, max 20)
     * @default 5
     * @type integer | undefined, int32
    */
    size?: number;
};

/**
 * @description OK
*/
export type GetRandomAvailablePackages200 = ExercisePackageResponse[];

export type GetRandomAvailablePackagesQueryResponse = GetRandomAvailablePackages200;

export type GetRandomAvailablePackagesQuery = {
    Response: GetRandomAvailablePackages200;
    QueryParams: GetRandomAvailablePackagesQueryParams;
    Errors: any;
};