/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/api-client'
import type {
  GetAllFeedbackForCourseQueryResponse,
  GetAllFeedbackForCourseQueryParams,
} from '../../types/courseDayFeedbackController/GetAllFeedbackForCourse.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/api-client'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getAllFeedbackForCourseSuspenseQueryKey = (
  params: GetAllFeedbackForCourseQueryParams
) =>
  [
    { url: '/api/course-progress/admin/feedback' },
    ...(params ? [params] : []),
  ] as const

export type GetAllFeedbackForCourseSuspenseQueryKey = ReturnType<
  typeof getAllFeedbackForCourseSuspenseQueryKey
>

/**
 * @description Admin/staff view of all daily feedback entries for a course, including all fields (completion %, effort %, pain, hardest exercise, general notes).
 * @summary Get all feedback for a course (admin)
 * {@link /api/course-progress/admin/feedback}
 */
export async function getAllFeedbackForCourseSuspense(
  params: GetAllFeedbackForCourseQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetAllFeedbackForCourseQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: `/api/course-progress/admin/feedback`,
    params,
    ...requestConfig,
  })
  return res.data
}

export function getAllFeedbackForCourseSuspenseQueryOptions(
  params: GetAllFeedbackForCourseQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = getAllFeedbackForCourseSuspenseQueryKey(params)
  return queryOptions<
    GetAllFeedbackForCourseQueryResponse,
    ResponseErrorConfig<Error>,
    GetAllFeedbackForCourseQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getAllFeedbackForCourseSuspense(params, config)
    },
  })
}

/**
 * @description Admin/staff view of all daily feedback entries for a course, including all fields (completion %, effort %, pain, hardest exercise, general notes).
 * @summary Get all feedback for a course (admin)
 * {@link /api/course-progress/admin/feedback}
 */
export function useGetAllFeedbackForCourseSuspense<
  TData = GetAllFeedbackForCourseQueryResponse,
  TQueryKey extends QueryKey = GetAllFeedbackForCourseSuspenseQueryKey,
>(
  params: GetAllFeedbackForCourseQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetAllFeedbackForCourseQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey =
    queryOptions?.queryKey ?? getAllFeedbackForCourseSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...getAllFeedbackForCourseSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
