/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type {
  SubmitFeedbackMutationRequest,
  SubmitFeedbackMutationResponse,
  SubmitFeedbackPathParams,
  SubmitFeedback400,
  SubmitFeedback404,
  SubmitFeedback409,
} from "../../types/courseDayFeedbackController/SubmitFeedback.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const submitFeedbackMutationKey = () =>
  [{ url: "/api/course-progress/days/:courseDayId/feedback" }] as const;

export type SubmitFeedbackMutationKey = ReturnType<
  typeof submitFeedbackMutationKey
>;

/**
 * @description Allows users to provide detailed feedback after completing all exercises in a course day. Users can only submit feedback for the day they just completed (currentDayNumber - 1). Once they move to the next day, the feedback window for the previous day closes. Feedback includes completion percentage, effort level, pain tracking, hardest exercise, and general notes.
 * @summary Submit feedback for a completed day
 * {@link /api/course-progress/days/:courseDayId/feedback}
 */
export async function submitFeedback(
  courseDayId: SubmitFeedbackPathParams["courseDayId"],
  data: SubmitFeedbackMutationRequest,
  config: Partial<RequestConfig<SubmitFeedbackMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    SubmitFeedbackMutationResponse,
    ResponseErrorConfig<
      SubmitFeedback400 | SubmitFeedback404 | SubmitFeedback409
    >,
    SubmitFeedbackMutationRequest
  >({
    method: "POST",
    url: `/api/course-progress/days/${courseDayId}/feedback`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function submitFeedbackMutationOptions(
  config: Partial<RequestConfig<SubmitFeedbackMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = submitFeedbackMutationKey();
  return mutationOptions<
    SubmitFeedbackMutationResponse,
    ResponseErrorConfig<
      SubmitFeedback400 | SubmitFeedback404 | SubmitFeedback409
    >,
    {
      courseDayId: SubmitFeedbackPathParams["courseDayId"];
      data: SubmitFeedbackMutationRequest;
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ courseDayId, data }) => {
      return submitFeedback(courseDayId, data, config);
    },
  });
}

/**
 * @description Allows users to provide detailed feedback after completing all exercises in a course day. Users can only submit feedback for the day they just completed (currentDayNumber - 1). Once they move to the next day, the feedback window for the previous day closes. Feedback includes completion percentage, effort level, pain tracking, hardest exercise, and general notes.
 * @summary Submit feedback for a completed day
 * {@link /api/course-progress/days/:courseDayId/feedback}
 */
export function useSubmitFeedback<TContext>(
  options: {
    mutation?: UseMutationOptions<
      SubmitFeedbackMutationResponse,
      ResponseErrorConfig<
        SubmitFeedback400 | SubmitFeedback404 | SubmitFeedback409
      >,
      {
        courseDayId: SubmitFeedbackPathParams["courseDayId"];
        data: SubmitFeedbackMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<SubmitFeedbackMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? submitFeedbackMutationKey();

  const baseOptions = submitFeedbackMutationOptions(
    config,
  ) as UseMutationOptions<
    SubmitFeedbackMutationResponse,
    ResponseErrorConfig<
      SubmitFeedback400 | SubmitFeedback404 | SubmitFeedback409
    >,
    {
      courseDayId: SubmitFeedbackPathParams["courseDayId"];
      data: SubmitFeedbackMutationRequest;
    },
    TContext
  >;

  return useMutation<
    SubmitFeedbackMutationResponse,
    ResponseErrorConfig<
      SubmitFeedback400 | SubmitFeedback404 | SubmitFeedback409
    >,
    {
      courseDayId: SubmitFeedbackPathParams["courseDayId"];
      data: SubmitFeedbackMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    SubmitFeedbackMutationResponse,
    ResponseErrorConfig<
      SubmitFeedback400 | SubmitFeedback404 | SubmitFeedback409
    >,
    {
      courseDayId: SubmitFeedbackPathParams["courseDayId"];
      data: SubmitFeedbackMutationRequest;
    },
    TContext
  >;
}
