/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetAllCategoriesQueryResponse } from "../../types/exerciseCategoriesController/GetAllCategories.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetAllCategoriesUrl() {
  const res = { method: 'GET', url: `/api/exercise-categories` as const }  
  return res
}

/**
 * @description Retrieve all exercise categories
 * @summary Get all categories
 * {@link /api/exercise-categories}
 */
export async function getAllCategories(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetAllCategoriesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetAllCategoriesUrl().url.toString(), ... requestConfig })  
  return res.data
}