/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetPendingPurchasesQueryResponse } from "../../types/subscriptionControllerController/GetPendingPurchases.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getPendingPurchasesSuspenseQueryKey = () => [{ url: '/api/subscriptions/pending-purchases' }] as const

export type GetPendingPurchasesSuspenseQueryKey = ReturnType<typeof getPendingPurchasesSuspenseQueryKey>

/**
 * {@link /api/subscriptions/pending-purchases}
 */
export async function getPendingPurchasesSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetPendingPurchasesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/subscriptions/pending-purchases`, ... requestConfig })  
  return res.data
}

export function getPendingPurchasesSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getPendingPurchasesSuspenseQueryKey()
  return queryOptions<GetPendingPurchasesQueryResponse, ResponseErrorConfig<Error>, GetPendingPurchasesQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getPendingPurchasesSuspense(config)
   },
  })
}

/**
 * {@link /api/subscriptions/pending-purchases}
 */
export function useGetPendingPurchasesSuspense<TData = GetPendingPurchasesQueryResponse, TQueryKey extends QueryKey = GetPendingPurchasesSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetPendingPurchasesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPendingPurchasesSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getPendingPurchasesSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}