/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetMySubscriptionsQueryResponse } from "../../types/subscriptionControllerController/GetMySubscriptions.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMySubscriptionsSuspenseQueryKey = () => [{ url: '/api/subscriptions/my-subscriptions' }] as const

export type GetMySubscriptionsSuspenseQueryKey = ReturnType<typeof getMySubscriptionsSuspenseQueryKey>

/**
 * {@link /api/subscriptions/my-subscriptions}
 */
export async function getMySubscriptionsSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMySubscriptionsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/subscriptions/my-subscriptions`, ... requestConfig })  
  return res.data
}

export function getMySubscriptionsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMySubscriptionsSuspenseQueryKey()
  return queryOptions<GetMySubscriptionsQueryResponse, ResponseErrorConfig<Error>, GetMySubscriptionsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMySubscriptionsSuspense(config)
   },
  })
}

/**
 * {@link /api/subscriptions/my-subscriptions}
 */
export function useGetMySubscriptionsSuspense<TData = GetMySubscriptionsQueryResponse, TQueryKey extends QueryKey = GetMySubscriptionsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetMySubscriptionsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMySubscriptionsSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getMySubscriptionsSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}