/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ExerciseResponse } from "../ExerciseResponse.ts";

export type GetExercisesByGroupPathParams = {
    /**
     * @description Group ID
     * @type integer, int64
    */
    groupId: number;
};

/**
 * @description OK
*/
export type GetExercisesByGroup200 = ExerciseResponse[];

export type GetExercisesByGroupQueryResponse = GetExercisesByGroup200;

export type GetExercisesByGroupQuery = {
    Response: GetExercisesByGroup200;
    PathParams: GetExercisesByGroupPathParams;
    Errors: any;
};