/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { CreateCouponMutationRequest, CreateCouponMutationResponse } from "../../types/CreateCoupon.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getCreateCouponUrl() {
  const res = { method: 'POST', url: `/api/coupons` as const }  
  return res
}

/**
 * @description Create a new discount coupon code
 * @summary Create coupon (Admin only)
 * {@link /api/coupons}
 */
export async function createCoupon(data: CreateCouponMutationRequest, config: Partial<RequestConfig<CreateCouponMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateCouponMutationResponse, ResponseErrorConfig<Error>, CreateCouponMutationRequest>({ method : "POST", url : getCreateCouponUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}