/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetNewsByTitleQueryResponse, GetNewsByTitleQueryParams } from "../../types/newsController/GetNewsByTitle.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getNewsByTitleQueryKey = (params: GetNewsByTitleQueryParams) => [{ url: '/api/news/search' }, ...(params ? [params] : [])] as const

export type GetNewsByTitleQueryKey = ReturnType<typeof getNewsByTitleQueryKey>

/**
 * @description Search for news articles by title (case-insensitive, partial match). Example: ?title=health&page=0&size=10&sort=createdAt,desc
 * @summary Search news by title
 * {@link /api/news/search}
 */
export async function getNewsByTitle(params: GetNewsByTitleQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetNewsByTitleQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/news/search`, params, ... requestConfig })  
  return res.data
}

export function getNewsByTitleQueryOptions(params: GetNewsByTitleQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getNewsByTitleQueryKey(params)
  return queryOptions<GetNewsByTitleQueryResponse, ResponseErrorConfig<Error>, GetNewsByTitleQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getNewsByTitle(params, config)
   },
  })
}

/**
 * @description Search for news articles by title (case-insensitive, partial match). Example: ?title=health&page=0&size=10&sort=createdAt,desc
 * @summary Search news by title
 * {@link /api/news/search}
 */
export function useGetNewsByTitle<TData = GetNewsByTitleQueryResponse, TQueryData = GetNewsByTitleQueryResponse, TQueryKey extends QueryKey = GetNewsByTitleQueryKey>(params: GetNewsByTitleQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetNewsByTitleQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getNewsByTitleQueryKey(params)

  const query = useQuery({
   ...getNewsByTitleQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}