/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetAllNewsQueryResponse, GetAllNewsQueryParams } from "../../types/newsController/GetAllNews.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getAllNewsSuspenseQueryKey = (params: GetAllNewsQueryParams) => [{ url: '/api/news' }, ...(params ? [params] : [])] as const

export type GetAllNewsSuspenseQueryKey = ReturnType<typeof getAllNewsSuspenseQueryKey>

/**
 * @description Retrieve a paginated list of news with optional status and category filtering. Use query params: ?status=PUBLISHED&category=HEALTH_TIPS&page=0&size=10&sort=createdAt,desc
 * @summary Get paginated news with filtering
 * {@link /api/news}
 */
export async function getAllNewsSuspense(params: GetAllNewsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetAllNewsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/news`, params, ... requestConfig })  
  return res.data
}

export function getAllNewsSuspenseQueryOptions(params: GetAllNewsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getAllNewsSuspenseQueryKey(params)
  return queryOptions<GetAllNewsQueryResponse, ResponseErrorConfig<Error>, GetAllNewsQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getAllNewsSuspense(params, config)
   },
  })
}

/**
 * @description Retrieve a paginated list of news with optional status and category filtering. Use query params: ?status=PUBLISHED&category=HEALTH_TIPS&page=0&size=10&sort=createdAt,desc
 * @summary Get paginated news with filtering
 * {@link /api/news}
 */
export function useGetAllNewsSuspense<TData = GetAllNewsQueryResponse, TQueryKey extends QueryKey = GetAllNewsSuspenseQueryKey>(params: GetAllNewsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetAllNewsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getAllNewsSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getAllNewsSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}