/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetAllNewsQueryResponse, GetAllNewsQueryParams } from "../../types/newsController/GetAllNews.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAllNewsQueryKey = (params: GetAllNewsQueryParams) => [{ url: '/api/news' }, ...(params ? [params] : [])] as const

export type GetAllNewsQueryKey = ReturnType<typeof getAllNewsQueryKey>

/**
 * @description Retrieve a paginated list of news with optional status and category filtering. Use query params: ?status=PUBLISHED&category=HEALTH_TIPS&page=0&size=10&sort=createdAt,desc
 * @summary Get paginated news with filtering
 * {@link /api/news}
 */
export async function getAllNews(params: GetAllNewsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetAllNewsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/news`, params, ... requestConfig })  
  return res.data
}

export function getAllNewsQueryOptions(params: GetAllNewsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getAllNewsQueryKey(params)
  return queryOptions<GetAllNewsQueryResponse, ResponseErrorConfig<Error>, GetAllNewsQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getAllNews(params, config)
   },
  })
}

/**
 * @description Retrieve a paginated list of news with optional status and category filtering. Use query params: ?status=PUBLISHED&category=HEALTH_TIPS&page=0&size=10&sort=createdAt,desc
 * @summary Get paginated news with filtering
 * {@link /api/news}
 */
export function useGetAllNews<TData = GetAllNewsQueryResponse, TQueryData = GetAllNewsQueryResponse, TQueryKey extends QueryKey = GetAllNewsQueryKey>(params: GetAllNewsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetAllNewsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getAllNewsQueryKey(params)

  const query = useQuery({
   ...getAllNewsQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}