/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetAllUsersQueryResponse } from "../../types/userManagementController/GetAllUsers.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getAllUsersSuspenseQueryKey = () => [{ url: '/api/users' }] as const

export type GetAllUsersSuspenseQueryKey = ReturnType<typeof getAllUsersSuspenseQueryKey>

/**
 * @description Retrieve a list of all users in the system (Admin/Doctor only)
 * @summary Get all users
 * {@link /api/users}
 */
export async function getAllUsersSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetAllUsersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/users`, ... requestConfig })  
  return res.data
}

export function getAllUsersSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getAllUsersSuspenseQueryKey()
  return queryOptions<GetAllUsersQueryResponse, ResponseErrorConfig<Error>, GetAllUsersQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getAllUsersSuspense(config)
   },
  })
}

/**
 * @description Retrieve a list of all users in the system (Admin/Doctor only)
 * @summary Get all users
 * {@link /api/users}
 */
export function useGetAllUsersSuspense<TData = GetAllUsersQueryResponse, TQueryKey extends QueryKey = GetAllUsersSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetAllUsersQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getAllUsersSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getAllUsersSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}