/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { ApproveCourseRequestMutationRequest, ApproveCourseRequestMutationResponse, ApproveCourseRequestPathParams } from "../../types/doctorController/ApproveCourseRequest.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const approveCourseRequestMutationKey = () => [{ url: '/api/doctors/course-requests/:id/approve' }] as const

export type ApproveCourseRequestMutationKey = ReturnType<typeof approveCourseRequestMutationKey>

/**
 * @description Approve a course assignment request from a trainer, creating the course and assigning it to the patient
 * @summary Approve trainer's course request
 * {@link /api/doctors/course-requests/:id/approve}
 */
export async function approveCourseRequest(id: ApproveCourseRequestPathParams["id"], data?: ApproveCourseRequestMutationRequest, config: Partial<RequestConfig<ApproveCourseRequestMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<ApproveCourseRequestMutationResponse, ResponseErrorConfig<Error>, ApproveCourseRequestMutationRequest>({ method : "POST", url : `/api/doctors/course-requests/${id}/approve`, data : requestData, ... requestConfig })  
  return res.data
}

export function approveCourseRequestMutationOptions(config: Partial<RequestConfig<ApproveCourseRequestMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = approveCourseRequestMutationKey()
  return mutationOptions<ApproveCourseRequestMutationResponse, ResponseErrorConfig<Error>, {id: ApproveCourseRequestPathParams["id"], data?: ApproveCourseRequestMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return approveCourseRequest(id, data, config)
    },
  })
}

/**
 * @description Approve a course assignment request from a trainer, creating the course and assigning it to the patient
 * @summary Approve trainer's course request
 * {@link /api/doctors/course-requests/:id/approve}
 */
export function useApproveCourseRequest<TContext>(options: 
{
  mutation?: UseMutationOptions<ApproveCourseRequestMutationResponse, ResponseErrorConfig<Error>, {id: ApproveCourseRequestPathParams["id"], data?: ApproveCourseRequestMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<ApproveCourseRequestMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? approveCourseRequestMutationKey()

  const baseOptions = approveCourseRequestMutationOptions(config) as UseMutationOptions<ApproveCourseRequestMutationResponse, ResponseErrorConfig<Error>, {id: ApproveCourseRequestPathParams["id"], data?: ApproveCourseRequestMutationRequest}, TContext>

  return useMutation<ApproveCourseRequestMutationResponse, ResponseErrorConfig<Error>, {id: ApproveCourseRequestPathParams["id"], data?: ApproveCourseRequestMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ApproveCourseRequestMutationResponse, ResponseErrorConfig<Error>, {id: ApproveCourseRequestPathParams["id"], data?: ApproveCourseRequestMutationRequest}, TContext>
}