/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { AssignCourseToPatientMutationRequest, AssignCourseToPatientMutationResponse, AssignCourseToPatientPathParams } from "../../types/doctorController/AssignCourseToPatient.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const assignCourseToPatientMutationKey = () => [{ url: '/api/doctors/patients/:userId/courses' }] as const

export type AssignCourseToPatientMutationKey = ReturnType<typeof assignCourseToPatientMutationKey>

/**
 * @description Assign a course to my patient
 * @summary Assign course to patient
 * {@link /api/doctors/patients/:userId/courses}
 */
export async function assignCourseToPatient(userId: AssignCourseToPatientPathParams["userId"], data: AssignCourseToPatientMutationRequest, config: Partial<RequestConfig<AssignCourseToPatientMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AssignCourseToPatientMutationResponse, ResponseErrorConfig<Error>, AssignCourseToPatientMutationRequest>({ method : "POST", url : `/api/doctors/patients/${userId}/courses`, data : requestData, ... requestConfig })  
  return res.data
}

export function assignCourseToPatientMutationOptions(config: Partial<RequestConfig<AssignCourseToPatientMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = assignCourseToPatientMutationKey()
  return mutationOptions<AssignCourseToPatientMutationResponse, ResponseErrorConfig<Error>, {userId: AssignCourseToPatientPathParams["userId"], data: AssignCourseToPatientMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ userId, data }) => {
      return assignCourseToPatient(userId, data, config)
    },
  })
}

/**
 * @description Assign a course to my patient
 * @summary Assign course to patient
 * {@link /api/doctors/patients/:userId/courses}
 */
export function useAssignCourseToPatient<TContext>(options: 
{
  mutation?: UseMutationOptions<AssignCourseToPatientMutationResponse, ResponseErrorConfig<Error>, {userId: AssignCourseToPatientPathParams["userId"], data: AssignCourseToPatientMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AssignCourseToPatientMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? assignCourseToPatientMutationKey()

  const baseOptions = assignCourseToPatientMutationOptions(config) as UseMutationOptions<AssignCourseToPatientMutationResponse, ResponseErrorConfig<Error>, {userId: AssignCourseToPatientPathParams["userId"], data: AssignCourseToPatientMutationRequest}, TContext>

  return useMutation<AssignCourseToPatientMutationResponse, ResponseErrorConfig<Error>, {userId: AssignCourseToPatientPathParams["userId"], data: AssignCourseToPatientMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AssignCourseToPatientMutationResponse, ResponseErrorConfig<Error>, {userId: AssignCourseToPatientPathParams["userId"], data: AssignCourseToPatientMutationRequest}, TContext>
}