/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetMyCourseAssignmentsQueryResponse, GetMyCourseAssignmentsQueryParams } from "../../types/doctorController/GetMyCourseAssignments.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMyCourseAssignmentsSuspenseQueryKey = (params: GetMyCourseAssignmentsQueryParams) => [{ url: '/api/doctors/my-course-assignments' }, ...(params ? [params] : [])] as const

export type GetMyCourseAssignmentsSuspenseQueryKey = ReturnType<typeof getMyCourseAssignmentsSuspenseQueryKey>

/**
 * @description Get all courses I assigned to all my patients
 * @summary Get all my course assignments
 * {@link /api/doctors/my-course-assignments}
 */
export async function getMyCourseAssignmentsSuspense(params: GetMyCourseAssignmentsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMyCourseAssignmentsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/doctors/my-course-assignments`, params, ... requestConfig })  
  return res.data
}

export function getMyCourseAssignmentsSuspenseQueryOptions(params: GetMyCourseAssignmentsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMyCourseAssignmentsSuspenseQueryKey(params)
  return queryOptions<GetMyCourseAssignmentsQueryResponse, ResponseErrorConfig<Error>, GetMyCourseAssignmentsQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMyCourseAssignmentsSuspense(params, config)
   },
  })
}

/**
 * @description Get all courses I assigned to all my patients
 * @summary Get all my course assignments
 * {@link /api/doctors/my-course-assignments}
 */
export function useGetMyCourseAssignmentsSuspense<TData = GetMyCourseAssignmentsQueryResponse, TQueryKey extends QueryKey = GetMyCourseAssignmentsSuspenseQueryKey>(params: GetMyCourseAssignmentsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetMyCourseAssignmentsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMyCourseAssignmentsSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getMyCourseAssignmentsSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}