/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetMyAssignedCoursesQueryResponse, GetMyAssignedCoursesQueryParams } from "../../types/doctorController/GetMyAssignedCourses.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMyAssignedCoursesSuspenseQueryKey = (params: GetMyAssignedCoursesQueryParams) => [{ url: '/api/doctors/my-course-assignments' }, ...(params ? [params] : [])] as const

export type GetMyAssignedCoursesSuspenseQueryKey = ReturnType<typeof getMyAssignedCoursesSuspenseQueryKey>

/**
 * @description Get all courses I assigned to all my patients
 * @summary Get all my course assignments
 * {@link /api/doctors/my-course-assignments}
 */
export async function getMyAssignedCoursesSuspense(params: GetMyAssignedCoursesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMyAssignedCoursesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/doctors/my-course-assignments`, params, ... requestConfig })  
  return res.data
}

export function getMyAssignedCoursesSuspenseQueryOptions(params: GetMyAssignedCoursesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMyAssignedCoursesSuspenseQueryKey(params)
  return queryOptions<GetMyAssignedCoursesQueryResponse, ResponseErrorConfig<Error>, GetMyAssignedCoursesQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMyAssignedCoursesSuspense(params, config)
   },
  })
}

/**
 * @description Get all courses I assigned to all my patients
 * @summary Get all my course assignments
 * {@link /api/doctors/my-course-assignments}
 */
export function useGetMyAssignedCoursesSuspense<TData = GetMyAssignedCoursesQueryResponse, TQueryKey extends QueryKey = GetMyAssignedCoursesSuspenseQueryKey>(params: GetMyAssignedCoursesQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetMyAssignedCoursesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMyAssignedCoursesSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getMyAssignedCoursesSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}