/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetMyTrainersQueryResponse, GetMyTrainersQueryParams } from "../../types/doctorController/GetMyTrainers.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getMyTrainersQueryKey = (params: GetMyTrainersQueryParams) => [{ url: '/api/doctors/my-trainers' }, ...(params ? [params] : [])] as const

export type GetMyTrainersQueryKey = ReturnType<typeof getMyTrainersQueryKey>

/**
 * @description Get all trainers assigned to the authenticated doctor
 * @summary Get my trainers
 * {@link /api/doctors/my-trainers}
 */
export async function getMyTrainers(params: GetMyTrainersQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMyTrainersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/doctors/my-trainers`, params, ... requestConfig })  
  return res.data
}

export function getMyTrainersQueryOptions(params: GetMyTrainersQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMyTrainersQueryKey(params)
  return queryOptions<GetMyTrainersQueryResponse, ResponseErrorConfig<Error>, GetMyTrainersQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMyTrainers(params, config)
   },
  })
}

/**
 * @description Get all trainers assigned to the authenticated doctor
 * @summary Get my trainers
 * {@link /api/doctors/my-trainers}
 */
export function useGetMyTrainers<TData = GetMyTrainersQueryResponse, TQueryData = GetMyTrainersQueryResponse, TQueryKey extends QueryKey = GetMyTrainersQueryKey>(params: GetMyTrainersQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetMyTrainersQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMyTrainersQueryKey(params)

  const query = useQuery({
   ...getMyTrainersQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}