/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetMyAssignedCoursesQueryResponse, GetMyAssignedCoursesQueryParams } from "../../types/doctorController/GetMyAssignedCourses.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getMyAssignedCoursesQueryKey = (params: GetMyAssignedCoursesQueryParams) => [{ url: '/api/doctors/my-course-assignments' }, ...(params ? [params] : [])] as const

export type GetMyAssignedCoursesQueryKey = ReturnType<typeof getMyAssignedCoursesQueryKey>

/**
 * @description Get all courses I assigned to all my patients
 * @summary Get all my course assignments
 * {@link /api/doctors/my-course-assignments}
 */
export async function getMyAssignedCourses(params: GetMyAssignedCoursesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMyAssignedCoursesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/doctors/my-course-assignments`, params, ... requestConfig })  
  return res.data
}

export function getMyAssignedCoursesQueryOptions(params: GetMyAssignedCoursesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMyAssignedCoursesQueryKey(params)
  return queryOptions<GetMyAssignedCoursesQueryResponse, ResponseErrorConfig<Error>, GetMyAssignedCoursesQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMyAssignedCourses(params, config)
   },
  })
}

/**
 * @description Get all courses I assigned to all my patients
 * @summary Get all my course assignments
 * {@link /api/doctors/my-course-assignments}
 */
export function useGetMyAssignedCourses<TData = GetMyAssignedCoursesQueryResponse, TQueryData = GetMyAssignedCoursesQueryResponse, TQueryKey extends QueryKey = GetMyAssignedCoursesQueryKey>(params: GetMyAssignedCoursesQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetMyAssignedCoursesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMyAssignedCoursesQueryKey(params)

  const query = useQuery({
   ...getMyAssignedCoursesQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}