/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/api-client'
import type {
  SearchMyPatientsQueryResponse,
  SearchMyPatientsQueryParams,
} from '../../types/doctorController/SearchMyPatients.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/api-client'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const searchMyPatientsQueryKey = (
  params?: SearchMyPatientsQueryParams
) =>
  [
    { url: '/api/doctors/patients/search' },
    ...(params ? [params] : []),
  ] as const

export type SearchMyPatientsQueryKey = ReturnType<
  typeof searchMyPatientsQueryKey
>

/**
 * @description Returns up to 5 closest matching patients assigned to the authenticated doctor, based on name or phone number. Used for the patient search filter dropdown.
 * @summary Search my patients (top 5 results)
 * {@link /api/doctors/patients/search}
 */
export async function searchMyPatients(
  params?: SearchMyPatientsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    SearchMyPatientsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: `/api/doctors/patients/search`,
    params,
    ...requestConfig,
  })
  return res.data
}

export function searchMyPatientsQueryOptions(
  params?: SearchMyPatientsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = searchMyPatientsQueryKey(params)
  return queryOptions<
    SearchMyPatientsQueryResponse,
    ResponseErrorConfig<Error>,
    SearchMyPatientsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return searchMyPatients(params, config)
    },
  })
}

/**
 * @description Returns up to 5 closest matching patients assigned to the authenticated doctor, based on name or phone number. Used for the patient search filter dropdown.
 * @summary Search my patients (top 5 results)
 * {@link /api/doctors/patients/search}
 */
export function useSearchMyPatients<
  TData = SearchMyPatientsQueryResponse,
  TQueryData = SearchMyPatientsQueryResponse,
  TQueryKey extends QueryKey = SearchMyPatientsQueryKey,
>(
  params?: SearchMyPatientsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        SearchMyPatientsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? searchMyPatientsQueryKey(params)

  const query = useQuery(
    {
      ...searchMyPatientsQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
