/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { pageableSchema } from '../pageableSchema.ts'
import { pagedModelAuditLogResponseSchema } from '../pagedModelAuditLogResponseSchema.ts'
import { z } from 'zod/v4'

export const getAuditLogsQueryParamsSchema = z.object({
  entityType: z.optional(z.string()),
  action: z.optional(z.string()),
  actorId: z.optional(z.coerce.number().int()),
  from: z.optional(z.string().datetime()),
  to: z.optional(z.string().datetime()),
  get pageable() {
    return pageableSchema
  },
})

/**
 * @description OK
 */
export const getAuditLogs200Schema = z.lazy(
  () => pagedModelAuditLogResponseSchema
)

export const getAuditLogsQueryResponseSchema = z.lazy(
  () => getAuditLogs200Schema
)
