/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { pageableSchema } from '../pageableSchema.ts'
import { pagedModelAuditLogResponseSchema } from '../pagedModelAuditLogResponseSchema.ts'
import { z } from 'zod/v4'

export const getEntityAuditHistoryPathParamsSchema = z.object({
  entityType: z.string(),
  entityId: z.coerce.number().int(),
})

export const getEntityAuditHistoryQueryParamsSchema = z.object({
  get pageable() {
    return pageableSchema
  },
})

/**
 * @description OK
 */
export const getEntityAuditHistory200Schema = z.lazy(
  () => pagedModelAuditLogResponseSchema
)

export const getEntityAuditHistoryQueryResponseSchema = z.lazy(
  () => getEntityAuditHistory200Schema
)
