/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { trainerResponseSchema } from "../trainerResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const getMyTrainers200Schema = z.array(
  z.lazy(() => trainerResponseSchema),
);

export const getMyTrainersQueryResponseSchema = z.lazy(
  () => getMyTrainers200Schema,
);
