/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { myPatientResponseSchema } from "../myPatientResponseSchema.ts";
import { z } from "zod/v4";

export const searchMyPatientsQueryParamsSchema = z.object({
    "query": z.optional(z.string().describe("Search by fullName or phoneNumber (case-insensitive)"))
    }).optional()

/**
 * @description OK
 */
export const searchMyPatients200Schema = z.array(z.lazy(() => myPatientResponseSchema))

export const searchMyPatientsQueryResponseSchema = z.lazy(() => searchMyPatients200Schema)