export type { GetAppointmentStatsQueryKey } from "./useGetAppointmentStats.ts";
export type { GetAppointmentStatsSuspenseQueryKey } from "./useGetAppointmentStatsSuspense.ts";
export type { GetCourseStatsQueryKey } from "./useGetCourseStats.ts";
export type { GetCourseStatsSuspenseQueryKey } from "./useGetCourseStatsSuspense.ts";
export type { GetDoctorStatsQueryKey } from "./useGetDoctorStats.ts";
export type { GetDoctorStatsSuspenseQueryKey } from "./useGetDoctorStatsSuspense.ts";
export type { GetLowEffortPatientsQueryKey } from "./useGetLowEffortPatients.ts";
export type { GetLowEffortPatientsSuspenseQueryKey } from "./useGetLowEffortPatientsSuspense.ts";
export type { GetOverviewQueryKey } from "./useGetOverview.ts";
export type { GetOverviewSuspenseQueryKey } from "./useGetOverviewSuspense.ts";
export type { GetPainReportsQueryKey } from "./useGetPainReports.ts";
export type { GetPainReportsSuspenseQueryKey } from "./useGetPainReportsSuspense.ts";
export type { GetRegistrationsQueryKey } from "./useGetRegistrations.ts";
export type { GetRegistrationsSuspenseQueryKey } from "./useGetRegistrationsSuspense.ts";
export type { GetRevenueQueryKey } from "./useGetRevenue.ts";
export type { GetRevenueSuspenseQueryKey } from "./useGetRevenueSuspense.ts";
export type { GetTopSpendersQueryKey } from "./useGetTopSpenders.ts";
export type { GetTopSpendersSuspenseQueryKey } from "./useGetTopSpendersSuspense.ts";
export { getAppointmentStatsQueryKey } from "./useGetAppointmentStats.ts";
export { getAppointmentStats } from "./useGetAppointmentStats.ts";
export { getAppointmentStatsQueryOptions } from "./useGetAppointmentStats.ts";
export { useGetAppointmentStats } from "./useGetAppointmentStats.ts";
export { getAppointmentStatsSuspenseQueryKey } from "./useGetAppointmentStatsSuspense.ts";
export { getAppointmentStatsSuspense } from "./useGetAppointmentStatsSuspense.ts";
export { getAppointmentStatsSuspenseQueryOptions } from "./useGetAppointmentStatsSuspense.ts";
export { useGetAppointmentStatsSuspense } from "./useGetAppointmentStatsSuspense.ts";
export { getCourseStatsQueryKey } from "./useGetCourseStats.ts";
export { getCourseStats } from "./useGetCourseStats.ts";
export { getCourseStatsQueryOptions } from "./useGetCourseStats.ts";
export { useGetCourseStats } from "./useGetCourseStats.ts";
export { getCourseStatsSuspenseQueryKey } from "./useGetCourseStatsSuspense.ts";
export { getCourseStatsSuspense } from "./useGetCourseStatsSuspense.ts";
export { getCourseStatsSuspenseQueryOptions } from "./useGetCourseStatsSuspense.ts";
export { useGetCourseStatsSuspense } from "./useGetCourseStatsSuspense.ts";
export { getDoctorStatsQueryKey } from "./useGetDoctorStats.ts";
export { getDoctorStats } from "./useGetDoctorStats.ts";
export { getDoctorStatsQueryOptions } from "./useGetDoctorStats.ts";
export { useGetDoctorStats } from "./useGetDoctorStats.ts";
export { getDoctorStatsSuspenseQueryKey } from "./useGetDoctorStatsSuspense.ts";
export { getDoctorStatsSuspense } from "./useGetDoctorStatsSuspense.ts";
export { getDoctorStatsSuspenseQueryOptions } from "./useGetDoctorStatsSuspense.ts";
export { useGetDoctorStatsSuspense } from "./useGetDoctorStatsSuspense.ts";
export { getLowEffortPatientsQueryKey } from "./useGetLowEffortPatients.ts";
export { getLowEffortPatients } from "./useGetLowEffortPatients.ts";
export { getLowEffortPatientsQueryOptions } from "./useGetLowEffortPatients.ts";
export { useGetLowEffortPatients } from "./useGetLowEffortPatients.ts";
export { getLowEffortPatientsSuspenseQueryKey } from "./useGetLowEffortPatientsSuspense.ts";
export { getLowEffortPatientsSuspense } from "./useGetLowEffortPatientsSuspense.ts";
export { getLowEffortPatientsSuspenseQueryOptions } from "./useGetLowEffortPatientsSuspense.ts";
export { useGetLowEffortPatientsSuspense } from "./useGetLowEffortPatientsSuspense.ts";
export { getOverviewQueryKey } from "./useGetOverview.ts";
export { getOverview } from "./useGetOverview.ts";
export { getOverviewQueryOptions } from "./useGetOverview.ts";
export { useGetOverview } from "./useGetOverview.ts";
export { getOverviewSuspenseQueryKey } from "./useGetOverviewSuspense.ts";
export { getOverviewSuspense } from "./useGetOverviewSuspense.ts";
export { getOverviewSuspenseQueryOptions } from "./useGetOverviewSuspense.ts";
export { useGetOverviewSuspense } from "./useGetOverviewSuspense.ts";
export { getPainReportsQueryKey } from "./useGetPainReports.ts";
export { getPainReports } from "./useGetPainReports.ts";
export { getPainReportsQueryOptions } from "./useGetPainReports.ts";
export { useGetPainReports } from "./useGetPainReports.ts";
export { getPainReportsSuspenseQueryKey } from "./useGetPainReportsSuspense.ts";
export { getPainReportsSuspense } from "./useGetPainReportsSuspense.ts";
export { getPainReportsSuspenseQueryOptions } from "./useGetPainReportsSuspense.ts";
export { useGetPainReportsSuspense } from "./useGetPainReportsSuspense.ts";
export { getRegistrationsQueryKey } from "./useGetRegistrations.ts";
export { getRegistrations } from "./useGetRegistrations.ts";
export { getRegistrationsQueryOptions } from "./useGetRegistrations.ts";
export { useGetRegistrations } from "./useGetRegistrations.ts";
export { getRegistrationsSuspenseQueryKey } from "./useGetRegistrationsSuspense.ts";
export { getRegistrationsSuspense } from "./useGetRegistrationsSuspense.ts";
export { getRegistrationsSuspenseQueryOptions } from "./useGetRegistrationsSuspense.ts";
export { useGetRegistrationsSuspense } from "./useGetRegistrationsSuspense.ts";
export { getRevenueQueryKey } from "./useGetRevenue.ts";
export { getRevenue } from "./useGetRevenue.ts";
export { getRevenueQueryOptions } from "./useGetRevenue.ts";
export { useGetRevenue } from "./useGetRevenue.ts";
export { getRevenueSuspenseQueryKey } from "./useGetRevenueSuspense.ts";
export { getRevenueSuspense } from "./useGetRevenueSuspense.ts";
export { getRevenueSuspenseQueryOptions } from "./useGetRevenueSuspense.ts";
export { useGetRevenueSuspense } from "./useGetRevenueSuspense.ts";
export { getTopSpendersQueryKey } from "./useGetTopSpenders.ts";
export { getTopSpenders } from "./useGetTopSpenders.ts";
export { getTopSpendersQueryOptions } from "./useGetTopSpenders.ts";
export { useGetTopSpenders } from "./useGetTopSpenders.ts";
export { getTopSpendersSuspenseQueryKey } from "./useGetTopSpendersSuspense.ts";
export { getTopSpendersSuspense } from "./useGetTopSpendersSuspense.ts";
export { getTopSpendersSuspenseQueryOptions } from "./useGetTopSpendersSuspense.ts";
export { useGetTopSpendersSuspense } from "./useGetTopSpendersSuspense.ts";
