/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetLowEffortPatientsQueryResponse, GetLowEffortPatientsQueryParams } from "../../types/reportsController/GetLowEffortPatients.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getLowEffortPatientsQueryKey = (params?: GetLowEffortPatientsQueryParams) => [{ url: '/api/reports/low-effort-patients' }, ...(params ? [params] : [])] as const

export type GetLowEffortPatientsQueryKey = ReturnType<typeof getLowEffortPatientsQueryKey>

/**
 * @description Returns patients whose average effort percentage across all logged course days is below a configurable threshold. Sorted by effort ascending (lowest effort first). Useful for flagging disengaged patients for doctor review.
 * @summary Get low effort patients
 * {@link /api/reports/low-effort-patients}
 */
export async function getLowEffortPatients(params?: GetLowEffortPatientsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetLowEffortPatientsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/reports/low-effort-patients`, params, ... requestConfig })  
  return res.data
}

export function getLowEffortPatientsQueryOptions(params?: GetLowEffortPatientsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getLowEffortPatientsQueryKey(params)
  return queryOptions<GetLowEffortPatientsQueryResponse, ResponseErrorConfig<Error>, GetLowEffortPatientsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getLowEffortPatients(params, config)
   },
  })
}

/**
 * @description Returns patients whose average effort percentage across all logged course days is below a configurable threshold. Sorted by effort ascending (lowest effort first). Useful for flagging disengaged patients for doctor review.
 * @summary Get low effort patients
 * {@link /api/reports/low-effort-patients}
 */
export function useGetLowEffortPatients<TData = GetLowEffortPatientsQueryResponse, TQueryData = GetLowEffortPatientsQueryResponse, TQueryKey extends QueryKey = GetLowEffortPatientsQueryKey>(params?: GetLowEffortPatientsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetLowEffortPatientsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getLowEffortPatientsQueryKey(params)

  const query = useQuery({
   ...getLowEffortPatientsQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}