/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type { GetDoctorStatsQueryResponse } from "../../types/reportsController/GetDoctorStats.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getDoctorStatsQueryKey = () =>
  [{ url: "/api/reports/doctor-stats" }] as const;

export type GetDoctorStatsQueryKey = ReturnType<typeof getDoctorStatsQueryKey>;

/**
 * @description Returns per-doctor statistics including patient count, courses assigned, courses completed by their patients, completion rate, appointments this month, and dispute count. Sorted by patient caseload (highest first).
 * @summary Get doctor performance statistics
 * {@link /api/reports/doctor-stats}
 */
export async function getDoctorStats(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetDoctorStatsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/api/reports/doctor-stats`, ...requestConfig });
  return res.data;
}

export function getDoctorStatsQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getDoctorStatsQueryKey();
  return queryOptions<
    GetDoctorStatsQueryResponse,
    ResponseErrorConfig<Error>,
    GetDoctorStatsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getDoctorStats(config);
    },
  });
}

/**
 * @description Returns per-doctor statistics including patient count, courses assigned, courses completed by their patients, completion rate, appointments this month, and dispute count. Sorted by patient caseload (highest first).
 * @summary Get doctor performance statistics
 * {@link /api/reports/doctor-stats}
 */
export function useGetDoctorStats<
  TData = GetDoctorStatsQueryResponse,
  TQueryData = GetDoctorStatsQueryResponse,
  TQueryKey extends QueryKey = GetDoctorStatsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetDoctorStatsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getDoctorStatsQueryKey();

  const query = useQuery(
    {
      ...getDoctorStatsQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
