/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetCourseStatsQueryResponse } from "../../types/reportsController/GetCourseStats.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getCourseStatsSuspenseQueryKey = () => [{ url: '/api/reports/course-stats' }] as const

export type GetCourseStatsSuspenseQueryKey = ReturnType<typeof getCourseStatsSuspenseQueryKey>

/**
 * @description Returns per-course statistics including total assigned, started, in-progress, completed, dropped, and completion rate. Results are sorted by completion rate (highest first).
 * @summary Get course engagement statistics
 * {@link /api/reports/course-stats}
 */
export async function getCourseStatsSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCourseStatsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/reports/course-stats`, ... requestConfig })  
  return res.data
}

export function getCourseStatsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getCourseStatsSuspenseQueryKey()
  return queryOptions<GetCourseStatsQueryResponse, ResponseErrorConfig<Error>, GetCourseStatsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getCourseStatsSuspense(config)
   },
  })
}

/**
 * @description Returns per-course statistics including total assigned, started, in-progress, completed, dropped, and completion rate. Results are sorted by completion rate (highest first).
 * @summary Get course engagement statistics
 * {@link /api/reports/course-stats}
 */
export function useGetCourseStatsSuspense<TData = GetCourseStatsQueryResponse, TQueryKey extends QueryKey = GetCourseStatsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetCourseStatsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getCourseStatsSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getCourseStatsSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}