export type { CompleteCourseMutationKey } from "./useCompleteCourse.ts";
export type { CompleteExerciseMutationKey } from "./useCompleteExercise.ts";
export type { GetCompletedCoursesQueryKey } from "./useGetCompletedCourses.ts";
export type { GetCompletedCoursesSuspenseQueryKey } from "./useGetCompletedCoursesSuspense.ts";
export type { GetCourseProgressHistoryQueryKey } from "./useGetCourseProgressHistory.ts";
export type { GetCourseProgressHistorySuspenseQueryKey } from "./useGetCourseProgressHistorySuspense.ts";
export type { GetCurrentProgressQueryKey } from "./useGetCurrentProgress.ts";
export type { GetCurrentProgressSuspenseQueryKey } from "./useGetCurrentProgressSuspense.ts";
export type { GetDayContentQueryKey } from "./useGetDayContent.ts";
export type { GetDayContentSuspenseQueryKey } from "./useGetDayContentSuspense.ts";
export type { GetMyAssignedCourses1QueryKey } from "./useGetMyAssignedCourses1.ts";
export type { GetMyAssignedCourses1SuspenseQueryKey } from "./useGetMyAssignedCourses1Suspense.ts";
export type { GetProgressHistoryQueryKey } from "./useGetProgressHistory.ts";
export type { GetProgressHistorySuspenseQueryKey } from "./useGetProgressHistorySuspense.ts";
export type { StartCourseMutationKey } from "./useStartCourse.ts";
export { completeCourseMutationKey } from "./useCompleteCourse.ts";
export { completeCourse } from "./useCompleteCourse.ts";
export { completeCourseMutationOptions } from "./useCompleteCourse.ts";
export { useCompleteCourse } from "./useCompleteCourse.ts";
export { completeExerciseMutationKey } from "./useCompleteExercise.ts";
export { completeExercise } from "./useCompleteExercise.ts";
export { completeExerciseMutationOptions } from "./useCompleteExercise.ts";
export { useCompleteExercise } from "./useCompleteExercise.ts";
export { getCompletedCoursesQueryKey } from "./useGetCompletedCourses.ts";
export { getCompletedCourses } from "./useGetCompletedCourses.ts";
export { getCompletedCoursesQueryOptions } from "./useGetCompletedCourses.ts";
export { useGetCompletedCourses } from "./useGetCompletedCourses.ts";
export { getCompletedCoursesSuspenseQueryKey } from "./useGetCompletedCoursesSuspense.ts";
export { getCompletedCoursesSuspense } from "./useGetCompletedCoursesSuspense.ts";
export { getCompletedCoursesSuspenseQueryOptions } from "./useGetCompletedCoursesSuspense.ts";
export { useGetCompletedCoursesSuspense } from "./useGetCompletedCoursesSuspense.ts";
export { getCourseProgressHistoryQueryKey } from "./useGetCourseProgressHistory.ts";
export { getCourseProgressHistory } from "./useGetCourseProgressHistory.ts";
export { getCourseProgressHistoryQueryOptions } from "./useGetCourseProgressHistory.ts";
export { useGetCourseProgressHistory } from "./useGetCourseProgressHistory.ts";
export { getCourseProgressHistorySuspenseQueryKey } from "./useGetCourseProgressHistorySuspense.ts";
export { getCourseProgressHistorySuspense } from "./useGetCourseProgressHistorySuspense.ts";
export { getCourseProgressHistorySuspenseQueryOptions } from "./useGetCourseProgressHistorySuspense.ts";
export { useGetCourseProgressHistorySuspense } from "./useGetCourseProgressHistorySuspense.ts";
export { getCurrentProgressQueryKey } from "./useGetCurrentProgress.ts";
export { getCurrentProgress } from "./useGetCurrentProgress.ts";
export { getCurrentProgressQueryOptions } from "./useGetCurrentProgress.ts";
export { useGetCurrentProgress } from "./useGetCurrentProgress.ts";
export { getCurrentProgressSuspenseQueryKey } from "./useGetCurrentProgressSuspense.ts";
export { getCurrentProgressSuspense } from "./useGetCurrentProgressSuspense.ts";
export { getCurrentProgressSuspenseQueryOptions } from "./useGetCurrentProgressSuspense.ts";
export { useGetCurrentProgressSuspense } from "./useGetCurrentProgressSuspense.ts";
export { getDayContentQueryKey } from "./useGetDayContent.ts";
export { getDayContent } from "./useGetDayContent.ts";
export { getDayContentQueryOptions } from "./useGetDayContent.ts";
export { useGetDayContent } from "./useGetDayContent.ts";
export { getDayContentSuspenseQueryKey } from "./useGetDayContentSuspense.ts";
export { getDayContentSuspense } from "./useGetDayContentSuspense.ts";
export { getDayContentSuspenseQueryOptions } from "./useGetDayContentSuspense.ts";
export { useGetDayContentSuspense } from "./useGetDayContentSuspense.ts";
export { getMyAssignedCourses1QueryKey } from "./useGetMyAssignedCourses1.ts";
export { getMyAssignedCourses1 } from "./useGetMyAssignedCourses1.ts";
export { getMyAssignedCourses1QueryOptions } from "./useGetMyAssignedCourses1.ts";
export { useGetMyAssignedCourses1 } from "./useGetMyAssignedCourses1.ts";
export { getMyAssignedCourses1SuspenseQueryKey } from "./useGetMyAssignedCourses1Suspense.ts";
export { getMyAssignedCourses1Suspense } from "./useGetMyAssignedCourses1Suspense.ts";
export { getMyAssignedCourses1SuspenseQueryOptions } from "./useGetMyAssignedCourses1Suspense.ts";
export { useGetMyAssignedCourses1Suspense } from "./useGetMyAssignedCourses1Suspense.ts";
export { getProgressHistoryQueryKey } from "./useGetProgressHistory.ts";
export { getProgressHistory } from "./useGetProgressHistory.ts";
export { getProgressHistoryQueryOptions } from "./useGetProgressHistory.ts";
export { useGetProgressHistory } from "./useGetProgressHistory.ts";
export { getProgressHistorySuspenseQueryKey } from "./useGetProgressHistorySuspense.ts";
export { getProgressHistorySuspense } from "./useGetProgressHistorySuspense.ts";
export { getProgressHistorySuspenseQueryOptions } from "./useGetProgressHistorySuspense.ts";
export { useGetProgressHistorySuspense } from "./useGetProgressHistorySuspense.ts";
export { startCourseMutationKey } from "./useStartCourse.ts";
export { startCourse } from "./useStartCourse.ts";
export { startCourseMutationOptions } from "./useStartCourse.ts";
export { useStartCourse } from "./useStartCourse.ts";
