/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetProgressHistoryQueryResponse } from "../../types/courseProgressController/GetProgressHistory.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getProgressHistoryQueryKey = () => [{ url: '/api/course-progress/history' }] as const

export type GetProgressHistoryQueryKey = ReturnType<typeof getProgressHistoryQueryKey>

/**
 * @description Retrieve all progress records (active and archived) for the authenticated user. Includes completed courses, restarted attempts, and expired subscriptions. Useful for viewing complete rehabilitation journey.
 * @summary Get my complete progress history
 * {@link /api/course-progress/history}
 */
export async function getProgressHistory(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetProgressHistoryQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/course-progress/history`, ... requestConfig })  
  return res.data
}

export function getProgressHistoryQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getProgressHistoryQueryKey()
  return queryOptions<GetProgressHistoryQueryResponse, ResponseErrorConfig<Error>, GetProgressHistoryQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getProgressHistory(config)
   },
  })
}

/**
 * @description Retrieve all progress records (active and archived) for the authenticated user. Includes completed courses, restarted attempts, and expired subscriptions. Useful for viewing complete rehabilitation journey.
 * @summary Get my complete progress history
 * {@link /api/course-progress/history}
 */
export function useGetProgressHistory<TData = GetProgressHistoryQueryResponse, TQueryData = GetProgressHistoryQueryResponse, TQueryKey extends QueryKey = GetProgressHistoryQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetProgressHistoryQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getProgressHistoryQueryKey()

  const query = useQuery({
   ...getProgressHistoryQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}