/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetProgressHistoryQueryResponse } from "../../types/courseProgressController/GetProgressHistory.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getProgressHistorySuspenseQueryKey = () => [{ url: '/api/course-progress/history' }] as const

export type GetProgressHistorySuspenseQueryKey = ReturnType<typeof getProgressHistorySuspenseQueryKey>

/**
 * @description Retrieve all progress records (active and archived) for the authenticated user. Includes completed courses, restarted attempts, and expired subscriptions. Useful for viewing complete rehabilitation journey.
 * @summary Get my complete progress history
 * {@link /api/course-progress/history}
 */
export async function getProgressHistorySuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetProgressHistoryQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/course-progress/history`, ... requestConfig })  
  return res.data
}

export function getProgressHistorySuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getProgressHistorySuspenseQueryKey()
  return queryOptions<GetProgressHistoryQueryResponse, ResponseErrorConfig<Error>, GetProgressHistoryQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getProgressHistorySuspense(config)
   },
  })
}

/**
 * @description Retrieve all progress records (active and archived) for the authenticated user. Includes completed courses, restarted attempts, and expired subscriptions. Useful for viewing complete rehabilitation journey.
 * @summary Get my complete progress history
 * {@link /api/course-progress/history}
 */
export function useGetProgressHistorySuspense<TData = GetProgressHistoryQueryResponse, TQueryKey extends QueryKey = GetProgressHistorySuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetProgressHistoryQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getProgressHistorySuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getProgressHistorySuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}