/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type { GetCompletedCoursesQueryResponse } from "../../types/courseProgressController/GetCompletedCourses.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getCompletedCoursesSuspenseQueryKey = () =>
  [{ url: "/api/course-progress/completed" }] as const;

export type GetCompletedCoursesSuspenseQueryKey = ReturnType<
  typeof getCompletedCoursesSuspenseQueryKey
>;

/**
 * @description Retrieve all successfully completed courses (archived with COMPLETED reason). Excludes courses that were restarted or expired. Shows user's achievements and finished rehabilitation programs.
 * @summary Get my completed courses
 * {@link /api/course-progress/completed}
 */
export async function getCompletedCoursesSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetCompletedCoursesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/api/course-progress/completed`, ...requestConfig });
  return res.data;
}

export function getCompletedCoursesSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getCompletedCoursesSuspenseQueryKey();
  return queryOptions<
    GetCompletedCoursesQueryResponse,
    ResponseErrorConfig<Error>,
    GetCompletedCoursesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getCompletedCoursesSuspense(config);
    },
  });
}

/**
 * @description Retrieve all successfully completed courses (archived with COMPLETED reason). Excludes courses that were restarted or expired. Shows user's achievements and finished rehabilitation programs.
 * @summary Get my completed courses
 * {@link /api/course-progress/completed}
 */
export function useGetCompletedCoursesSuspense<
  TData = GetCompletedCoursesQueryResponse,
  TQueryKey extends QueryKey = GetCompletedCoursesSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetCompletedCoursesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getCompletedCoursesSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getCompletedCoursesSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
