/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type RemoveTrainerFromDoctorPathParams = {
  /**
   * @description Doctor ID
   * @type integer, int64
   */
  doctorId: number;
  /**
   * @description Trainer ID
   * @type integer, int64
   */
  trainerId: number;
};

/**
 * @description OK
 */
export type RemoveTrainerFromDoctor200 = any;

export type RemoveTrainerFromDoctorMutationResponse =
  RemoveTrainerFromDoctor200;

export type RemoveTrainerFromDoctorMutation = {
  Response: RemoveTrainerFromDoctor200;
  PathParams: RemoveTrainerFromDoctorPathParams;
  Errors: any;
};
