/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { DeleteFileMutationResponse, DeleteFileQueryParams } from "../../types/DeleteFile.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getDeleteFileUrl() {
  const res = { method: 'DELETE', url: `/api/files/delete` as const }  
  return res
}

/**
 * @description Delete a file from S3 by URL (Admin and Doctor only)
 * @summary Delete file from S3
 * {@link /api/files/delete}
 */
export async function deleteFile(params: DeleteFileQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteFileMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteFileUrl().url.toString(), params, ... requestConfig })  
  return res.data
}