/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GeneratePresignedAccessUrlQueryResponse, GeneratePresignedAccessUrlPathParams, GeneratePresignedAccessUrlQueryParams } from "../../types/GeneratePresignedAccessUrl.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGeneratePresignedAccessUrlUrl(folder: GeneratePresignedAccessUrlPathParams["folder"], fileName: GeneratePresignedAccessUrlPathParams["fileName"]) {
  const res = { method: 'GET', url: `/api/files/presigned-url/${folder}/${fileName}` as const }  
  return res
}

/**
 * @description Generate a presigned URL for temporary file access
 * @summary Generate presigned access URL
 * {@link /api/files/presigned-url/:folder/:fileName}
 */
export async function generatePresignedAccessUrl(folder: GeneratePresignedAccessUrlPathParams["folder"], fileName: GeneratePresignedAccessUrlPathParams["fileName"], params?: GeneratePresignedAccessUrlQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GeneratePresignedAccessUrlQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGeneratePresignedAccessUrlUrl(folder, fileName).url.toString(), params, ... requestConfig })  
  return res.data
}