/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { UploadVideoMutationRequest, UploadVideoMutationResponse } from "../../types/UploadVideo.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getUploadVideoUrl() {
  const res = { method: 'POST', url: `/api/files/upload/video` as const }  
  return res
}

/**
 * @description Upload a video file for exercises (Admin and Doctor only)
 * @summary Upload exercise video
 * {@link /api/files/upload/video}
 */
export async function uploadVideo(data: UploadVideoMutationRequest, config: Partial<RequestConfig<UploadVideoMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  const formData = new FormData()
  if (requestData) {
   Object.keys(requestData).forEach((key) => {
     const value = requestData[key as keyof typeof requestData];
     if (typeof value === 'string' || (value as unknown) instanceof Blob) {
       formData.append(key, value as unknown as string | Blob);
     } else {
       formData.append(key, JSON.stringify(value));
     }
   })
  }  
  const res = await request<UploadVideoMutationResponse, ResponseErrorConfig<Error>, UploadVideoMutationRequest>({ method : "POST", url : getUploadVideoUrl().url.toString(), data : formData, ... requestConfig, headers : { 'Content-Type': 'multipart/form-data', ...requestConfig.headers } })  
  return res.data
}