/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { deleteFileRequestSchema } from "../deleteFileRequestSchema.ts";
import { fileDeleteResponseSchema } from "../fileDeleteResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const deleteFile200Schema = z.lazy(() => fileDeleteResponseSchema)

export const deleteFileMutationRequestSchema = z.lazy(() => deleteFileRequestSchema)

export const deleteFileMutationResponseSchema = z.lazy(() => deleteFile200Schema)