/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pageable } from "../Pageable.ts";
import type { PagedModel } from "../PagedModel.ts";

export type GetDisputedAppointmentsQueryParams = {
    /**
     * @type object
    */
    pageable: Pageable;
};

/**
 * @description OK
*/
export type GetDisputedAppointments200 = PagedModel;

export type GetDisputedAppointmentsQueryResponse = GetDisputedAppointments200;

export type GetDisputedAppointmentsQuery = {
    Response: GetDisputedAppointments200;
    QueryParams: GetDisputedAppointmentsQueryParams;
    Errors: any;
};