/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pageable } from '../Pageable.ts'
import type { PagedModelAppointmentResponse } from '../PagedModelAppointmentResponse.ts'

export type GetPatientAppointmentsForStaffPathParams = {
  /**
   * @type integer, int64
   */
  userId: number
}

export type GetPatientAppointmentsForStaffQueryParams = {
  /**
   * @type object
   */
  pageable: Pageable
}

/**
 * @description OK
 */
export type GetPatientAppointmentsForStaff200 = PagedModelAppointmentResponse

export type GetPatientAppointmentsForStaffQueryResponse =
  GetPatientAppointmentsForStaff200

export type GetPatientAppointmentsForStaffQuery = {
  Response: GetPatientAppointmentsForStaff200
  PathParams: GetPatientAppointmentsForStaffPathParams
  QueryParams: GetPatientAppointmentsForStaffQueryParams
  Errors: any
}
