/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PublicDoctorResponse } from "../PublicDoctorResponse.ts";

/**
 * @description OK
*/
export type GetPublicDoctors200 = PublicDoctorResponse[];

export type GetPublicDoctorsQueryResponse = GetPublicDoctors200;

export type GetPublicDoctorsQuery = {
    Response: GetPublicDoctors200;
    Errors: any;
};