/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { CreateBannerMutationRequest, CreateBannerMutationResponse } from "../../types/CreateBanner.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getCreateBannerUrl() {
  const res = { method: 'POST', url: `/api/carousel-banners` as const }  
  return res
}

/**
 * @description Create a new carousel banner. Upload image first via /api/files/upload/image and use the returned URL. Banners are created as active by default.
 * @summary Create new banner (Admin only)
 * {@link /api/carousel-banners}
 */
export async function createBanner(data: CreateBannerMutationRequest, config: Partial<RequestConfig<CreateBannerMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateBannerMutationResponse, ResponseErrorConfig<Error>, CreateBannerMutationRequest>({ method : "POST", url : getCreateBannerUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}