/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { DeleteBannerMutationResponse, DeleteBannerPathParams } from "../../types/DeleteBanner.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getDeleteBannerUrl(id: DeleteBannerPathParams["id"]) {
  const res = { method: 'DELETE', url: `/api/carousel-banners/${id}` as const }  
  return res
}

/**
 * @description Permanently delete a carousel banner
 * @summary Delete banner (Admin only)
 * {@link /api/carousel-banners/:id}
 */
export async function deleteBanner(id: DeleteBannerPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteBannerMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteBannerUrl(id).url.toString(), ... requestConfig })  
  return res.data
}