/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { CreateCategoryMutationRequest, CreateCategoryMutationResponse } from "../../types/CreateCategory.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getCreateCategoryUrl() {
  const res = { method: 'POST', url: `/api/categories` as const }  
  return res
}

/**
 * @description Create a new category (Admin only)
 * @summary Create new category
 * {@link /api/categories}
 */
export async function createCategory(data: CreateCategoryMutationRequest, config: Partial<RequestConfig<CreateCategoryMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateCategoryMutationResponse, ResponseErrorConfig<Error>, CreateCategoryMutationRequest>({ method : "POST", url : getCreateCategoryUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}