/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { DeleteCategoryMutationResponse, DeleteCategoryPathParams } from "../../types/DeleteCategory.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getDeleteCategoryUrl(id: DeleteCategoryPathParams["id"]) {
  const res = { method: 'DELETE', url: `/api/categories/${id}` as const }  
  return res
}

/**
 * @description Soft delete a category (Admin only)
 * @summary Delete category
 * {@link /api/categories/:id}
 */
export async function deleteCategory(id: DeleteCategoryPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteCategoryMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteCategoryUrl(id).url.toString(), ... requestConfig })  
  return res.data
}