/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetCategoryByIdQueryResponse, GetCategoryByIdPathParams } from "../../types/GetCategoryById.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetCategoryByIdUrl(id: GetCategoryByIdPathParams["id"]) {
  const res = { method: 'GET', url: `/api/categories/${id}` as const }  
  return res
}

/**
 * @description Retrieve a specific category by its ID
 * @summary Get category by ID
 * {@link /api/categories/:id}
 */
export async function getCategoryById(id: GetCategoryByIdPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCategoryByIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetCategoryByIdUrl(id).url.toString(), ... requestConfig })  
  return res.data
}