import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image as Photo,
  Laptop,
  LayoutDashboard,
  Loader2,
  LogIn,
  ShoppingBag,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  Sun,
  Trash2 as Trash,
  User,
  UserCircle2 as UserCircle,
  UserCog as UserEdit,
  UserX,
  X,
} from 'lucide-react';

export type Icon = React.ComponentType<React.SVGProps<SVGSVGElement>>;

export const Icons = {
  dashboard: LayoutDashboard,
  logo: Command,
  login: LogIn,
  close: X,
  product: ShoppingBag,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX,
  post: FileText,
  page: File,
  userPen: UserEdit,
  user2: UserCircle,
  media: Photo,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  check: Check
};