/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DiscountResponse } from "../DiscountResponse.ts";

export type GetByIdPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type GetById200 = DiscountResponse;

export type GetByIdQueryResponse = GetById200;

export type GetByIdQuery = {
    Response: GetById200;
    PathParams: GetByIdPathParams;
    Errors: any;
};