/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { CheckPackageAccessQueryResponse, CheckPackageAccessPathParams } from "../../types/exercisePackagesController/CheckPackageAccess.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const checkPackageAccessSuspenseQueryKey = (id: CheckPackageAccessPathParams["id"]) => [{ url: '/api/exercise-packages/:id/check-access', params: {id:id} }] as const

export type CheckPackageAccessSuspenseQueryKey = ReturnType<typeof checkPackageAccessSuspenseQueryKey>

/**
 * @description Check if the authenticated user has an active subscription to a specific exercise package
 * @summary Check package access
 * {@link /api/exercise-packages/:id/check-access}
 */
export async function checkPackageAccessSuspense(id: CheckPackageAccessPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<CheckPackageAccessQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/exercise-packages/${id}/check-access`, ... requestConfig })  
  return res.data
}

export function checkPackageAccessSuspenseQueryOptions(id: CheckPackageAccessPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = checkPackageAccessSuspenseQueryKey(id)
  return queryOptions<CheckPackageAccessQueryResponse, ResponseErrorConfig<Error>, CheckPackageAccessQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return checkPackageAccessSuspense(id, config)
   },
  })
}

/**
 * @description Check if the authenticated user has an active subscription to a specific exercise package
 * @summary Check package access
 * {@link /api/exercise-packages/:id/check-access}
 */
export function useCheckPackageAccessSuspense<TData = CheckPackageAccessQueryResponse, TQueryKey extends QueryKey = CheckPackageAccessSuspenseQueryKey>(id: CheckPackageAccessPathParams["id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<CheckPackageAccessQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? checkPackageAccessSuspenseQueryKey(id)

  const query = useSuspenseQuery({
   ...checkPackageAccessSuspenseQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}