/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { CheckPackageAccessQueryResponse, CheckPackageAccessPathParams } from "../../types/exercisePackagesController/CheckPackageAccess.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const checkPackageAccessQueryKey = (id: CheckPackageAccessPathParams["id"]) => [{ url: '/api/exercise-packages/:id/check-access', params: {id:id} }] as const

export type CheckPackageAccessQueryKey = ReturnType<typeof checkPackageAccessQueryKey>

/**
 * @description Check if the authenticated user has an active subscription to a specific exercise package
 * @summary Check package access
 * {@link /api/exercise-packages/:id/check-access}
 */
export async function checkPackageAccess(id: CheckPackageAccessPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<CheckPackageAccessQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/exercise-packages/${id}/check-access`, ... requestConfig })  
  return res.data
}

export function checkPackageAccessQueryOptions(id: CheckPackageAccessPathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = checkPackageAccessQueryKey(id)
  return queryOptions<CheckPackageAccessQueryResponse, ResponseErrorConfig<Error>, CheckPackageAccessQueryResponse, typeof queryKey>({
   enabled: !!(id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return checkPackageAccess(id, config)
   },
  })
}

/**
 * @description Check if the authenticated user has an active subscription to a specific exercise package
 * @summary Check package access
 * {@link /api/exercise-packages/:id/check-access}
 */
export function useCheckPackageAccess<TData = CheckPackageAccessQueryResponse, TQueryData = CheckPackageAccessQueryResponse, TQueryKey extends QueryKey = CheckPackageAccessQueryKey>(id: CheckPackageAccessPathParams["id"], options: 
{
  query?: Partial<QueryObserverOptions<CheckPackageAccessQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? checkPackageAccessQueryKey(id)

  const query = useQuery({
   ...checkPackageAccessQueryOptions(id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}