/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetRandomAvailablePackagesQueryResponse, GetRandomAvailablePackagesQueryParams } from "../../types/exercisePackagesController/GetRandomAvailablePackages.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getRandomAvailablePackagesQueryKey = (params?: GetRandomAvailablePackagesQueryParams) => [{ url: '/api/exercise-packages/me/available/random' }, ...(params ? [params] : [])] as const

export type GetRandomAvailablePackagesQueryKey = ReturnType<typeof getRandomAvailablePackagesQueryKey>

/**
 * @description Retrieve a random selection of exercise packages that the current user has not purchased yet. Returns a non-paginated list of randomly ordered packages. Useful for discovery/recommendation on the home screen. Default size is 5, maximum is 20.
 * @summary Get random available exercise packages for current user
 * {@link /api/exercise-packages/me/available/random}
 */
export async function getRandomAvailablePackages(params?: GetRandomAvailablePackagesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetRandomAvailablePackagesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/exercise-packages/me/available/random`, params, ... requestConfig })  
  return res.data
}

export function getRandomAvailablePackagesQueryOptions(params?: GetRandomAvailablePackagesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getRandomAvailablePackagesQueryKey(params)
  return queryOptions<GetRandomAvailablePackagesQueryResponse, ResponseErrorConfig<Error>, GetRandomAvailablePackagesQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getRandomAvailablePackages(params, config)
   },
  })
}

/**
 * @description Retrieve a random selection of exercise packages that the current user has not purchased yet. Returns a non-paginated list of randomly ordered packages. Useful for discovery/recommendation on the home screen. Default size is 5, maximum is 20.
 * @summary Get random available exercise packages for current user
 * {@link /api/exercise-packages/me/available/random}
 */
export function useGetRandomAvailablePackages<TData = GetRandomAvailablePackagesQueryResponse, TQueryData = GetRandomAvailablePackagesQueryResponse, TQueryKey extends QueryKey = GetRandomAvailablePackagesQueryKey>(params?: GetRandomAvailablePackagesQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetRandomAvailablePackagesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getRandomAvailablePackagesQueryKey(params)

  const query = useQuery({
   ...getRandomAvailablePackagesQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}