/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RemovePatientFromDoctorPathParams = {
    /**
     * @description Doctor ID
     * @type integer, int64
    */
    doctorId: number;
    /**
     * @description User ID
     * @type integer, int64
    */
    userId: number;
};

/**
 * @description OK
*/
export type RemovePatientFromDoctor200 = any;

export type RemovePatientFromDoctorMutationResponse = RemovePatientFromDoctor200;

export type RemovePatientFromDoctorMutation = {
    Response: RemovePatientFromDoctor200;
    PathParams: RemovePatientFromDoctorPathParams;
    Errors: any;
};