/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { PurchasePackageMutationRequest, PurchasePackageMutationResponse } from "../../types/subscriptionsController/PurchasePackage.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const purchasePackageMutationKey = () => [{ url: '/api/subscriptions/package/purchase' }] as const

export type PurchasePackageMutationKey = ReturnType<typeof purchasePackageMutationKey>

/**
 * @description Purchase a subscription for an exercise package (monthly or yearly)
 * @summary Purchase package subscription
 * {@link /api/subscriptions/package/purchase}
 */
export async function purchasePackage(data: PurchasePackageMutationRequest, config: Partial<RequestConfig<PurchasePackageMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<PurchasePackageMutationResponse, ResponseErrorConfig<Error>, PurchasePackageMutationRequest>({ method : "POST", url : `/api/subscriptions/package/purchase`, data : requestData, ... requestConfig })  
  return res.data
}

export function purchasePackageMutationOptions(config: Partial<RequestConfig<PurchasePackageMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = purchasePackageMutationKey()
  return mutationOptions<PurchasePackageMutationResponse, ResponseErrorConfig<Error>, {data: PurchasePackageMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return purchasePackage(data, config)
    },
  })
}

/**
 * @description Purchase a subscription for an exercise package (monthly or yearly)
 * @summary Purchase package subscription
 * {@link /api/subscriptions/package/purchase}
 */
export function usePurchasePackage<TContext>(options: 
{
  mutation?: UseMutationOptions<PurchasePackageMutationResponse, ResponseErrorConfig<Error>, {data: PurchasePackageMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PurchasePackageMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? purchasePackageMutationKey()

  const baseOptions = purchasePackageMutationOptions(config) as UseMutationOptions<PurchasePackageMutationResponse, ResponseErrorConfig<Error>, {data: PurchasePackageMutationRequest}, TContext>

  return useMutation<PurchasePackageMutationResponse, ResponseErrorConfig<Error>, {data: PurchasePackageMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<PurchasePackageMutationResponse, ResponseErrorConfig<Error>, {data: PurchasePackageMutationRequest}, TContext>
}