/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetGlobalDiscountQueryResponse } from "../../types/GetGlobalDiscount.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetGlobalDiscountUrl() {
  const res = { method: 'GET', url: `/api/admin/global-discount` as const }  
  return res
}

/**
 * @description Retrieve current global discount configuration
 * @summary Get global discount settings
 * {@link /api/admin/global-discount}
 */
export async function getGlobalDiscount(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetGlobalDiscountQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetGlobalDiscountUrl().url.toString(), ... requestConfig })  
  return res.data
}