/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type AvailableSlotResponse = {
    /**
     * @type string | undefined, date
    */
    date?: string;
    /**
     * @type string | undefined
    */
    startTime?: string;
    /**
     * @type string | undefined
    */
    endTime?: string;
    /**
     * @type boolean | undefined
    */
    available?: boolean;
};