/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CourseProgressResponse = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type integer | undefined, int64
    */
    courseId?: number;
    /**
     * @type string | undefined
    */
    courseTitle?: string;
    /**
     * @type integer | undefined, int32
    */
    currentDayNumber?: number;
    /**
     * @type integer | undefined, int32
    */
    totalDays?: number;
    /**
     * @type boolean | undefined
    */
    isCompleted?: boolean;
    /**
     * @type string | undefined, date-time
    */
    startedAt?: string;
    /**
     * @type string | undefined, date-time
    */
    completedAt?: string;
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
};