/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CourseMetadataDto = {
  /**
   * @type integer | undefined, int64
   */
  id?: number
  /**
   * @type object | undefined
   */
  title?: {
    [key: string]: string
  }
  /**
   * @type integer | undefined, int32
   */
  totalDays?: number
}
