/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CourseDayDetailDto } from './CourseDayDetailDto.ts'

export type CourseWithDaysResponse = {
  /**
   * @type integer | undefined, int64
   */
  id?: number
  /**
   * @type integer | undefined, int64
   */
  userId?: number
  /**
   * @type object | undefined
   */
  title?: {
    [key: string]: string
  }
  /**
   * @type object | undefined
   */
  description?: {
    [key: string]: string
  }
  /**
   * @type integer | undefined, int32
   */
  durationDays?: number
  /**
   * @type boolean | undefined
   */
  isActive?: boolean
  /**
   * @type array | undefined
   */
  days?: CourseDayDetailDto[]
  /**
   * @type string | undefined, date-time
   */
  createdAt?: string
  /**
   * @type string | undefined, date-time
   */
  updatedAt?: string
}
