/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CourseDayDto } from './CourseDayDto.ts'

export type CreateCustomCourseRequest = {
  /**
   * @minLength 1
   * @type string
   */
  title: string
  /**
   * @minLength 1
   * @type string
   */
  description: string
  /**
   * @type string | undefined
   */
  patientProblems?: string
  /**
   * @type string | undefined
   */
  objective?: string
  /**
   * @type integer, int32
   */
  durationDays: number
  /**
   * @type string | undefined
   */
  notes?: string
  /**
   * @type boolean | undefined
   */
  isFree?: boolean
  /**
   * @type integer | undefined, int64
   */
  assigningDoctorId?: number
  /**
   * @type array
   */
  courseDays: CourseDayDto[]
}
