/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateStartupPopupRequest = {
  /**
   * @type object | undefined
   */
  title?: {
    [key: string]: string
  }
  /**
   * @minLength 0
   * @maxLength 500
   * @type string
   */
  imageUrl: string
  /**
   * @type boolean | undefined
   */
  active?: boolean
}
