/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateGroupRequest = {
  /**
   * @type object | undefined
   */
  name?: {
    [key: string]: string
  }
  /**
   * @type object | undefined
   */
  description?: {
    [key: string]: string
  }
}
