/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateGroupRequest = {
    /**
     * @minLength 1
     * @type string
    */
    name: string;
    /**
     * @type string | undefined
    */
    description?: string;
};