/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CreateExercisePackageRequest = {
    /**
     * @type string
    */
    title: string;
    /**
     * @type string
    */
    description: string;
    /**
     * @type string | undefined
    */
    imageUrl?: string;
    /**
     * @type array
    */
    exerciseIds: number[];
};