/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DoctorStatsResponse = {
  /**
   * @type integer | undefined, int64
   */
  doctorId?: number;
  /**
   * @type string | undefined
   */
  doctorName?: string;
  /**
   * @type string | undefined
   */
  specialization?: string;
  /**
   * @type integer | undefined, int64
   */
  patientCount?: number;
  /**
   * @type integer | undefined, int64
   */
  coursesAssigned?: number;
  /**
   * @type integer | undefined, int64
   */
  coursesCompleted?: number;
  /**
   * @type number | undefined, double
   */
  completionRate?: number;
  /**
   * @type integer | undefined, int64
   */
  appointmentsThisMonth?: number;
  /**
   * @type integer | undefined, int64
   */
  disputeCount?: number;
};
