/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type ExercisePackageResponse = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    title?: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type string | undefined
    */
    imageUrl?: string;
    /**
     * @type integer | undefined, int32
    */
    exerciseCount?: number;
    /**
     * @type integer | undefined, int64
    */
    monthlyPrice?: number;
    /**
     * @type integer | undefined, int64
    */
    yearlyPrice?: number;
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
    /**
     * @type string | undefined, date-time
    */
    updatedAt?: string;
};