/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CategoryResponse } from './CategoryResponse.ts'
import type { SubscriptionInfo } from './SubscriptionInfo.ts'

export type ExercisePackageWithSubscriptionResponse = {
  /**
   * @type integer | undefined, int64
   */
  id?: number
  /**
   * @type object | undefined
   */
  title?: {
    [key: string]: string
  }
  /**
   * @type object | undefined
   */
  description?: {
    [key: string]: string
  }
  /**
   * @type string | undefined
   */
  imageUrl?: string
  /**
   * @type array | undefined
   */
  categories?: CategoryResponse[]
  /**
   * @type integer | undefined, int32
   */
  exerciseCount?: number
  /**
   * @type object | undefined
   */
  subscription?: SubscriptionInfo
  /**
   * @type integer | undefined, int64
   */
  oneMonthPrice?: number
  /**
   * @type integer | undefined, int64
   */
  threeMonthPrice?: number
  /**
   * @type integer | undefined, int64
   */
  twelveMonthPrice?: number
  /**
   * @type string | undefined, date-time
   */
  createdAt?: string
  /**
   * @type string | undefined, date-time
   */
  updatedAt?: string
}
