/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ExerciseResponse } from "./ExerciseResponse.ts";

export type ExercisePackageResponse = {
  /**
   * @type integer | undefined, int64
   */
  id?: number;
  /**
   * @type string | undefined
   */
  title?: string;
  /**
   * @type string | undefined
   */
  description?: string;
  /**
   * @type string | undefined
   */
  imageUrl?: string;
  /**
   * @type array | undefined
   */
  exercises?: ExerciseResponse[];
  /**
   * @type string | undefined, date-time
   */
  createdAt?: string;
  /**
   * @type string | undefined, date-time
   */
  updatedAt?: string;
};
