/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type FeedbackResponse = {
  /**
   * @type integer | undefined, int64
   */
  id?: number;
  /**
   * @type integer | undefined, int64
   */
  courseDayId?: number;
  /**
   * @type integer | undefined, int32
   */
  dayNumber?: number;
  /**
   * @type integer | undefined, int32
   */
  completionPercentage?: number;
  /**
   * @type integer | undefined, int32
   */
  effortPercentage?: number;
  /**
   * @type boolean | undefined
   */
  hasPain?: boolean;
  /**
   * @type string | undefined
   */
  painDetails?: string;
  /**
   * @type string | undefined
   */
  hardestExercise?: string;
  /**
   * @type string | undefined
   */
  hardestExerciseReason?: string;
  /**
   * @type string | undefined
   */
  generalNotes?: string;
  /**
   * @type string | undefined, date-time
   */
  createdAt?: string;
};
