/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LocalTime = {
  /**
   * @type integer | undefined, int32
   */
  hour?: number;
  /**
   * @type integer | undefined, int32
   */
  minute?: number;
  /**
   * @type integer | undefined, int32
   */
  second?: number;
  /**
   * @type integer | undefined, int32
   */
  nano?: number;
};
