/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type OtpResponse = {
  /**
   * @type string | undefined
   */
  message?: string;
  /**
   * @type string | undefined
   */
  otpId?: string;
  /**
   * @type integer | undefined, int64
   */
  expiresInSeconds?: number;
};
