/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RevenueDataPointResponse } from "./RevenueDataPointResponse.ts";

export type OverviewResponse = {
    /**
     * @type integer | undefined, int64
    */
    totalPatients?: number;
    /**
     * @type integer | undefined, int64
    */
    newPatientsThisMonth?: number;
    /**
     * @type integer | undefined, int64
    */
    totalRevenueThisMonth?: number;
    /**
     * @type integer | undefined, int64
    */
    activeSubscriptions?: number;
    /**
     * @type integer | undefined, int64
    */
    activeStandardPackageUsers?: number;
    /**
     * @type integer | undefined, int64
    */
    activePersonalizedCourseUsers?: number;
    /**
     * @type integer | undefined, int64
    */
    appointmentsToday?: number;
    /**
     * @type number | undefined, double
    */
    overallCompletionRate?: number;
    /**
     * @type array | undefined
    */
    last30DaysRevenueTrend?: RevenueDataPointResponse[];
    /**
     * @type object | undefined
    */
    appointmentStatusToday?: {
        [key: string]: number;
    };
};