/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ExercisePackageResponse } from "./ExercisePackageResponse.ts";
import type { PageMetadata } from "./PageMetadata.ts";

export type PagedModelExercisePackageResponse = {
    /**
     * @type array | undefined
    */
    content?: ExercisePackageResponse[];
    /**
     * @type object | undefined
    */
    page?: PageMetadata;
};