/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PageMetadata } from './PageMetadata.ts'
import type { StaffResponse } from './StaffResponse.ts'

export type PagedModelStaffResponse = {
  /**
   * @type array | undefined
   */
  content?: StaffResponse[]
  /**
   * @type object | undefined
   */
  page?: PageMetadata
}
