/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { MyAssignedCourseResponse } from "./MyAssignedCourseResponse.ts";
import type { PageableObject } from "./PageableObject.ts";
import type { SortObject } from "./SortObject.ts";

export type PageMyAssignedCourseResponse = {
    /**
     * @type array | undefined
    */
    content?: MyAssignedCourseResponse[];
    /**
     * @type object | undefined
    */
    pageable?: PageableObject;
    /**
     * @type integer | undefined, int64
    */
    totalElements?: number;
    /**
     * @type integer | undefined, int32
    */
    totalPages?: number;
    /**
     * @type boolean | undefined
    */
    last?: boolean;
    /**
     * @type object | undefined
    */
    sort?: SortObject;
    /**
     * @type integer | undefined, int32
    */
    numberOfElements?: number;
    /**
     * @type boolean | undefined
    */
    first?: boolean;
    /**
     * @type integer | undefined, int32
    */
    size?: number;
    /**
     * @type integer | undefined, int32
    */
    number?: number;
    /**
     * @type boolean | undefined
    */
    empty?: boolean;
};