/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MyPatientResponse } from './MyPatientResponse.ts'
import type { PageMetadata } from './PageMetadata.ts'

export type PagedModelMyPatientResponse = {
  /**
   * @type array | undefined
   */
  content?: MyPatientResponse[]
  /**
   * @type object | undefined
   */
  page?: PageMetadata
}
