/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CourseWithDaysResponse } from './CourseWithDaysResponse.ts'
import type { PageMetadata } from './PageMetadata.ts'

export type PagedModelCourseWithDaysResponse = {
  /**
   * @type array | undefined
   */
  content?: CourseWithDaysResponse[]
  /**
   * @type object | undefined
   */
  page?: PageMetadata
}
