/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PageableObject } from "./PageableObject.ts";
import type { RehabilitationExaminationFormResponse } from "./RehabilitationExaminationFormResponse.ts";
import type { SortObject } from "./SortObject.ts";

<<<<<<<< HEAD:src/api/types/PageRehabilitationExaminationFormResponse.ts
export type PageRehabilitationExaminationFormResponse = {
========
export type PageCategoryResponse = {
    /**
     * @type integer | undefined, int32
    */
    totalPages?: number;
    /**
     * @type integer | undefined, int64
    */
    totalElements?: number;
>>>>>>>> origin/feature/news:src/api/types/PageCategoryResponse.ts
    /**
     * @type object | undefined
    */
    pageable?: PageableObject;
    /**
     * @type integer | undefined, int32
    */
    numberOfElements?: number;
    /**
     * @type object | undefined
    */
    sort?: SortObject;
    /**
     * @type boolean | undefined
    */
    first?: boolean;
    /**
     * @type boolean | undefined
    */
    last?: boolean;
    /**
     * @type integer | undefined, int64
    */
    totalElements?: number;
    /**
     * @type object | undefined
    */
    pageable?: PageableObject;
    /**
     * @type integer | undefined, int32
    */
    numberOfElements?: number;
    /**
     * @type object | undefined
    */
    sort?: SortObject;
    /**
     * @type boolean | undefined
    */
<<<<<<<< HEAD:src/api/types/PageRehabilitationExaminationFormResponse.ts
    first?: boolean;
    /**
     * @type boolean | undefined
    */
    last?: boolean;
    /**
     * @type integer | undefined, int32
    */
    size?: number;
    /**
     * @type array | undefined
    */
    content?: RehabilitationExaminationFormResponse[];
    /**
     * @type integer | undefined, int32
    */
    number?: number;
    /**
     * @type boolean | undefined
    */
========
>>>>>>>> origin/feature/news:src/api/types/PageCategoryResponse.ts
    empty?: boolean;
};