/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type PendingPurchaseResponse = {
    /**
     * @type integer | undefined, int64
    */
    userCourseId?: number;
    /**
     * @type integer | undefined, int64
    */
    courseId?: number;
    /**
     * @type string | undefined
    */
    courseTitle?: string;
    /**
     * @type string | undefined
    */
    courseDescription?: string;
    /**
     * @type integer | undefined, int32
    */
    durationDays?: number;
    /**
     * @type string | undefined
    */
    assignedByDoctorName?: string;
    /**
     * @type string | undefined, date-time
    */
    assignedAt?: string;
    /**
     * @type string | undefined
    */
    notes?: string;
    /**
     * @type number | undefined
    */
    monthlyPrice?: number;
    /**
     * @type number | undefined
    */
    yearlyPrice?: number;
};