/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PresignedUrlResponse = {
  /**
   * @type string | undefined
   */
  presignedUrl?: string;
  /**
   * @type string | undefined
   */
  objectKey?: string;
  /**
   * @type string | undefined
   */
  expiresIn?: string;
};
