/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const purchasePackageRequestSubscriptionTypeEnum = {
    "ONE_MONTH": "ONE_MONTH",
    "THREE_MONTHS": "THREE_MONTHS",
    "TWELVE_MONTHS": "TWELVE_MONTHS"
} as const;

export type PurchasePackageRequestSubscriptionTypeEnumKey = (typeof purchasePackageRequestSubscriptionTypeEnum)[keyof typeof purchasePackageRequestSubscriptionTypeEnum];

export type PurchasePackageRequest = {
    /**
     * @type integer, int64
    */
    packageId: number;
    /**
     * @type string
    */
    subscriptionType: PurchasePackageRequestSubscriptionTypeEnumKey;
};