/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type RegisterRequest = {
    /**
     * @minLength 1
     * @type string
    */
    fullName: string;
    /**
     * @minLength 1
     * @pattern ^(Male|Female|Other)$
     * @type string
    */
    gender: string;
    /**
     * @type string, date
    */
    dateOfBirth: string;
    /**
     * @minLength 1
     * @pattern ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
     * @type string
    */
    verificationToken: string;
    /**
     * @minLength 6
     * @maxLength 6
     * @pattern ^\d{6}$
     * @type string
    */
    pin: string;
    /**
     * @minLength 1
     * @pattern ^[0-9]{12}$
     * @type string
    */
    nationalId: string;
};