/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type RescheduleAppointmentRequest = {
  /**
   * @type string | undefined, date
   */
  appointmentDate?: string
  /**
   * @type string | undefined
   */
  startTime?: string
  /**
   * @type integer | undefined, int64
   */
  doctorId?: number
}
