/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type TrainerResponse = {
  /**
   * @type integer | undefined, int64
   */
  id?: number;
  /**
   * @type string | undefined
   */
  email?: string;
  /**
   * @type string | undefined
   */
  fullName?: string;
  /**
   * @type integer | undefined, int64
   */
  doctorId?: number;
  /**
   * @type string | undefined, date-time
   */
  createdAt?: string;
  /**
   * @type string | undefined, date-time
   */
  updatedAt?: string;
};
