/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const transactionResponseTransactionTypeEnum = {
    "BALANCE_ADD": "BALANCE_ADD",
    "BALANCE_ADD_SEPAY": "BALANCE_ADD_SEPAY",
    "COURSE_PURCHASE": "COURSE_PURCHASE",
    "PACKAGE_PURCHASE": "PACKAGE_PURCHASE",
    "REFUND": "REFUND",
    "SUBSCRIPTION_RENEWAL": "SUBSCRIPTION_RENEWAL",
    "APPOINTMENT_BOOKING": "APPOINTMENT_BOOKING",
    "APPOINTMENT_REFUND": "APPOINTMENT_REFUND"
} as const;

export type TransactionResponseTransactionTypeEnumKey = (typeof transactionResponseTransactionTypeEnum)[keyof typeof transactionResponseTransactionTypeEnum];

export type TransactionResponse = {
    /**
     * @type integer | undefined, int64
    */
    id?: number;
    /**
     * @type string | undefined
    */
    userName?: string;
    /**
     * @type string | undefined
    */
    phoneNumber?: string;
    /**
     * @type string | undefined
    */
    transactionType?: TransactionResponseTransactionTypeEnumKey;
    /**
     * @type integer | undefined, int64
    */
    amount?: number;
    /**
     * @type integer | undefined, int64
    */
    balanceBefore?: number;
    /**
     * @type integer | undefined, int64
    */
    balanceAfter?: number;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type integer | undefined, int64
    */
    subscriptionId?: number;
    /**
     * @type string | undefined, date-time
    */
    createdAt?: string;
};