/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const updateBannerRequestStatusEnum = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ARCHIVED: 'ARCHIVED',
} as const

export type UpdateBannerRequestStatusEnumKey =
  (typeof updateBannerRequestStatusEnum)[keyof typeof updateBannerRequestStatusEnum]

export type UpdateBannerRequest = {
  /**
   * @type string
   */
  title: string
  /**
   * @type string
   */
  imageUrl: string
  /**
   * @type integer | undefined, int32
   */
  displayOrder?: number
  /**
   * @type string
   */
  status: UpdateBannerRequestStatusEnumKey
}
