/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateExercisePackageRequest = {
  /**
   * @type object | undefined
   */
  title?: {
    [key: string]: string
  }
  /**
   * @type object | undefined
   */
  description?: {
    [key: string]: string
  }
  /**
   * @minLength 1
   * @type string
   */
  imageUrl: string
  /**
   * @type array
   */
  categoryIds: number[]
  /**
   * @type array
   */
  exerciseIds: number[]
}
