/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const updateTrainerRequestStaffTypeEnum = {
    "DOCTOR": "DOCTOR",
    "TRAINER": "TRAINER",
    "ADMIN": "ADMIN",
    "SUPER_ADMIN": "SUPER_ADMIN"
} as const;

export type UpdateTrainerRequestStaffTypeEnumKey = (typeof updateTrainerRequestStaffTypeEnum)[keyof typeof updateTrainerRequestStaffTypeEnum];

/**
 * @description Update request for Trainer staff
*/
export type UpdateTrainerRequest = {
    /**
     * @description Staff email address
     * @type string
    */
    email: string;
    /**
     * @description Staff full name
     * @type string
    */
    fullName: string;
    /**
     * @description Staff type discriminator
     * @type string
    */
    staffType: UpdateTrainerRequestStaffTypeEnumKey;
};