/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export const updateAdminRequestStaffTypeEnum = {
    "DOCTOR": "DOCTOR",
    "TRAINER": "TRAINER",
    "ADMIN": "ADMIN",
    "SUPER_ADMIN": "SUPER_ADMIN"
} as const;

export type UpdateAdminRequestStaffTypeEnumKey = (typeof updateAdminRequestStaffTypeEnum)[keyof typeof updateAdminRequestStaffTypeEnum];

/**
 * @description Update request for Admin staff
*/
export type UpdateAdminRequest = {
    /**
     * @description Staff email address
     * @type string
    */
    email: string;
    /**
     * @description Staff full name
     * @type string
    */
    fullName: string;
    /**
     * @description Staff type discriminator
     * @type string
    */
    staffType: UpdateAdminRequestStaffTypeEnumKey;
};