/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { LocalTime } from "./LocalTime.ts";

export const updateClinicScheduleRequestDayOfWeekEnum = {
    "MONDAY": "MONDAY",
    "TUESDAY": "TUESDAY",
    "WEDNESDAY": "WEDNESDAY",
    "THURSDAY": "THURSDAY",
    "FRIDAY": "FRIDAY",
    "SATURDAY": "SATURDAY",
    "SUNDAY": "SUNDAY"
} as const;

export type UpdateClinicScheduleRequestDayOfWeekEnumKey = (typeof updateClinicScheduleRequestDayOfWeekEnum)[keyof typeof updateClinicScheduleRequestDayOfWeekEnum];

export type UpdateClinicScheduleRequest = {
    /**
     * @type string
    */
    dayOfWeek: UpdateClinicScheduleRequestDayOfWeekEnumKey;
    /**
     * @type boolean
    */
    isOpen: boolean;
    /**
     * @type object
    */
    openingTime: LocalTime;
    /**
     * @type object
    */
    closingTime: LocalTime;
    /**
     * @type integer, int32
    */
    slotDurationMinutes: number;
};