/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type UpdateBannerRequest = {
    /**
     * @type string
    */
    title: string;
    /**
     * @type string | undefined
    */
    description?: string;
    /**
     * @type string | undefined
    */
    linkUrl?: string;
    /**
     * @type integer, int32
    */
    displayOrder: number;
    /**
     * @type string
    */
    imageUrl: string;
    /**
     * @type boolean
    */
    isActive: boolean;
    /**
     * @type string | undefined, date
    */
    startDate?: string;
    /**
     * @type string | undefined, date
    */
    endDate?: string;
};