/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UserCourseAssignmentResponse = {
  /**
   * @type integer | undefined, int64
   */
  id?: number
  /**
   * @type integer | undefined, int64
   */
  userId?: number
  /**
   * @type string | undefined
   */
  userPhoneNumber?: string
  /**
   * @type integer | undefined, int64
   */
  courseId?: number
  /**
   * @type object | undefined
   */
  courseTitle?: {
    [key: string]: string
  }
  /**
   * @type integer | undefined, int32
   */
  courseDurationDays?: number
  /**
   * @type string | undefined, date-time
   */
  assignedAt?: string
  /**
   * @type string | undefined
   */
  notes?: string
  /**
   * @type boolean | undefined
   */
  hasStarted?: boolean
  /**
   * @type boolean | undefined
   */
  isCompleted?: boolean
}
