/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { CreateExerciseMutationRequest, CreateExerciseMutationResponse } from "../../types/exercisesController/CreateExercise.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getCreateExerciseUrl() {
  const res = { method: 'POST', url: `/api/exercises` as const }  
  return res
}

/**
 * @description Create a new exercise with title, description, media URLs, duration, multiple categories, and multiple groups
 * @summary Create exercise
 * {@link /api/exercises}
 */
export async function createExercise(data: CreateExerciseMutationRequest, config: Partial<RequestConfig<CreateExerciseMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateExerciseMutationResponse, ResponseErrorConfig<Error>, CreateExerciseMutationRequest>({ method : "POST", url : getCreateExerciseUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}