/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetAllExercisesQueryResponse, GetAllExercisesQueryParams } from "../../types/exercisesController/GetAllExercises.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetAllExercisesUrl() {
  const res = { method: 'GET', url: `/api/exercises` as const }  
  return res
}

/**
 * @description Retrieve exercises with pagination. Default page size is 20.
 * @summary Get all exercises
 * {@link /api/exercises}
 */
export async function getAllExercises(params: GetAllExercisesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetAllExercisesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetAllExercisesUrl().url.toString(), params, ... requestConfig })  
  return res.data
}