/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { SearchExercisesByTitleQueryResponse, SearchExercisesByTitleQueryParams } from "../../types/exercisesController/SearchExercisesByTitle.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getSearchExercisesByTitleUrl() {
  const res = { method: 'GET', url: `/api/exercises/search` as const }  
  return res
}

/**
 * @description Search exercises by title (case-insensitive, partial match)
 * @summary Search exercises by title
 * {@link /api/exercises/search}
 */
export async function searchExercisesByTitle(params: SearchExercisesByTitleQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<SearchExercisesByTitleQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getSearchExercisesByTitleUrl().url.toString(), params, ... requestConfig })  
  return res.data
}