/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pageable } from "../Pageable.ts";
import type { PagedModel } from "../PagedModel.ts";

export const getAllNewsQueryParamsStatusEnum = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  ARCHIVED: "ARCHIVED",
} as const;

export type GetAllNewsQueryParamsStatusEnumKey =
  (typeof getAllNewsQueryParamsStatusEnum)[keyof typeof getAllNewsQueryParamsStatusEnum];

export type GetAllNewsQueryParams = {
  /**
   * @type object
   */
  pageable: Pageable;
  /**
   * @type string | undefined
   */
  status?: GetAllNewsQueryParamsStatusEnumKey;
  /**
   * @type string | undefined
   */
  category?: string;
  /**
   * @type string | undefined
   */
  title?: string;
};

/**
 * @description OK
 */
export type GetAllNews200 = PagedModel;

export type GetAllNewsQueryResponse = GetAllNews200;

export type GetAllNewsQuery = {
  Response: GetAllNews200;
  QueryParams: GetAllNewsQueryParams;
  Errors: any;
};
