/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pageable } from "../Pageable.ts";
import type { PageNewsResponse } from "../PageNewsResponse.ts";

export type GetNewsByTitleQueryParams = {
    /**
     * @type string
    */
    title: string;
    /**
     * @type object
    */
    pageable: Pageable;
};

/**
 * @description OK
*/
export type GetNewsByTitle200 = PageNewsResponse;

export type GetNewsByTitleQueryResponse = GetNewsByTitle200;

export type GetNewsByTitleQuery = {
    Response: GetNewsByTitle200;
    QueryParams: GetNewsByTitleQueryParams;
    Errors: any;
};