/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { SendOtpForUserMutationRequest, SendOtpForUserMutationResponse } from "../../types/SendOtpForUser.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getSendOtpForUserUrl() {
  const res = { method: 'POST', url: `/api/auth/user/send-otp` as const }  
  return res
}

/**
 * @description Send OTP for user login (users authenticate via OTP)
 * @summary Send OTP to user's phone
 * {@link /api/auth/user/send-otp}
 */
export async function sendOtpForUser(data: SendOtpForUserMutationRequest, config: Partial<RequestConfig<SendOtpForUserMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SendOtpForUserMutationResponse, ResponseErrorConfig<Error>, SendOtpForUserMutationRequest>({ method : "POST", url : getSendOtpForUserUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}