/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { StaffLoginMutationRequest, StaffLoginMutationResponse } from "../../types/StaffLogin.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getStaffLoginUrl() {
  const res = { method: 'POST', url: `/api/auth/staff/login` as const }  
  return res
}

/**
 * @description Login for doctors and admins using email and password
 * @summary Staff login
 * {@link /api/auth/staff/login}
 */
export async function staffLogin(data: StaffLoginMutationRequest, config: Partial<RequestConfig<StaffLoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<StaffLoginMutationResponse, ResponseErrorConfig<Error>, StaffLoginMutationRequest>({ method : "POST", url : getStaffLoginUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}