/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateStartupPopupRequest } from "../CreateStartupPopupRequest.ts";
import type { StartupPopupResponse } from "../StartupPopupResponse.ts";

/**
 * @description OK
*/
export type CreatePopup200 = StartupPopupResponse;

export type CreatePopupMutationRequest = CreateStartupPopupRequest;

export type CreatePopupMutationResponse = CreatePopup200;

export type CreatePopupMutation = {
    Response: CreatePopup200;
    Request: CreatePopupMutationRequest;
    Errors: any;
};