/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { StartupPopupResponse } from '../StartupPopupResponse.ts'
import type { UpdateStartupPopupRequest } from '../UpdateStartupPopupRequest.ts'

export type UpdatePopupPathParams = {
  /**
   * @type integer, int64
   */
  id: number
}

/**
 * @description OK
 */
export type UpdatePopup200 = StartupPopupResponse

export type UpdatePopupMutationRequest = UpdateStartupPopupRequest

export type UpdatePopupMutationResponse = UpdatePopup200

export type UpdatePopupMutation = {
  Response: UpdatePopup200
  Request: UpdatePopupMutationRequest
  PathParams: UpdatePopupPathParams
  Errors: any
}
