/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/api-client'
import type { GetPricingQueryResponse } from '../../types/discountsController/GetPricing.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/api-client'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getPricingSuspenseQueryKey = () =>
  [{ url: '/api/discounts/pricing' }] as const

export type GetPricingSuspenseQueryKey = ReturnType<
  typeof getPricingSuspenseQueryKey
>

/**
 * @description Returns all service types with original price, active discount info, and final price. Available to all authenticated users.
 * @summary Get current prices with discounts
 * {@link /api/discounts/pricing}
 */
export async function getPricingSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetPricingQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/api/discounts/pricing`, ...requestConfig })
  return res.data
}

export function getPricingSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = getPricingSuspenseQueryKey()
  return queryOptions<
    GetPricingQueryResponse,
    ResponseErrorConfig<Error>,
    GetPricingQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getPricingSuspense(config)
    },
  })
}

/**
 * @description Returns all service types with original price, active discount info, and final price. Available to all authenticated users.
 * @summary Get current prices with discounts
 * {@link /api/discounts/pricing}
 */
export function useGetPricingSuspense<
  TData = GetPricingQueryResponse,
  TQueryKey extends QueryKey = GetPricingSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetPricingQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getPricingSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...getPricingSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
