/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/api-client'
import type { GetActiveDiscountsQueryResponse } from '../../types/discountsController/GetActiveDiscounts.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/api-client'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getActiveDiscountsQueryKey = () =>
  [{ url: '/api/discounts/active' }] as const

export type GetActiveDiscountsQueryKey = ReturnType<
  typeof getActiveDiscountsQueryKey
>

/**
 * @description Returns the current discount configuration for all types
 * @summary Get all active discounts
 * {@link /api/discounts/active}
 */
export async function getActiveDiscounts(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetActiveDiscountsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/api/discounts/active`, ...requestConfig })
  return res.data
}

export function getActiveDiscountsQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = getActiveDiscountsQueryKey()
  return queryOptions<
    GetActiveDiscountsQueryResponse,
    ResponseErrorConfig<Error>,
    GetActiveDiscountsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getActiveDiscounts(config)
    },
  })
}

/**
 * @description Returns the current discount configuration for all types
 * @summary Get all active discounts
 * {@link /api/discounts/active}
 */
export function useGetActiveDiscounts<
  TData = GetActiveDiscountsQueryResponse,
  TQueryData = GetActiveDiscountsQueryResponse,
  TQueryKey extends QueryKey = GetActiveDiscountsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetActiveDiscountsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getActiveDiscountsQueryKey()

  const query = useQuery(
    {
      ...getActiveDiscountsQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
