/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pageable } from "../Pageable.ts";
import type { PagedModel } from "../PagedModel.ts";

export type GetAllGroupsQueryParams = {
  /**
   * @type object
   */
  pageable: Pageable;
};

/**
 * @description OK
 */
export type GetAllGroups200 = PagedModel;

export type GetAllGroupsQueryResponse = GetAllGroups200;

export type GetAllGroupsQuery = {
  Response: GetAllGroups200;
  QueryParams: GetAllGroupsQueryParams;
  Errors: any;
};
