/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CourseWithDaysResponse } from "../CourseWithDaysResponse.ts";

export type GetCourseStructurePathParams = {
    /**
     * @description Course ID
     * @type integer, int64
    */
    courseId: number;
};

/**
 * @description OK
*/
export type GetCourseStructure200 = CourseWithDaysResponse;

export type GetCourseStructureQueryResponse = GetCourseStructure200;

export type GetCourseStructureQuery = {
    Response: GetCourseStructure200;
    PathParams: GetCourseStructurePathParams;
    Errors: any;
};