/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { AssignPermissionToDoctorMutationRequest, AssignPermissionToDoctorMutationResponse, AssignPermissionToDoctorPathParams } from "../../types/AssignPermissionToDoctor.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getAssignPermissionToDoctorUrl(doctorId: AssignPermissionToDoctorPathParams["doctorId"]) {
  const res = { method: 'POST', url: `/api/permissions/doctor/${doctorId}/assign` as const }  
  return res
}

/**
 * @description Assign a permission to a doctor by permission name
 * @summary Assign permission to doctor
 * {@link /api/permissions/doctor/:doctorId/assign}
 */
export async function assignPermissionToDoctor(doctorId: AssignPermissionToDoctorPathParams["doctorId"], data?: AssignPermissionToDoctorMutationRequest, config: Partial<RequestConfig<AssignPermissionToDoctorMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AssignPermissionToDoctorMutationResponse, ResponseErrorConfig<Error>, AssignPermissionToDoctorMutationRequest>({ method : "POST", url : getAssignPermissionToDoctorUrl(doctorId).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}