/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { AssignPermissionToAdminMutationRequest, AssignPermissionToAdminMutationResponse, AssignPermissionToAdminPathParams } from "../../types/AssignPermissionToAdmin.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getAssignPermissionToAdminUrl(adminId: AssignPermissionToAdminPathParams["adminId"]) {
  const res = { method: 'POST', url: `/api/permissions/admin/${adminId}/assign` as const }  
  return res
}

/**
 * @description Assign a permission to an admin by permission name
 * @summary Assign permission to admin
 * {@link /api/permissions/admin/:adminId/assign}
 */
export async function assignPermissionToAdmin(adminId: AssignPermissionToAdminPathParams["adminId"], data?: AssignPermissionToAdminMutationRequest, config: Partial<RequestConfig<AssignPermissionToAdminMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<AssignPermissionToAdminMutationResponse, ResponseErrorConfig<Error>, AssignPermissionToAdminMutationRequest>({ method : "POST", url : getAssignPermissionToAdminUrl(adminId).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}