export * from "./assignPermissionToAdmin";
export * from "./assignPermissionToDoctor";
export * from "./getAdminPermissions";
export * from "./getAllPermissions";
export * from "./getDoctorPermissions";
export * from "./removePermissionFromAdmin";
export * from "./removePermissionFromDoctor";
export * from "./setAdminPermissions";
export * from "./setDoctorPermissions";