/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { SetAdminPermissionsMutationRequest, SetAdminPermissionsMutationResponse, SetAdminPermissionsPathParams } from "../../types/SetAdminPermissions.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getSetAdminPermissionsUrl(adminId: SetAdminPermissionsPathParams["adminId"]) {
  const res = { method: 'PUT', url: `/api/permissions/admin/${adminId}` as const }  
  return res
}

/**
 * @description Set all permissions for an admin (replaces existing)
 * @summary Set admin permissions
 * {@link /api/permissions/admin/:adminId}
 */
export async function setAdminPermissions(adminId: SetAdminPermissionsPathParams["adminId"], data?: SetAdminPermissionsMutationRequest, config: Partial<RequestConfig<SetAdminPermissionsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<SetAdminPermissionsMutationResponse, ResponseErrorConfig<Error>, SetAdminPermissionsMutationRequest>({ method : "PUT", url : getSetAdminPermissionsUrl(adminId).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}