/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FeedbackResponse } from "../FeedbackResponse.ts";

/**
 * @description Feedback list retrieved successfully
 */
export type GetMyFeedback200 = FeedbackResponse;

/**
 * @description No active course progress found
 */
export type GetMyFeedback404 = FeedbackResponse[];

export type GetMyFeedbackQueryResponse = GetMyFeedback200;

export type GetMyFeedbackQuery = {
  Response: GetMyFeedback200;
  Errors: GetMyFeedback404;
};
