/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { exerciseResponseSchema } from "../exerciseResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const getAllExercises200Schema = z.array(z.lazy(() => exerciseResponseSchema))

export const getAllExercisesQueryResponseSchema = z.lazy(() => getAllExercises200Schema)