/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableSchema } from "../pageableSchema.ts";
import { pageExerciseResponseSchema } from "../pageExerciseResponseSchema.ts";
import { z } from "zod/v4";

export const getExercisesQueryParamsSchema = z.object({
    "categoryId": z.optional(z.coerce.number().int().describe("Filter by category ID")),
"groupId": z.optional(z.coerce.number().int().describe("Filter by group ID")),
"title": z.optional(z.string().describe("Filter by title (case-insensitive, partial match)")),
get "pageable"(){
                return pageableSchema
              }
    })

/**
 * @description OK
 */
export const getExercises200Schema = z.lazy(() => pageExerciseResponseSchema)

export const getExercisesQueryResponseSchema = z.lazy(() => getExercises200Schema)