/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { exerciseResponseSchema } from "../exerciseResponseSchema.ts";
import { z } from "zod/v4";

export const searchExercisesByTitleQueryParamsSchema = z.object({
    "query": z.string().describe("Search query")
    })

/**
 * @description OK
 */
export const searchExercisesByTitle200Schema = z.array(z.lazy(() => exerciseResponseSchema))

export const searchExercisesByTitleQueryResponseSchema = z.lazy(() => searchExercisesByTitle200Schema)