/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableSchema } from "../pageableSchema.ts";
import { pagedModelSchema } from "../pagedModelSchema.ts";
import { z } from "zod/v4";

export const browsePackagesQueryParamsSchema = z.object({
    "query": z.optional(z.string().describe("Search query for title (case-insensitive)")),
get "pageable"(){
                return pageableSchema
              }
    })

/**
 * @description OK
 */
export const browsePackages200Schema = z.lazy(() => pagedModelSchema)

export const browsePackagesQueryResponseSchema = z.lazy(() => browsePackages200Schema)