/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const checkPackageAccessPathParamsSchema = z.object({
    "id": z.coerce.number().int().describe("Exercise Package ID")
    })

/**
 * @description OK
 */
export const checkPackageAccess200Schema = z.boolean()

export const checkPackageAccessQueryResponseSchema = z.lazy(() => checkPackageAccess200Schema)