/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { pageableSchema } from '../pageableSchema.ts'
import { pagedModelExercisePackageWithSubscriptionResponseSchema } from '../pagedModelExercisePackageWithSubscriptionResponseSchema.ts'
import { z } from 'zod/v4'

export const getCurrentUserPackagesQueryParamsSchema = z.object({
  get pageable() {
    return pageableSchema
  },
})

/**
 * @description OK
 */
export const getCurrentUserPackages200Schema = z.lazy(
  () => pagedModelExercisePackageWithSubscriptionResponseSchema
)

export const getCurrentUserPackagesQueryResponseSchema = z.lazy(
  () => getCurrentUserPackages200Schema
)
