/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { UpdateNationalHealthInsuranceMutationRequest, UpdateNationalHealthInsuranceMutationResponse, UpdateNationalHealthInsurancePathParams } from "../../types/UpdateNationalHealthInsurance.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getUpdateNationalHealthInsuranceUrl(userId: UpdateNationalHealthInsurancePathParams["userId"]) {
  const res = { method: 'PUT', url: `/api/users/${userId}/national-health-insurance` as const }  
  return res
}

/**
 * @description Admin can create or update any user's national health insurance information
 * @summary [Admin] Update user's national health insurance
 * {@link /api/users/:userId/national-health-insurance}
 */
export async function updateNationalHealthInsurance(userId: UpdateNationalHealthInsurancePathParams["userId"], data?: UpdateNationalHealthInsuranceMutationRequest, config: Partial<RequestConfig<UpdateNationalHealthInsuranceMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateNationalHealthInsuranceMutationResponse, ResponseErrorConfig<Error>, UpdateNationalHealthInsuranceMutationRequest>({ method : "PUT", url : getUpdateNationalHealthInsuranceUrl(userId).url.toString(), data : requestData, ... requestConfig })  
  return res.data
}