/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { CreateRatingMutationRequest, CreateRatingMutationResponse } from "../../types/CreateRating.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getCreateRatingUrl() {
  const res = { method: 'POST', url: `/api/course-ratings` as const }  
  return res
}

/**
 * @description Create a rating for a completed course. Users can only rate courses they have completed.
 * @summary Create course rating
 * {@link /api/course-ratings}
 */
export async function createRating(data: CreateRatingMutationRequest, config: Partial<RequestConfig<CreateRatingMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateRatingMutationResponse, ResponseErrorConfig<Error>, CreateRatingMutationRequest>({ method : "POST", url : getCreateRatingUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}