export type { AssignExerciseGroupToDoctorMutationKey } from "./useAssignExerciseGroupToDoctor.ts";
export type { AssignTrainerToDoctorMutationKey } from "./useAssignTrainerToDoctor.ts";
export type { CreateStaffMutationKey } from "./useCreateStaff.ts";
export type { DisableStaffMutationKey } from "./useDisableStaff.ts";
export type { EnableStaffMutationKey } from "./useEnableStaff.ts";
export type { GetAllStaffQueryKey } from "./useGetAllStaff.ts";
export type { GetAllStaffSuspenseQueryKey } from "./useGetAllStaffSuspense.ts";
export type { GetAvailableTrainersForDoctorQueryKey } from "./useGetAvailableTrainersForDoctor.ts";
export type { GetAvailableTrainersForDoctorSuspenseQueryKey } from "./useGetAvailableTrainersForDoctorSuspense.ts";
export type { GetExerciseGroupsByDoctorQueryKey } from "./useGetExerciseGroupsByDoctor.ts";
export type { GetExerciseGroupsByDoctorSuspenseQueryKey } from "./useGetExerciseGroupsByDoctorSuspense.ts";
export type { GetStaffByIdQueryKey } from "./useGetStaffById.ts";
export type { GetStaffByIdSuspenseQueryKey } from "./useGetStaffByIdSuspense.ts";
export type { GetTrainersByDoctorQueryKey } from "./useGetTrainersByDoctor.ts";
export type { GetTrainersByDoctorSuspenseQueryKey } from "./useGetTrainersByDoctorSuspense.ts";
export type { RemoveExerciseGroupFromDoctorMutationKey } from "./useRemoveExerciseGroupFromDoctor.ts";
export type { RemoveTrainerFromDoctorMutationKey } from "./useRemoveTrainerFromDoctor.ts";
export type { UpdateStaffMutationKey } from "./useUpdateStaff.ts";
export { assignExerciseGroupToDoctorMutationKey } from "./useAssignExerciseGroupToDoctor.ts";
export { assignExerciseGroupToDoctor } from "./useAssignExerciseGroupToDoctor.ts";
export { assignExerciseGroupToDoctorMutationOptions } from "./useAssignExerciseGroupToDoctor.ts";
export { useAssignExerciseGroupToDoctor } from "./useAssignExerciseGroupToDoctor.ts";
export { assignTrainerToDoctorMutationKey } from "./useAssignTrainerToDoctor.ts";
export { assignTrainerToDoctor } from "./useAssignTrainerToDoctor.ts";
export { assignTrainerToDoctorMutationOptions } from "./useAssignTrainerToDoctor.ts";
export { useAssignTrainerToDoctor } from "./useAssignTrainerToDoctor.ts";
export { createStaffMutationKey } from "./useCreateStaff.ts";
export { createStaff } from "./useCreateStaff.ts";
export { createStaffMutationOptions } from "./useCreateStaff.ts";
export { useCreateStaff } from "./useCreateStaff.ts";
export { disableStaffMutationKey } from "./useDisableStaff.ts";
export { disableStaff } from "./useDisableStaff.ts";
export { disableStaffMutationOptions } from "./useDisableStaff.ts";
export { useDisableStaff } from "./useDisableStaff.ts";
export { enableStaffMutationKey } from "./useEnableStaff.ts";
export { enableStaff } from "./useEnableStaff.ts";
export { enableStaffMutationOptions } from "./useEnableStaff.ts";
export { useEnableStaff } from "./useEnableStaff.ts";
export { getAllStaffQueryKey } from "./useGetAllStaff.ts";
export { getAllStaff } from "./useGetAllStaff.ts";
export { getAllStaffQueryOptions } from "./useGetAllStaff.ts";
export { useGetAllStaff } from "./useGetAllStaff.ts";
export { getAllStaffSuspenseQueryKey } from "./useGetAllStaffSuspense.ts";
export { getAllStaffSuspense } from "./useGetAllStaffSuspense.ts";
export { getAllStaffSuspenseQueryOptions } from "./useGetAllStaffSuspense.ts";
export { useGetAllStaffSuspense } from "./useGetAllStaffSuspense.ts";
export { getAvailableTrainersForDoctorQueryKey } from "./useGetAvailableTrainersForDoctor.ts";
export { getAvailableTrainersForDoctor } from "./useGetAvailableTrainersForDoctor.ts";
export { getAvailableTrainersForDoctorQueryOptions } from "./useGetAvailableTrainersForDoctor.ts";
export { useGetAvailableTrainersForDoctor } from "./useGetAvailableTrainersForDoctor.ts";
export { getAvailableTrainersForDoctorSuspenseQueryKey } from "./useGetAvailableTrainersForDoctorSuspense.ts";
export { getAvailableTrainersForDoctorSuspense } from "./useGetAvailableTrainersForDoctorSuspense.ts";
export { getAvailableTrainersForDoctorSuspenseQueryOptions } from "./useGetAvailableTrainersForDoctorSuspense.ts";
export { useGetAvailableTrainersForDoctorSuspense } from "./useGetAvailableTrainersForDoctorSuspense.ts";
export { getExerciseGroupsByDoctorQueryKey } from "./useGetExerciseGroupsByDoctor.ts";
export { getExerciseGroupsByDoctor } from "./useGetExerciseGroupsByDoctor.ts";
export { getExerciseGroupsByDoctorQueryOptions } from "./useGetExerciseGroupsByDoctor.ts";
export { useGetExerciseGroupsByDoctor } from "./useGetExerciseGroupsByDoctor.ts";
export { getExerciseGroupsByDoctorSuspenseQueryKey } from "./useGetExerciseGroupsByDoctorSuspense.ts";
export { getExerciseGroupsByDoctorSuspense } from "./useGetExerciseGroupsByDoctorSuspense.ts";
export { getExerciseGroupsByDoctorSuspenseQueryOptions } from "./useGetExerciseGroupsByDoctorSuspense.ts";
export { useGetExerciseGroupsByDoctorSuspense } from "./useGetExerciseGroupsByDoctorSuspense.ts";
export { getStaffByIdQueryKey } from "./useGetStaffById.ts";
export { getStaffById } from "./useGetStaffById.ts";
export { getStaffByIdQueryOptions } from "./useGetStaffById.ts";
export { useGetStaffById } from "./useGetStaffById.ts";
export { getStaffByIdSuspenseQueryKey } from "./useGetStaffByIdSuspense.ts";
export { getStaffByIdSuspense } from "./useGetStaffByIdSuspense.ts";
export { getStaffByIdSuspenseQueryOptions } from "./useGetStaffByIdSuspense.ts";
export { useGetStaffByIdSuspense } from "./useGetStaffByIdSuspense.ts";
export { getTrainersByDoctorQueryKey } from "./useGetTrainersByDoctor.ts";
export { getTrainersByDoctor } from "./useGetTrainersByDoctor.ts";
export { getTrainersByDoctorQueryOptions } from "./useGetTrainersByDoctor.ts";
export { useGetTrainersByDoctor } from "./useGetTrainersByDoctor.ts";
export { getTrainersByDoctorSuspenseQueryKey } from "./useGetTrainersByDoctorSuspense.ts";
export { getTrainersByDoctorSuspense } from "./useGetTrainersByDoctorSuspense.ts";
export { getTrainersByDoctorSuspenseQueryOptions } from "./useGetTrainersByDoctorSuspense.ts";
export { useGetTrainersByDoctorSuspense } from "./useGetTrainersByDoctorSuspense.ts";
export { removeExerciseGroupFromDoctorMutationKey } from "./useRemoveExerciseGroupFromDoctor.ts";
export { removeExerciseGroupFromDoctor } from "./useRemoveExerciseGroupFromDoctor.ts";
export { removeExerciseGroupFromDoctorMutationOptions } from "./useRemoveExerciseGroupFromDoctor.ts";
export { useRemoveExerciseGroupFromDoctor } from "./useRemoveExerciseGroupFromDoctor.ts";
export { removeTrainerFromDoctorMutationKey } from "./useRemoveTrainerFromDoctor.ts";
export { removeTrainerFromDoctor } from "./useRemoveTrainerFromDoctor.ts";
export { removeTrainerFromDoctorMutationOptions } from "./useRemoveTrainerFromDoctor.ts";
export { useRemoveTrainerFromDoctor } from "./useRemoveTrainerFromDoctor.ts";
export { updateStaffMutationKey } from "./useUpdateStaff.ts";
export { updateStaff } from "./useUpdateStaff.ts";
export { updateStaffMutationOptions } from "./useUpdateStaff.ts";
export { useUpdateStaff } from "./useUpdateStaff.ts";
