/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  AssignExerciseGroupToDoctorMutationResponse,
  AssignExerciseGroupToDoctorPathParams,
} from "../../types/staffManagementController/AssignExerciseGroupToDoctor.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const assignExerciseGroupToDoctorMutationKey = () =>
  [{ url: "/api/admin/doctors/:doctorId/exercise-groups/:groupId" }] as const;

export type AssignExerciseGroupToDoctorMutationKey = ReturnType<
  typeof assignExerciseGroupToDoctorMutationKey
>;

/**
 * @description Assign an exercise group to a doctor for access
 * @summary Assign exercise group to doctor
 * {@link /api/admin/doctors/:doctorId/exercise-groups/:groupId}
 */
export async function assignExerciseGroupToDoctor(
  doctorId: AssignExerciseGroupToDoctorPathParams["doctorId"],
  groupId: AssignExerciseGroupToDoctorPathParams["groupId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    AssignExerciseGroupToDoctorMutationResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "POST",
    url: `/api/admin/doctors/${doctorId}/exercise-groups/${groupId}`,
    ...requestConfig,
  });
  return res.data;
}

export function assignExerciseGroupToDoctorMutationOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = assignExerciseGroupToDoctorMutationKey();
  return mutationOptions<
    AssignExerciseGroupToDoctorMutationResponse,
    ResponseErrorConfig<Error>,
    {
      doctorId: AssignExerciseGroupToDoctorPathParams["doctorId"];
      groupId: AssignExerciseGroupToDoctorPathParams["groupId"];
    },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ doctorId, groupId }) => {
      return assignExerciseGroupToDoctor(doctorId, groupId, config);
    },
  });
}

/**
 * @description Assign an exercise group to a doctor for access
 * @summary Assign exercise group to doctor
 * {@link /api/admin/doctors/:doctorId/exercise-groups/:groupId}
 */
export function useAssignExerciseGroupToDoctor<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AssignExerciseGroupToDoctorMutationResponse,
      ResponseErrorConfig<Error>,
      {
        doctorId: AssignExerciseGroupToDoctorPathParams["doctorId"];
        groupId: AssignExerciseGroupToDoctorPathParams["groupId"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? assignExerciseGroupToDoctorMutationKey();

  const baseOptions = assignExerciseGroupToDoctorMutationOptions(
    config,
  ) as UseMutationOptions<
    AssignExerciseGroupToDoctorMutationResponse,
    ResponseErrorConfig<Error>,
    {
      doctorId: AssignExerciseGroupToDoctorPathParams["doctorId"];
      groupId: AssignExerciseGroupToDoctorPathParams["groupId"];
    },
    TContext
  >;

  return useMutation<
    AssignExerciseGroupToDoctorMutationResponse,
    ResponseErrorConfig<Error>,
    {
      doctorId: AssignExerciseGroupToDoctorPathParams["doctorId"];
      groupId: AssignExerciseGroupToDoctorPathParams["groupId"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    AssignExerciseGroupToDoctorMutationResponse,
    ResponseErrorConfig<Error>,
    {
      doctorId: AssignExerciseGroupToDoctorPathParams["doctorId"];
      groupId: AssignExerciseGroupToDoctorPathParams["groupId"];
    },
    TContext
  >;
}
