/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { CreateStaffMutationRequest, CreateStaffMutationResponse } from "../../types/staffManagementController/CreateStaff.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const createStaffMutationKey = () => [{ url: '/api/admin/staff' }] as const

export type CreateStaffMutationKey = ReturnType<typeof createStaffMutationKey>

/**
 * @description Create a new staff account. SUPER_ADMIN can create ADMIN/DOCTOR/TRAINER. ADMIN can only create DOCTOR/TRAINER.
 * @summary Create staff account
 * {@link /api/admin/staff}
 */
export async function createStaff(data: CreateStaffMutationRequest, config: Partial<RequestConfig<CreateStaffMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<CreateStaffMutationResponse, ResponseErrorConfig<Error>, CreateStaffMutationRequest>({ method : "POST", url : `/api/admin/staff`, data : requestData, ... requestConfig })  
  return res.data
}

export function createStaffMutationOptions(config: Partial<RequestConfig<CreateStaffMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = createStaffMutationKey()
  return mutationOptions<CreateStaffMutationResponse, ResponseErrorConfig<Error>, {data: CreateStaffMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return createStaff(data, config)
    },
  })
}

/**
 * @description Create a new staff account. SUPER_ADMIN can create ADMIN/DOCTOR/TRAINER. ADMIN can only create DOCTOR/TRAINER.
 * @summary Create staff account
 * {@link /api/admin/staff}
 */
export function useCreateStaff<TContext>(options: 
{
  mutation?: UseMutationOptions<CreateStaffMutationResponse, ResponseErrorConfig<Error>, {data: CreateStaffMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateStaffMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? createStaffMutationKey()

  const baseOptions = createStaffMutationOptions(config) as UseMutationOptions<CreateStaffMutationResponse, ResponseErrorConfig<Error>, {data: CreateStaffMutationRequest}, TContext>

  return useMutation<CreateStaffMutationResponse, ResponseErrorConfig<Error>, {data: CreateStaffMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<CreateStaffMutationResponse, ResponseErrorConfig<Error>, {data: CreateStaffMutationRequest}, TContext>
}