/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import type {
  GetTrainersByDoctorQueryResponse,
  GetTrainersByDoctorPathParams,
} from "../../types/staffManagementController/GetTrainersByDoctor.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getTrainersByDoctorSuspenseQueryKey = (
  doctorId: GetTrainersByDoctorPathParams["doctorId"],
) =>
  [
    {
      url: "/api/admin/doctors/:doctorId/trainers",
      params: { doctorId: doctorId },
    },
  ] as const;

export type GetTrainersByDoctorSuspenseQueryKey = ReturnType<
  typeof getTrainersByDoctorSuspenseQueryKey
>;

/**
 * @description List all trainers assigned to a specific doctor
 * @summary Get trainers by doctor
 * {@link /api/admin/doctors/:doctorId/trainers}
 */
export async function getTrainersByDoctorSuspense(
  doctorId: GetTrainersByDoctorPathParams["doctorId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetTrainersByDoctorQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/api/admin/doctors/${doctorId}/trainers`,
    ...requestConfig,
  });
  return res.data;
}

export function getTrainersByDoctorSuspenseQueryOptions(
  doctorId: GetTrainersByDoctorPathParams["doctorId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getTrainersByDoctorSuspenseQueryKey(doctorId);
  return queryOptions<
    GetTrainersByDoctorQueryResponse,
    ResponseErrorConfig<Error>,
    GetTrainersByDoctorQueryResponse,
    typeof queryKey
  >({
    enabled: !!doctorId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getTrainersByDoctorSuspense(doctorId, config);
    },
  });
}

/**
 * @description List all trainers assigned to a specific doctor
 * @summary Get trainers by doctor
 * {@link /api/admin/doctors/:doctorId/trainers}
 */
export function useGetTrainersByDoctorSuspense<
  TData = GetTrainersByDoctorQueryResponse,
  TQueryKey extends QueryKey = GetTrainersByDoctorSuspenseQueryKey,
>(
  doctorId: GetTrainersByDoctorPathParams["doctorId"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetTrainersByDoctorQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getTrainersByDoctorSuspenseQueryKey(doctorId);

  const query = useSuspenseQuery(
    {
      ...getTrainersByDoctorSuspenseQueryOptions(doctorId, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
