/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type {
  GetExerciseGroupsByDoctorQueryResponse,
  GetExerciseGroupsByDoctorPathParams,
} from "../../types/staffManagementController/GetExerciseGroupsByDoctor.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getExerciseGroupsByDoctorSuspenseQueryKey = (
  doctorId: GetExerciseGroupsByDoctorPathParams["doctorId"],
) =>
  [
    {
      url: "/api/admin/doctors/:doctorId/exercise-groups",
      params: { doctorId: doctorId },
    },
  ] as const;

export type GetExerciseGroupsByDoctorSuspenseQueryKey = ReturnType<
  typeof getExerciseGroupsByDoctorSuspenseQueryKey
>;

/**
 * @description List all exercise groups assigned to a specific doctor
 * @summary Get exercise groups by doctor
 * {@link /api/admin/doctors/:doctorId/exercise-groups}
 */
export async function getExerciseGroupsByDoctorSuspense(
  doctorId: GetExerciseGroupsByDoctorPathParams["doctorId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetExerciseGroupsByDoctorQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/api/admin/doctors/${doctorId}/exercise-groups`,
    ...requestConfig,
  });
  return res.data;
}

export function getExerciseGroupsByDoctorSuspenseQueryOptions(
  doctorId: GetExerciseGroupsByDoctorPathParams["doctorId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getExerciseGroupsByDoctorSuspenseQueryKey(doctorId);
  return queryOptions<
    GetExerciseGroupsByDoctorQueryResponse,
    ResponseErrorConfig<Error>,
    GetExerciseGroupsByDoctorQueryResponse,
    typeof queryKey
  >({
    enabled: !!doctorId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getExerciseGroupsByDoctorSuspense(doctorId, config);
    },
  });
}

/**
 * @description List all exercise groups assigned to a specific doctor
 * @summary Get exercise groups by doctor
 * {@link /api/admin/doctors/:doctorId/exercise-groups}
 */
export function useGetExerciseGroupsByDoctorSuspense<
  TData = GetExerciseGroupsByDoctorQueryResponse,
  TQueryKey extends QueryKey = GetExerciseGroupsByDoctorSuspenseQueryKey,
>(
  doctorId: GetExerciseGroupsByDoctorPathParams["doctorId"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetExerciseGroupsByDoctorQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ??
    getExerciseGroupsByDoctorSuspenseQueryKey(doctorId);

  const query = useSuspenseQuery(
    {
      ...getExerciseGroupsByDoctorSuspenseQueryOptions(doctorId, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
