/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetAvailableTrainersForDoctorQueryResponse, GetAvailableTrainersForDoctorPathParams, GetAvailableTrainersForDoctorQueryParams } from "../../types/staffManagementController/GetAvailableTrainersForDoctor.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getAvailableTrainersForDoctorSuspenseQueryKey = (doctorId: GetAvailableTrainersForDoctorPathParams["doctorId"], params?: GetAvailableTrainersForDoctorQueryParams) => [{ url: '/api/admin/staff/doctors/:doctorId/available-trainers', params: {doctorId:doctorId} }, ...(params ? [params] : [])] as const

export type GetAvailableTrainersForDoctorSuspenseQueryKey = ReturnType<typeof getAvailableTrainersForDoctorSuspenseQueryKey>

/**
 * @description Returns the 5 closest matching trainers who are available to be assigned to a specific doctor. Includes trainers who are either unassigned or assigned to a different doctor. Results are sorted alphabetically by full name. No pagination - always returns max 5 results.
 * @summary Get top 5 available trainers for doctor assignment
 * {@link /api/admin/staff/doctors/:doctorId/available-trainers}
 */
export async function getAvailableTrainersForDoctorSuspense(doctorId: GetAvailableTrainersForDoctorPathParams["doctorId"], params?: GetAvailableTrainersForDoctorQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetAvailableTrainersForDoctorQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/admin/staff/doctors/${doctorId}/available-trainers`, params, ... requestConfig })  
  return res.data
}

export function getAvailableTrainersForDoctorSuspenseQueryOptions(doctorId: GetAvailableTrainersForDoctorPathParams["doctorId"], params?: GetAvailableTrainersForDoctorQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getAvailableTrainersForDoctorSuspenseQueryKey(doctorId, params)
  return queryOptions<GetAvailableTrainersForDoctorQueryResponse, ResponseErrorConfig<Error>, GetAvailableTrainersForDoctorQueryResponse, typeof queryKey>({
   enabled: !!(doctorId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getAvailableTrainersForDoctorSuspense(doctorId, params, config)
   },
  })
}

/**
 * @description Returns the 5 closest matching trainers who are available to be assigned to a specific doctor. Includes trainers who are either unassigned or assigned to a different doctor. Results are sorted alphabetically by full name. No pagination - always returns max 5 results.
 * @summary Get top 5 available trainers for doctor assignment
 * {@link /api/admin/staff/doctors/:doctorId/available-trainers}
 */
export function useGetAvailableTrainersForDoctorSuspense<TData = GetAvailableTrainersForDoctorQueryResponse, TQueryKey extends QueryKey = GetAvailableTrainersForDoctorSuspenseQueryKey>(doctorId: GetAvailableTrainersForDoctorPathParams["doctorId"], params?: GetAvailableTrainersForDoctorQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetAvailableTrainersForDoctorQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getAvailableTrainersForDoctorSuspenseQueryKey(doctorId, params)

  const query = useSuspenseQuery({
   ...getAvailableTrainersForDoctorSuspenseQueryOptions(doctorId, params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}