/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { SearchDoctorsQueryResponse, SearchDoctorsQueryParams } from "../../types/staffManagementController/SearchDoctors.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const searchDoctorsQueryKey = (params?: SearchDoctorsQueryParams) => [{ url: '/api/admin/staff/doctors/search' }, ...(params ? [params] : [])] as const

export type SearchDoctorsQueryKey = ReturnType<typeof searchDoctorsQueryKey>

/**
 * @description Returns the 5 closest matching doctors based on name, email, or specialization. Results are sorted alphabetically by full name. No pagination - always returns max 5 results.
 * @summary Search doctors (top 5 results)
 * {@link /api/admin/staff/doctors/search}
 */
export async function searchDoctors(params?: SearchDoctorsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<SearchDoctorsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/admin/staff/doctors/search`, params, ... requestConfig })  
  return res.data
}

export function searchDoctorsQueryOptions(params?: SearchDoctorsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = searchDoctorsQueryKey(params)
  return queryOptions<SearchDoctorsQueryResponse, ResponseErrorConfig<Error>, SearchDoctorsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return searchDoctors(params, config)
   },
  })
}

/**
 * @description Returns the 5 closest matching doctors based on name, email, or specialization. Results are sorted alphabetically by full name. No pagination - always returns max 5 results.
 * @summary Search doctors (top 5 results)
 * {@link /api/admin/staff/doctors/search}
 */
export function useSearchDoctors<TData = SearchDoctorsQueryResponse, TQueryData = SearchDoctorsQueryResponse, TQueryKey extends QueryKey = SearchDoctorsQueryKey>(params?: SearchDoctorsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<SearchDoctorsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? searchDoctorsQueryKey(params)

  const query = useQuery({
   ...searchDoctorsQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}