/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { SearchDoctorsQueryResponse, SearchDoctorsQueryParams } from "../../types/staffManagementController/SearchDoctors.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const searchDoctorsSuspenseQueryKey = (params?: SearchDoctorsQueryParams) => [{ url: '/api/admin/staff/doctors/search' }, ...(params ? [params] : [])] as const

export type SearchDoctorsSuspenseQueryKey = ReturnType<typeof searchDoctorsSuspenseQueryKey>

/**
 * @description Returns the 5 closest matching doctors based on name, email, or specialization. Results are sorted alphabetically by full name. No pagination - always returns max 5 results.
 * @summary Search doctors (top 5 results)
 * {@link /api/admin/staff/doctors/search}
 */
export async function searchDoctorsSuspense(params?: SearchDoctorsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<SearchDoctorsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/admin/staff/doctors/search`, params, ... requestConfig })  
  return res.data
}

export function searchDoctorsSuspenseQueryOptions(params?: SearchDoctorsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = searchDoctorsSuspenseQueryKey(params)
  return queryOptions<SearchDoctorsQueryResponse, ResponseErrorConfig<Error>, SearchDoctorsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return searchDoctorsSuspense(params, config)
   },
  })
}

/**
 * @description Returns the 5 closest matching doctors based on name, email, or specialization. Results are sorted alphabetically by full name. No pagination - always returns max 5 results.
 * @summary Search doctors (top 5 results)
 * {@link /api/admin/staff/doctors/search}
 */
export function useSearchDoctorsSuspense<TData = SearchDoctorsQueryResponse, TQueryKey extends QueryKey = SearchDoctorsSuspenseQueryKey>(params?: SearchDoctorsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<SearchDoctorsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? searchDoctorsSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...searchDoctorsSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}