/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { UpdateStaffPermissionsMutationRequest, UpdateStaffPermissionsMutationResponse, UpdateStaffPermissionsPathParams } from "../../types/staffManagementController/UpdateStaffPermissions.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const updateStaffPermissionsMutationKey = () => [{ url: '/api/admin/staff/:id/permissions' }] as const

export type UpdateStaffPermissionsMutationKey = ReturnType<typeof updateStaffPermissionsMutationKey>

/**
 * @description Update permissions for a staff member
 * @summary Update staff permissions
 * {@link /api/admin/staff/:id/permissions}
 */
export async function updateStaffPermissions(id: UpdateStaffPermissionsPathParams["id"], data: UpdateStaffPermissionsMutationRequest, config: Partial<RequestConfig<UpdateStaffPermissionsMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateStaffPermissionsMutationResponse, ResponseErrorConfig<Error>, UpdateStaffPermissionsMutationRequest>({ method : "PUT", url : `/api/admin/staff/${id}/permissions`, data : requestData, ... requestConfig })  
  return res.data
}

export function updateStaffPermissionsMutationOptions(config: Partial<RequestConfig<UpdateStaffPermissionsMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = updateStaffPermissionsMutationKey()
  return mutationOptions<UpdateStaffPermissionsMutationResponse, ResponseErrorConfig<Error>, {id: UpdateStaffPermissionsPathParams["id"], data: UpdateStaffPermissionsMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ id, data }) => {
      return updateStaffPermissions(id, data, config)
    },
  })
}

/**
 * @description Update permissions for a staff member
 * @summary Update staff permissions
 * {@link /api/admin/staff/:id/permissions}
 */
export function useUpdateStaffPermissions<TContext>(options: 
{
  mutation?: UseMutationOptions<UpdateStaffPermissionsMutationResponse, ResponseErrorConfig<Error>, {id: UpdateStaffPermissionsPathParams["id"], data: UpdateStaffPermissionsMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateStaffPermissionsMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? updateStaffPermissionsMutationKey()

  const baseOptions = updateStaffPermissionsMutationOptions(config) as UseMutationOptions<UpdateStaffPermissionsMutationResponse, ResponseErrorConfig<Error>, {id: UpdateStaffPermissionsPathParams["id"], data: UpdateStaffPermissionsMutationRequest}, TContext>

  return useMutation<UpdateStaffPermissionsMutationResponse, ResponseErrorConfig<Error>, {id: UpdateStaffPermissionsPathParams["id"], data: UpdateStaffPermissionsMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<UpdateStaffPermissionsMutationResponse, ResponseErrorConfig<Error>, {id: UpdateStaffPermissionsPathParams["id"], data: UpdateStaffPermissionsMutationRequest}, TContext>
}