/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { companyInfoResponseSchema } from "../companyInfoResponseSchema.ts";
import { z } from "zod/v4";

export const getCompanyInfoPathParamsSchema = z.object({
  userId: z.coerce.number().int().describe("User ID"),
});

/**
 * @description OK
 */
export const getCompanyInfo200Schema = z.lazy(() => companyInfoResponseSchema);

export const getCompanyInfoQueryResponseSchema = z.lazy(
  () => getCompanyInfo200Schema,
);
