/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { nonCompulsoryHealthInsuranceResponseSchema } from '../nonCompulsoryHealthInsuranceResponseSchema.ts'
import { z } from 'zod/v4'

/**
 * @description OK
 */
export const getMyNonCompulsoryInsurance200Schema = z.lazy(
  () => nonCompulsoryHealthInsuranceResponseSchema
)

export const getMyNonCompulsoryInsuranceQueryResponseSchema = z.lazy(
  () => getMyNonCompulsoryInsurance200Schema
)
