/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { nationalHealthInsuranceResponseSchema } from "../nationalHealthInsuranceResponseSchema.ts";
import { upsertNationalHealthInsuranceRequestSchema } from "../upsertNationalHealthInsuranceRequestSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const upsertMyNationalInsurance200Schema = z.lazy(
  () => nationalHealthInsuranceResponseSchema,
);

export const upsertMyNationalInsuranceMutationRequestSchema = z.lazy(
  () => upsertNationalHealthInsuranceRequestSchema,
);

export const upsertMyNationalInsuranceMutationResponseSchema = z.lazy(
  () => upsertMyNationalInsurance200Schema,
);
