/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetMyBalanceQueryResponse } from "../../types/balanceControllerController/GetMyBalance.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getMyBalanceQueryKey = () => [{ url: '/api/balance/my-balance' }] as const

export type GetMyBalanceQueryKey = ReturnType<typeof getMyBalanceQueryKey>

/**
 * {@link /api/balance/my-balance}
 */
export async function getMyBalance(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMyBalanceQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/balance/my-balance`, ... requestConfig })  
  return res.data
}

export function getMyBalanceQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMyBalanceQueryKey()
  return queryOptions<GetMyBalanceQueryResponse, ResponseErrorConfig<Error>, GetMyBalanceQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMyBalance(config)
   },
  })
}

/**
 * {@link /api/balance/my-balance}
 */
export function useGetMyBalance<TData = GetMyBalanceQueryResponse, TQueryData = GetMyBalanceQueryResponse, TQueryKey extends QueryKey = GetMyBalanceQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetMyBalanceQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMyBalanceQueryKey()

  const query = useQuery({
   ...getMyBalanceQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}