/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const assignPatientToDoctorRequestSchema = z.object({
    "userId": z.int(),
"notes": z.optional(z.string())
    })