/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const companyInfoResponseSchema = z.object({
  id: z.optional(z.int()),
  userId: z.optional(z.int()),
  companyName: z.optional(z.string()),
  companyTaxNumber: z.optional(z.string()),
  invoiceIssuanceAddress: z.optional(z.string()),
  createdAt: z.optional(z.string().datetime()),
  updatedAt: z.optional(z.string().datetime()),
});
