/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const courseDaySummaryDtoSchema = z.object({
    "dayNumber": z.optional(z.int()),
"description": z.optional(z.string()),
"exerciseCount": z.optional(z.int())
    })