/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createBannerRequestSchema = z.object({
    "title": z.string(),
"description": z.optional(z.string()),
"linkUrl": z.optional(z.string()),
"displayOrder": z.int(),
"imageUrl": z.string(),
"isActive": z.boolean(),
"startDate": z.optional(z.iso.date()),
"endDate": z.optional(z.iso.date())
    })