/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createDiscountRequestSchema = z.object({
    "applicableType": z.enum(["COURSE", "PACKAGE_ONE_MONTH", "PACKAGE_THREE_MONTHS", "PACKAGE_TWELVE_MONTHS", "APPOINTMENT"]),
"percentage": z.int().min(1).max(100),
"endDate": z.iso.date()
    })