/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createAppointmentRequestSchema = z.object({
    "appointmentType": z.optional(z.enum(["ONLINE", "OFFLINE"])),
"appointmentDate": z.iso.date(),
"startTime": z.string(),
"doctorId": z.optional(z.int()),
"patientNotes": z.optional(z.string()),
"sttLanguage": z.optional(z.enum(["EN_US", "VI_VN"])),
"pastResultImageKeys": z.optional(z.array(z.string())),
"patientTarget": z.optional(z.string()),
"existingProblems": z.optional(z.string()),
"paymentMethod": z.optional(z.enum(["BALANCE", "QR", "PAY_AT_CLINIC"]))
    })