/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createGroupRequestSchema = z.object({
    "name": z.string(),
"description": z.optional(z.string())
    })