/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const createCategoryRequestSchema = z.object({
    "name": z.string(),
"description": z.optional(z.string()),
"type": z.enum(["BODY_PART", "HEALTH_CONDITION", "EXERCISE_TYPE", "EXERCISE_EQUIPMENTS", "OTHERS"])
    })