/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const doctorStatsResponseSchema = z.object({
  doctorId: z.optional(z.int()),
  doctorName: z.optional(z.string()),
  specialization: z.optional(z.string()),
  patientCount: z.optional(z.int()),
  coursesAssigned: z.optional(z.int()),
  coursesCompleted: z.optional(z.int()),
  completionRate: z.optional(z.number()),
  appointmentsThisMonth: z.optional(z.int()),
  disputeCount: z.optional(z.int()),
});
