/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const loginWithPinRequestSchema = z.object({
  phoneNumber: z.string().regex(/^\+?[1-9]\d{1,14}$/),
  pin: z
    .string()
    .min(6)
    .max(6)
    .regex(/^\d{6}$/),
});
