/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { myPatientResponseSchema } from "./myPatientResponseSchema.ts";
import { pageMetadataSchema } from "./pageMetadataSchema.ts";
import { z } from "zod/v4";

export const pagedModelMyPatientResponseSchema = z.object({
    get "content"(){
                return z.array(myPatientResponseSchema).optional()
              },
get "page"(){
                return pageMetadataSchema.optional()
              }
    })