/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableObjectSchema } from "./pageableObjectSchema.ts";
import { rehabilitationExaminationFormResponseSchema } from "./rehabilitationExaminationFormResponseSchema.ts";
import { sortObjectSchema } from "./sortObjectSchema.ts";
import { z } from "zod/v4";

export const pageRehabilitationExaminationFormResponseSchema = z.object({
    "totalPages": z.optional(z.int()),
"totalElements": z.optional(z.int()),
get "pageable"(){
                return pageableObjectSchema.optional()
              },
"numberOfElements": z.optional(z.int()),
get "sort"(){
                return sortObjectSchema.optional()
              },
"first": z.optional(z.boolean()),
"last": z.optional(z.boolean()),
"size": z.optional(z.int()),
get "content"(){
                return z.array(rehabilitationExaminationFormResponseSchema).optional()
              },
"number": z.optional(z.int()),
"empty": z.optional(z.boolean())
    })