/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageMetadataSchema } from "./pageMetadataSchema.ts";
import { rehabilitationExaminationFormResponseSchema } from "./rehabilitationExaminationFormResponseSchema.ts";
import { z } from "zod/v4";

export const pagedModelRehabilitationExaminationFormResponseSchema = z.object({
    get "content"(){
                return z.array(rehabilitationExaminationFormResponseSchema).optional()
              },
get "page"(){
                return pageMetadataSchema.optional()
              }
    })