/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const sortObjectSchema = z.object({
    "unsorted": z.optional(z.boolean()),
"sorted": z.optional(z.boolean()),
"empty": z.optional(z.boolean())
    })