/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const startupPopupResponseSchema = z.object({
  id: z.optional(z.int()),
  title: z.optional(z.string()),
  imageUrl: z.optional(z.string()),
  active: z.optional(z.boolean()),
  createdAt: z.optional(z.string().datetime()),
  updatedAt: z.optional(z.string().datetime()),
})
