/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod/v4'

export const sttStatusResponseSchema = z.object({
  agentId: z.optional(z.string()),
  status: z.optional(z.string()),
  channelName: z.optional(z.string()),
  sourceLanguages: z.optional(z.array(z.string())),
})
