/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

/**
 * @description Update request for Super Admin staff
 */
export const updateSuperAdminRequestSchema = z.object({
    "email": z.string().describe("Staff email address"),
"fullName": z.string().describe("Staff full name"),
"staffType": z.enum(["DOCTOR", "TRAINER", "ADMIN", "SUPER_ADMIN"]).describe("Staff type discriminator")
    }).describe("Update request for Super Admin staff")