/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const updateUserProfileRequestSchema = z.object({
    "fullName": z.string(),
"gender": z.string(),
"dateOfBirth": z.iso.date(),
"email": z.optional(z.string())
    })