/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const updateStaffRequestSchema = z.object({
  email: z.string(),
  fullName: z.string(),
  phoneNumber: z.optional(z.string()),
  specialization: z.optional(z.string()),
  permissions: z.optional(z.array(z.string())),
});
