/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const videoTokenResponseSchema = z.object({
  channelName: z.optional(z.string()),
  token: z.optional(z.string()),
  uid: z.optional(z.int()),
  appId: z.optional(z.string()),
  expiresAt: z.optional(z.string().datetime()),
});
