/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pageable } from '../Pageable.ts'
import type { PagedModelBannerResponse } from '../PagedModelBannerResponse.ts'

export const getAllBannersQueryParamsStatusEnum = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ARCHIVED: 'ARCHIVED',
} as const

export type GetAllBannersQueryParamsStatusEnumKey =
  (typeof getAllBannersQueryParamsStatusEnum)[keyof typeof getAllBannersQueryParamsStatusEnum]

export type GetAllBannersQueryParams = {
  /**
   * @type string | undefined
   */
  status?: GetAllBannersQueryParamsStatusEnumKey
  /**
   * @type string | undefined
   */
  title?: string
  /**
   * @type object
   */
  pageable: Pageable
}

/**
 * @description OK
 */
export type GetAllBanners200 = PagedModelBannerResponse

export type GetAllBannersQueryResponse = GetAllBanners200

export type GetAllBannersQuery = {
  Response: GetAllBanners200
  QueryParams: GetAllBannersQueryParams
  Errors: any
}
