/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BannerResponse } from "../BannerResponse.ts";
import type { CreateBannerRequest } from "../CreateBannerRequest.ts";

/**
 * @description OK
*/
export type CreateBanner200 = BannerResponse;

export type CreateBannerMutationRequest = CreateBannerRequest;

export type CreateBannerMutationResponse = CreateBanner200;

export type CreateBannerMutation = {
    Response: CreateBanner200;
    Request: CreateBannerMutationRequest;
    Errors: any;
};