/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pageable } from "../Pageable.ts";
import type { PagedModel } from "../PagedModel.ts";

export type GetAllBannersQueryParams = {
    /**
     * @type object
    */
    pageable: Pageable;
    /**
     * @type boolean | undefined
    */
    isActive?: boolean;
    /**
     * @type string | undefined
    */
    title?: string;
};

/**
 * @description OK
*/
export type GetAllBanners200 = PagedModel;

export type GetAllBannersQueryResponse = GetAllBanners200;

export type GetAllBannersQuery = {
    Response: GetAllBanners200;
    QueryParams: GetAllBannersQueryParams;
    Errors: any;
};