/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from "zod/v4";

export const assignTrainerToDoctorPathParamsSchema = z.object({
  doctorId: z.coerce.number().int().describe("Doctor ID"),
  trainerId: z.coerce.number().int().describe("Trainer ID"),
});

/**
 * @description OK
 */
export const assignTrainerToDoctor200Schema = z.any();

export const assignTrainerToDoctorMutationResponseSchema = z.lazy(
  () => assignTrainerToDoctor200Schema,
);
