/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { pageableSchema } from "../pageableSchema.ts";
import { pagedModelSchema } from "../pagedModelSchema.ts";
import { z } from "zod/v4";

export const getAllStaffQueryParamsSchema = z.object({
  staffType: z.optional(
    z
      .enum(["DOCTOR", "TRAINER", "ADMIN", "SUPER_ADMIN"])
      .describe("Filter by staff type (DOCTOR, TRAINER, ADMIN, SUPER_ADMIN)"),
  ),
  enabled: z.optional(
    z.boolean().describe("Filter by enabled status (default: true)"),
  ),
  query: z.optional(
    z.string().describe("Search by name or email (case-insensitive)"),
  ),
  get pageable() {
    return pageableSchema;
  },
});

/**
 * @description OK
 */
export const getAllStaff200Schema = z.lazy(() => pagedModelSchema);

export const getAllStaffQueryResponseSchema = z.lazy(
  () => getAllStaff200Schema,
);
