/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { staffResponseSchema } from "../staffResponseSchema.ts";
import { z } from "zod/v4";

export const getAvailableTrainersForDoctorPathParamsSchema = z.object({
  doctorId: z.coerce.number().int().describe("Doctor ID"),
});

export const getAvailableTrainersForDoctorQueryParamsSchema = z.object({
  enabled: z
    .boolean()
    .default(true)
    .describe("Filter by enabled status (default: true)"),
  query: z.optional(
    z.string().describe("Search by fullName or email (case-insensitive)"),
  ),
});

/**
 * @description OK
 */
export const getAvailableTrainersForDoctor200Schema = z.array(
  z.lazy(() => staffResponseSchema),
);

export const getAvailableTrainersForDoctorQueryResponseSchema = z.lazy(
  () => getAvailableTrainersForDoctor200Schema,
);
