/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { staffResponseSchema } from "../staffResponseSchema.ts";
import { updateStaffRequestSchema } from "../updateStaffRequestSchema.ts";
import { z } from "zod/v4";

export const updateStaffPermissionsPathParamsSchema = z.object({
    "id": z.coerce.number().int().describe("Staff ID")
    })

/**
 * @description OK
 */
export const updateStaffPermissions200Schema = z.lazy(() => staffResponseSchema)

export const updateStaffPermissionsMutationRequestSchema = z.lazy(() => updateStaffRequestSchema).describe("Base update request for staff")

export const updateStaffPermissionsMutationResponseSchema = z.lazy(() => updateStaffPermissions200Schema)