/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { userResponseSchema } from "../userResponseSchema.ts";
import { z } from "zod/v4";

export const searchUsersByNameQueryParamsSchema = z
  .object({
    query: z.optional(
      z
        .string()
        .describe("Search by name, phone number, or email (case-insensitive)"),
    ),
  })
  .optional();

/**
 * @description OK
 */
export const searchUsersByName200Schema = z.array(
  z.lazy(() => userResponseSchema),
);

export const searchUsersByNameQueryResponseSchema = z.lazy(
  () => searchUsersByName200Schema,
);
