/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetAllGroupsQueryResponse,
  GetAllGroupsQueryParams,
} from "../../types/exerciseGroupsController/GetAllGroups.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAllGroupsQueryKey = (params: GetAllGroupsQueryParams) =>
  [{ url: "/api/exercise-groups" }, ...(params ? [params] : [])] as const;

export type GetAllGroupsQueryKey = ReturnType<typeof getAllGroupsQueryKey>;

/**
 * @description Retrieve exercise groups with pagination and optional search query. Returns only groups the user has access to.
 * @summary Get all groups with optional search
 * {@link /api/exercise-groups}
 */
export async function getAllGroups(
  params: GetAllGroupsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAllGroupsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/api/exercise-groups`, params, ...requestConfig });
  return res.data;
}

export function getAllGroupsQueryOptions(
  params: GetAllGroupsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getAllGroupsQueryKey(params);
  return queryOptions<
    GetAllGroupsQueryResponse,
    ResponseErrorConfig<Error>,
    GetAllGroupsQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getAllGroups(params, config);
    },
  });
}

/**
 * @description Retrieve exercise groups with pagination and optional search query. Returns only groups the user has access to.
 * @summary Get all groups with optional search
 * {@link /api/exercise-groups}
 */
export function useGetAllGroups<
  TData = GetAllGroupsQueryResponse,
  TQueryData = GetAllGroupsQueryResponse,
  TQueryKey extends QueryKey = GetAllGroupsQueryKey,
>(
  params: GetAllGroupsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetAllGroupsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getAllGroupsQueryKey(params);

  const query = useQuery(
    {
      ...getAllGroupsQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
