/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { SearchGroupsByNameQueryResponse, SearchGroupsByNameQueryParams } from "../../types/exerciseGroupsController/SearchGroupsByName.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { InfiniteData, QueryKey, QueryClient, UseSuspenseInfiniteQueryOptions, UseSuspenseInfiniteQueryResult } from "@tanstack/react-query";
import { searchGroupsByName } from "../../clients/exerciseGroupsController/searchGroupsByName.ts";
import { infiniteQueryOptions, useSuspenseInfiniteQuery } from "@tanstack/react-query";

export const searchGroupsByNameSuspenseInfiniteQueryKey = (params: SearchGroupsByNameQueryParams) => [{ url: '/api/exercise-groups/search' }, ...(params ? [params] : [])] as const

export type SearchGroupsByNameSuspenseInfiniteQueryKey = ReturnType<typeof searchGroupsByNameSuspenseInfiniteQueryKey>

export function searchGroupsByNameSuspenseInfiniteQueryOptions(params: SearchGroupsByNameQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = searchGroupsByNameSuspenseInfiniteQueryKey(params)
  return infiniteQueryOptions<SearchGroupsByNameQueryResponse, ResponseErrorConfig<Error>, InfiniteData<SearchGroupsByNameQueryResponse>, typeof queryKey, NonNullable<SearchGroupsByNameQueryParams['next_page']>>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal, pageParam }) => {
      config.signal = signal
    
      params = {
        ...(params ?? {}),
        ['next_page']: pageParam as unknown as SearchGroupsByNameQueryParams['next_page'],
      } as SearchGroupsByNameQueryParams
      return searchGroupsByName(params, config)
   },
   initialPageParam: 0,
  getNextPageParam: (lastPage) => lastPage?.['pagination']?.['next']?.['cursor'],
  getPreviousPageParam: (firstPage) => firstPage?.['pagination']?.['prev']?.['cursor']
  })
}

/**
 * @description Search exercise groups by name (case-insensitive, partial match)
 * @summary Search groups by name
 * {@link /api/exercise-groups/search}
 */
export function useSearchGroupsByNameSuspenseInfinite<TQueryFnData = SearchGroupsByNameQueryResponse, TError = ResponseErrorConfig<Error>, TData = InfiniteData<TQueryFnData>, TQueryKey extends QueryKey = SearchGroupsByNameSuspenseInfiniteQueryKey, TPageParam = NonNullable<SearchGroupsByNameQueryParams['next_page']>>(params: SearchGroupsByNameQueryParams, options: 
{
  query?: Partial<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, TData, TQueryKey, TPageParam>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? searchGroupsByNameSuspenseInfiniteQueryKey(params)

  const query = useSuspenseInfiniteQuery({
   ...searchGroupsByNameSuspenseInfiniteQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, TData, TQueryKey, TPageParam>, queryClient) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}