/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { SearchGroupsByNameQueryResponse, SearchGroupsByNameQueryParams } from "../../types/exerciseGroupsController/SearchGroupsByName.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const searchGroupsByNameQueryKey = (params: SearchGroupsByNameQueryParams) => [{ url: '/api/exercise-groups/search' }, ...(params ? [params] : [])] as const

export type SearchGroupsByNameQueryKey = ReturnType<typeof searchGroupsByNameQueryKey>

/**
 * @description Search exercise groups by name (case-insensitive, partial match)
 * @summary Search groups by name
 * {@link /api/exercise-groups/search}
 */
export async function searchGroupsByName(params: SearchGroupsByNameQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<SearchGroupsByNameQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/exercise-groups/search`, params, ... requestConfig })  
  return res.data
}

export function searchGroupsByNameQueryOptions(params: SearchGroupsByNameQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = searchGroupsByNameQueryKey(params)
  return queryOptions<SearchGroupsByNameQueryResponse, ResponseErrorConfig<Error>, SearchGroupsByNameQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return searchGroupsByName(params, config)
   },
  })
}

/**
 * @description Search exercise groups by name (case-insensitive, partial match)
 * @summary Search groups by name
 * {@link /api/exercise-groups/search}
 */
export function useSearchGroupsByName<TData = SearchGroupsByNameQueryResponse, TQueryData = SearchGroupsByNameQueryResponse, TQueryKey extends QueryKey = SearchGroupsByNameQueryKey>(params: SearchGroupsByNameQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<SearchGroupsByNameQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? searchGroupsByNameQueryKey(params)

  const query = useQuery({
   ...searchGroupsByNameQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}