/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { assignPatientToDoctorRequestSchema } from "../assignPatientToDoctorRequestSchema.ts";
import { doctorPatientResponseSchema } from "../doctorPatientResponseSchema.ts";
import { z } from "zod/v4";

export const assignPatientToDoctorPathParamsSchema = z.object({
  doctorId: z.coerce.number().int().describe("Doctor ID"),
});

/**
 * @description OK
 */
export const assignPatientToDoctor200Schema = z.lazy(
  () => doctorPatientResponseSchema,
);

export const assignPatientToDoctorMutationRequestSchema = z.lazy(
  () => assignPatientToDoctorRequestSchema,
);

export const assignPatientToDoctorMutationResponseSchema = z.lazy(
  () => assignPatientToDoctor200Schema,
);
