/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { otpResponseSchema } from "../otpResponseSchema.ts";
import { sendOtpRequestSchema } from "../sendOtpRequestSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const sendRegistrationOtp200Schema = z.lazy(() => otpResponseSchema)

export const sendRegistrationOtpMutationRequestSchema = z.lazy(() => sendOtpRequestSchema)

export const sendRegistrationOtpMutationResponseSchema = z.lazy(() => sendRegistrationOtp200Schema)