/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { verifyPinResetOtpRequestSchema } from "../verifyPinResetOtpRequestSchema.ts";
import { verifyRegistrationOtpResponseSchema } from "../verifyRegistrationOtpResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const verifyPinResetOtp200Schema = z.lazy(
  () => verifyRegistrationOtpResponseSchema,
);

export const verifyPinResetOtpMutationRequestSchema = z.lazy(
  () => verifyPinResetOtpRequestSchema,
);

export const verifyPinResetOtpMutationResponseSchema = z.lazy(
  () => verifyPinResetOtp200Schema,
);
