/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { pageableSchema } from '../pageableSchema.ts'
import { pagedModelAppointmentResponseSchema } from '../pagedModelAppointmentResponseSchema.ts'
import { z } from 'zod/v4'

export const getAllAppointmentsQueryParamsSchema = z.object({
  get pageable() {
    return pageableSchema
  },
})

/**
 * @description OK
 */
export const getAllAppointments200Schema = z.lazy(
  () => pagedModelAppointmentResponseSchema
)

export const getAllAppointmentsQueryResponseSchema = z.lazy(
  () => getAllAppointments200Schema
)
