/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { appointmentQrResponseSchema } from '../appointmentQrResponseSchema.ts'
import { z } from 'zod/v4'

export const getPaymentQrPathParamsSchema = z.object({
  id: z.coerce.number().int(),
})

/**
 * @description OK
 */
export const getPaymentQr200Schema = z.lazy(() => appointmentQrResponseSchema)

export const getPaymentQrQueryResponseSchema = z.lazy(
  () => getPaymentQr200Schema
)
