/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetExercisesQueryResponse, GetExercisesQueryParams } from "../../types/exercisesController/GetExercises.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getExercises } from "../../clients/exercisesController/getExercises.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getExercisesQueryKey = (params: GetExercisesQueryParams) => [{ url: '/api/exercises' }, ...(params ? [params] : [])] as const

export type GetExercisesQueryKey = ReturnType<typeof getExercisesQueryKey>

export function getExercisesQueryOptions(params: GetExercisesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getExercisesQueryKey(params)
  return queryOptions<GetExercisesQueryResponse, ResponseErrorConfig<Error>, GetExercisesQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getExercises(params, config)
   },
  })
}

/**
 * @description Retrieve exercises with optional filters (category, group, title). All filters are optional and can be combined. Default page size is 20. Sorted by newest first.
 * @summary Get exercises with filters
 * {@link /api/exercises}
 */
export function useGetExercises<TData = GetExercisesQueryResponse, TQueryData = GetExercisesQueryResponse, TQueryKey extends QueryKey = GetExercisesQueryKey>(params: GetExercisesQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetExercisesQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getExercisesQueryKey(params)

  const query = useQuery({
   ...getExercisesQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}