/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { SearchExercisesByTitleQueryResponse, SearchExercisesByTitleQueryParams } from "../../types/exercisesController/SearchExercisesByTitle.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { searchExercisesByTitle } from "../../clients/exercisesController/searchExercisesByTitle.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const searchExercisesByTitleQueryKey = (params: SearchExercisesByTitleQueryParams) => [{ url: '/api/exercises/search' }, ...(params ? [params] : [])] as const

export type SearchExercisesByTitleQueryKey = ReturnType<typeof searchExercisesByTitleQueryKey>

export function searchExercisesByTitleQueryOptions(params: SearchExercisesByTitleQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = searchExercisesByTitleQueryKey(params)
  return queryOptions<SearchExercisesByTitleQueryResponse, ResponseErrorConfig<Error>, SearchExercisesByTitleQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return searchExercisesByTitle(params, config)
   },
  })
}

/**
 * @description Search exercises by title (case-insensitive, partial match)
 * @summary Search exercises by title
 * {@link /api/exercises/search}
 */
export function useSearchExercisesByTitle<TData = SearchExercisesByTitleQueryResponse, TQueryData = SearchExercisesByTitleQueryResponse, TQueryKey extends QueryKey = SearchExercisesByTitleQueryKey>(params: SearchExercisesByTitleQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<SearchExercisesByTitleQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? searchExercisesByTitleQueryKey(params)

  const query = useQuery({
   ...searchExercisesByTitleQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}