/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { pageableSchema } from '../pageableSchema.ts'
import { pagedModelNewsResponseSchema } from '../pagedModelNewsResponseSchema.ts'
import { z } from 'zod/v4'

export const getAllNewsQueryParamsSchema = z.object({
  get pageable() {
    return pageableSchema
  },
  status: z.optional(z.enum(['DRAFT', 'PUBLISHED', 'ARCHIVED'])),
  category: z.optional(z.string()),
  title: z.optional(z.string()),
})

/**
 * @description OK
 */
export const getAllNews200Schema = z.lazy(() => pagedModelNewsResponseSchema)

export const getAllNewsQueryResponseSchema = z.lazy(() => getAllNews200Schema)
