/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { newsResponseSchema } from "../newsResponseSchema.ts";
import { z } from "zod/v4";

export const getNewsByIdPathParamsSchema = z.object({
    "id": z.coerce.number().int()
    })

/**
 * @description OK
 */
export const getNewsById200Schema = z.lazy(() => newsResponseSchema)

export const getNewsByIdQueryResponseSchema = z.lazy(() => getNewsById200Schema)