/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableSchema } from "../pageableSchema.ts";
import { pageNewsResponseSchema } from "../pageNewsResponseSchema.ts";
import { z } from "zod/v4";

export const getNewsByTitleQueryParamsSchema = z.object({
    "title": z.string(),
get "pageable"(){
                return pageableSchema
              }
    })

/**
 * @description OK
 */
export const getNewsByTitle200Schema = z.lazy(() => pageNewsResponseSchema)

export const getNewsByTitleQueryResponseSchema = z.lazy(() => getNewsByTitle200Schema)