export type { CreateCourseRequestMutationKey } from "./useCreateCourseRequest.ts";
export type { GetCourseRequestByIdQueryKey } from "./useGetCourseRequestById.ts";
export type { GetCourseRequestByIdSuspenseQueryKey } from "./useGetCourseRequestByIdSuspense.ts";
export type { GetDoctorPatients1QueryKey } from "./useGetDoctorPatients1.ts";
export type { GetDoctorPatients1SuspenseQueryKey } from "./useGetDoctorPatients1Suspense.ts";
export type { GetMyCourseRequestsQueryKey } from "./useGetMyCourseRequests.ts";
export type { GetMyCourseRequestsSuspenseQueryKey } from "./useGetMyCourseRequestsSuspense.ts";
export type { UpdateCourseRequestMutationKey } from "./useUpdateCourseRequest.ts";
export { createCourseRequestMutationKey } from "./useCreateCourseRequest.ts";
export { createCourseRequest } from "./useCreateCourseRequest.ts";
export { createCourseRequestMutationOptions } from "./useCreateCourseRequest.ts";
export { useCreateCourseRequest } from "./useCreateCourseRequest.ts";
export { getCourseRequestByIdQueryKey } from "./useGetCourseRequestById.ts";
export { getCourseRequestById } from "./useGetCourseRequestById.ts";
export { getCourseRequestByIdQueryOptions } from "./useGetCourseRequestById.ts";
export { useGetCourseRequestById } from "./useGetCourseRequestById.ts";
export { getCourseRequestByIdSuspenseQueryKey } from "./useGetCourseRequestByIdSuspense.ts";
export { getCourseRequestByIdSuspense } from "./useGetCourseRequestByIdSuspense.ts";
export { getCourseRequestByIdSuspenseQueryOptions } from "./useGetCourseRequestByIdSuspense.ts";
export { useGetCourseRequestByIdSuspense } from "./useGetCourseRequestByIdSuspense.ts";
export { getDoctorPatients1QueryKey } from "./useGetDoctorPatients1.ts";
export { getDoctorPatients1 } from "./useGetDoctorPatients1.ts";
export { getDoctorPatients1QueryOptions } from "./useGetDoctorPatients1.ts";
export { useGetDoctorPatients1 } from "./useGetDoctorPatients1.ts";
export { getDoctorPatients1SuspenseQueryKey } from "./useGetDoctorPatients1Suspense.ts";
export { getDoctorPatients1Suspense } from "./useGetDoctorPatients1Suspense.ts";
export { getDoctorPatients1SuspenseQueryOptions } from "./useGetDoctorPatients1Suspense.ts";
export { useGetDoctorPatients1Suspense } from "./useGetDoctorPatients1Suspense.ts";
export { getMyCourseRequestsQueryKey } from "./useGetMyCourseRequests.ts";
export { getMyCourseRequests } from "./useGetMyCourseRequests.ts";
export { getMyCourseRequestsQueryOptions } from "./useGetMyCourseRequests.ts";
export { useGetMyCourseRequests } from "./useGetMyCourseRequests.ts";
export { getMyCourseRequestsSuspenseQueryKey } from "./useGetMyCourseRequestsSuspense.ts";
export { getMyCourseRequestsSuspense } from "./useGetMyCourseRequestsSuspense.ts";
export { getMyCourseRequestsSuspenseQueryOptions } from "./useGetMyCourseRequestsSuspense.ts";
export { useGetMyCourseRequestsSuspense } from "./useGetMyCourseRequestsSuspense.ts";
export { updateCourseRequestMutationKey } from "./useUpdateCourseRequest.ts";
export { updateCourseRequest } from "./useUpdateCourseRequest.ts";
export { updateCourseRequestMutationOptions } from "./useUpdateCourseRequest.ts";
export { useUpdateCourseRequest } from "./useUpdateCourseRequest.ts";