/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetMyCourseRequestsQueryResponse, GetMyCourseRequestsQueryParams } from "../../types/trainerController/GetMyCourseRequests.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMyCourseRequestsSuspenseQueryKey = (params: GetMyCourseRequestsQueryParams) => [{ url: '/api/trainer/course-requests' }, ...(params ? [params] : [])] as const

export type GetMyCourseRequestsSuspenseQueryKey = ReturnType<typeof getMyCourseRequestsSuspenseQueryKey>

/**
 * @description View all course assignment requests created by this trainer, optionally filtered by status
 * @summary List my course requests
 * {@link /api/trainer/course-requests}
 */
export async function getMyCourseRequestsSuspense(params: GetMyCourseRequestsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMyCourseRequestsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/trainer/course-requests`, params, ... requestConfig })  
  return res.data
}

export function getMyCourseRequestsSuspenseQueryOptions(params: GetMyCourseRequestsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getMyCourseRequestsSuspenseQueryKey(params)
  return queryOptions<GetMyCourseRequestsQueryResponse, ResponseErrorConfig<Error>, GetMyCourseRequestsQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getMyCourseRequestsSuspense(params, config)
   },
  })
}

/**
 * @description View all course assignment requests created by this trainer, optionally filtered by status
 * @summary List my course requests
 * {@link /api/trainer/course-requests}
 */
export function useGetMyCourseRequestsSuspense<TData = GetMyCourseRequestsQueryResponse, TQueryKey extends QueryKey = GetMyCourseRequestsSuspenseQueryKey>(params: GetMyCourseRequestsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetMyCourseRequestsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMyCourseRequestsSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getMyCourseRequestsSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}