/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pageable } from '../Pageable.ts'
import type { PagedModel } from '../PagedModel.ts'

export type GetCompletedCoursesQueryParams = {
  /**
   * @type object
   */
  pageable: Pageable
}

/**
 * @description OK
 */
export type GetCompletedCourses200 = PagedModel

export type GetCompletedCoursesQueryResponse = GetCompletedCourses200

export type GetCompletedCoursesQuery = {
  Response: GetCompletedCourses200
  QueryParams: GetCompletedCoursesQueryParams
  Errors: any
}
