/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DayContentResponse } from "../DayContentResponse.ts";

export type GetDayContentPathParams = {
    /**
     * @description Course ID
     * @type integer, int64
    */
    courseId: number;
    /**
     * @description Day number (1-based)
     * @type integer, int32
    */
    dayNumber: number;
};

/**
 * @description OK
*/
export type GetDayContent200 = DayContentResponse;

export type GetDayContentQueryResponse = GetDayContent200;

export type GetDayContentQuery = {
    Response: GetDayContent200;
    PathParams: GetDayContentPathParams;
    Errors: any;
};