/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { MyAssignedCourseResponse } from "../MyAssignedCourseResponse.ts";

/**
 * @description OK
 */
export type GetMyAssignedCourses1200 = MyAssignedCourseResponse[];

export type GetMyAssignedCourses1QueryResponse = GetMyAssignedCourses1200;

export type GetMyAssignedCourses1Query = {
  Response: GetMyAssignedCourses1200;
  Errors: any;
};
