import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import "./globals.css";
import React from "react";
import NextTopLoader from "nextjs-toploader";
import {Toaster} from "sonner";

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vn">
      <body
        className={`${comfortaa.variable} font-sans antialiased`}
      >
      <NextTopLoader showSpinner={false}/>
      <Toaster />
      {children}
      </body>
    </html>
  );
}
