/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/api-client'
import type { GetMyCompanyInfoQueryResponse } from '../../types/userHealthInfoController/GetMyCompanyInfo.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/api-client'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getMyCompanyInfoQueryKey = () =>
  [{ url: '/api/users/me/health-info/company-info' }] as const

export type GetMyCompanyInfoQueryKey = ReturnType<
  typeof getMyCompanyInfoQueryKey
>

/**
 * @description Mobile users can retrieve their own company information
 * @summary Get own company info
 * {@link /api/users/me/health-info/company-info}
 */
export async function getMyCompanyInfo(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetMyCompanyInfoQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: `/api/users/me/health-info/company-info`,
    ...requestConfig,
  })
  return res.data
}

export function getMyCompanyInfoQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = getMyCompanyInfoQueryKey()
  return queryOptions<
    GetMyCompanyInfoQueryResponse,
    ResponseErrorConfig<Error>,
    GetMyCompanyInfoQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getMyCompanyInfo(config)
    },
  })
}

/**
 * @description Mobile users can retrieve their own company information
 * @summary Get own company info
 * {@link /api/users/me/health-info/company-info}
 */
export function useGetMyCompanyInfo<
  TData = GetMyCompanyInfoQueryResponse,
  TQueryData = GetMyCompanyInfoQueryResponse,
  TQueryKey extends QueryKey = GetMyCompanyInfoQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetMyCompanyInfoQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getMyCompanyInfoQueryKey()

  const query = useQuery(
    {
      ...getMyCompanyInfoQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
