/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetCompanyInfoQueryResponse, GetCompanyInfoPathParams } from "../../types/userHealthInfoController/GetCompanyInfo.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getCompanyInfoSuspenseQueryKey = (userId: GetCompanyInfoPathParams["userId"]) => [{ url: '/api/users/:userId/health-info/company-info', params: {userId:userId} }] as const

export type GetCompanyInfoSuspenseQueryKey = ReturnType<typeof getCompanyInfoSuspenseQueryKey>

/**
 * @description Admins can retrieve a user's company information
 * @summary Get user's company info
 * {@link /api/users/:userId/health-info/company-info}
 */
export async function getCompanyInfoSuspense(userId: GetCompanyInfoPathParams["userId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCompanyInfoQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/users/${userId}/health-info/company-info`, ... requestConfig })  
  return res.data
}

export function getCompanyInfoSuspenseQueryOptions(userId: GetCompanyInfoPathParams["userId"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getCompanyInfoSuspenseQueryKey(userId)
  return queryOptions<GetCompanyInfoQueryResponse, ResponseErrorConfig<Error>, GetCompanyInfoQueryResponse, typeof queryKey>({
   enabled: !!(userId),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getCompanyInfoSuspense(userId, config)
   },
  })
}

/**
 * @description Admins can retrieve a user's company information
 * @summary Get user's company info
 * {@link /api/users/:userId/health-info/company-info}
 */
export function useGetCompanyInfoSuspense<TData = GetCompanyInfoQueryResponse, TQueryKey extends QueryKey = GetCompanyInfoSuspenseQueryKey>(userId: GetCompanyInfoPathParams["userId"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetCompanyInfoQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getCompanyInfoSuspenseQueryKey(userId)

  const query = useSuspenseQuery({
   ...getCompanyInfoSuspenseQueryOptions(userId, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}