/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type {
  GetNationalInsuranceQueryResponse,
  GetNationalInsurancePathParams,
} from "../../types/userHealthInfoController/GetNationalInsurance.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getNationalInsuranceSuspenseQueryKey = (
  userId: GetNationalInsurancePathParams["userId"],
) =>
  [
    {
      url: "/api/users/:userId/health-info/national-insurance",
      params: { userId: userId },
    },
  ] as const;

export type GetNationalInsuranceSuspenseQueryKey = ReturnType<
  typeof getNationalInsuranceSuspenseQueryKey
>;

/**
 * @description Admins can retrieve a user's national health insurance information
 * @summary Get user's national health insurance
 * {@link /api/users/:userId/health-info/national-insurance}
 */
export async function getNationalInsuranceSuspense(
  userId: GetNationalInsurancePathParams["userId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetNationalInsuranceQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/api/users/${userId}/health-info/national-insurance`,
    ...requestConfig,
  });
  return res.data;
}

export function getNationalInsuranceSuspenseQueryOptions(
  userId: GetNationalInsurancePathParams["userId"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getNationalInsuranceSuspenseQueryKey(userId);
  return queryOptions<
    GetNationalInsuranceQueryResponse,
    ResponseErrorConfig<Error>,
    GetNationalInsuranceQueryResponse,
    typeof queryKey
  >({
    enabled: !!userId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getNationalInsuranceSuspense(userId, config);
    },
  });
}

/**
 * @description Admins can retrieve a user's national health insurance information
 * @summary Get user's national health insurance
 * {@link /api/users/:userId/health-info/national-insurance}
 */
export function useGetNationalInsuranceSuspense<
  TData = GetNationalInsuranceQueryResponse,
  TQueryKey extends QueryKey = GetNationalInsuranceSuspenseQueryKey,
>(
  userId: GetNationalInsurancePathParams["userId"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetNationalInsuranceQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getNationalInsuranceSuspenseQueryKey(userId);

  const query = useSuspenseQuery(
    {
      ...getNationalInsuranceSuspenseQueryOptions(userId, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
