/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type {
  UpsertMyCompanyInfoMutationRequest,
  UpsertMyCompanyInfoMutationResponse,
} from "../../types/userHealthInfoController/UpsertMyCompanyInfo.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const upsertMyCompanyInfoMutationKey = () =>
  [{ url: "/api/users/me/health-info/company-info" }] as const;

export type UpsertMyCompanyInfoMutationKey = ReturnType<
  typeof upsertMyCompanyInfoMutationKey
>;

/**
 * @description Mobile users can create or update their own company information
 * @summary Upsert own company info
 * {@link /api/users/me/health-info/company-info}
 */
export async function upsertMyCompanyInfo(
  data?: UpsertMyCompanyInfoMutationRequest,
  config: Partial<RequestConfig<UpsertMyCompanyInfoMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    UpsertMyCompanyInfoMutationResponse,
    ResponseErrorConfig<Error>,
    UpsertMyCompanyInfoMutationRequest
  >({
    method: "PUT",
    url: `/api/users/me/health-info/company-info`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function upsertMyCompanyInfoMutationOptions(
  config: Partial<RequestConfig<UpsertMyCompanyInfoMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = upsertMyCompanyInfoMutationKey();
  return mutationOptions<
    UpsertMyCompanyInfoMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: UpsertMyCompanyInfoMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return upsertMyCompanyInfo(data, config);
    },
  });
}

/**
 * @description Mobile users can create or update their own company information
 * @summary Upsert own company info
 * {@link /api/users/me/health-info/company-info}
 */
export function useUpsertMyCompanyInfo<TContext>(
  options: {
    mutation?: UseMutationOptions<
      UpsertMyCompanyInfoMutationResponse,
      ResponseErrorConfig<Error>,
      { data?: UpsertMyCompanyInfoMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<UpsertMyCompanyInfoMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? upsertMyCompanyInfoMutationKey();

  const baseOptions = upsertMyCompanyInfoMutationOptions(
    config,
  ) as UseMutationOptions<
    UpsertMyCompanyInfoMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: UpsertMyCompanyInfoMutationRequest },
    TContext
  >;

  return useMutation<
    UpsertMyCompanyInfoMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: UpsertMyCompanyInfoMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    UpsertMyCompanyInfoMutationResponse,
    ResponseErrorConfig<Error>,
    { data?: UpsertMyCompanyInfoMutationRequest },
    TContext
  >;
}
