/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RehabilitationExaminationFormResponse } from "../RehabilitationExaminationFormResponse.ts";
import type { UpdateRehabilitationExaminationFormRequest } from "../UpdateRehabilitationExaminationFormRequest.ts";

export type UpdateFormPathParams = {
    /**
     * @type integer, int64
    */
    id: number;
};

/**
 * @description OK
*/
export type UpdateForm200 = RehabilitationExaminationFormResponse;

export type UpdateFormMutationRequest = UpdateRehabilitationExaminationFormRequest;

export type UpdateFormMutationResponse = UpdateForm200;

export type UpdateFormMutation = {
    Response: UpdateForm200;
    Request: UpdateFormMutationRequest;
    PathParams: UpdateFormPathParams;
    Errors: any;
};