export type { AssignDoctorMutationKey } from "./useAssignDoctor.ts";
export type { CancelAppointmentMutationKey } from "./useCancelAppointment.ts";
export type { ConfirmAppointmentMutationKey } from "./useConfirmAppointment.ts";
export type { ConfirmCompletionMutationKey } from "./useConfirmCompletion.ts";
export type { CreateAppointmentMutationKey } from "./useCreateAppointment.ts";
export type { DisputeAppointmentMutationKey } from "./useDisputeAppointment.ts";
export type { GetAllAppointmentsQueryKey } from "./useGetAllAppointments.ts";
export type { GetAllAppointmentsSuspenseQueryKey } from "./useGetAllAppointmentsSuspense.ts";
export type { GetAppointmentByIdQueryKey } from "./useGetAppointmentById.ts";
export type { GetAppointmentByIdSuspenseQueryKey } from "./useGetAppointmentByIdSuspense.ts";
export type { GetAvailableSlotsQueryKey } from "./useGetAvailableSlots.ts";
export type { GetAvailableSlotsSuspenseQueryKey } from "./useGetAvailableSlotsSuspense.ts";
export type { GetClinicScheduleQueryKey } from "./useGetClinicSchedule.ts";
export type { GetClinicScheduleSuspenseQueryKey } from "./useGetClinicScheduleSuspense.ts";
export type { GetDisputedAppointmentsQueryKey } from "./useGetDisputedAppointments.ts";
export type { GetDisputedAppointmentsSuspenseQueryKey } from "./useGetDisputedAppointmentsSuspense.ts";
export type { GetDoctorAppointmentsQueryKey } from "./useGetDoctorAppointments.ts";
export type { GetDoctorAppointmentsSuspenseQueryKey } from "./useGetDoctorAppointmentsSuspense.ts";
export type { GetMyAppointmentsQueryKey } from "./useGetMyAppointments.ts";
export type { GetMyAppointmentsSuspenseQueryKey } from "./useGetMyAppointmentsSuspense.ts";
export type { GetVideoTokenQueryKey } from "./useGetVideoToken.ts";
export type { GetVideoTokenSuspenseQueryKey } from "./useGetVideoTokenSuspense.ts";
export type { MarkCompleteMutationKey } from "./useMarkComplete.ts";
export type { RejectAppointmentMutationKey } from "./useRejectAppointment.ts";
export type { ResolveDisputeMutationKey } from "./useResolveDispute.ts";
export type { UpdateClinicScheduleMutationKey } from "./useUpdateClinicSchedule.ts";
export { assignDoctorMutationKey } from "./useAssignDoctor.ts";
export { assignDoctor } from "./useAssignDoctor.ts";
export { assignDoctorMutationOptions } from "./useAssignDoctor.ts";
export { useAssignDoctor } from "./useAssignDoctor.ts";
export { cancelAppointmentMutationKey } from "./useCancelAppointment.ts";
export { cancelAppointment } from "./useCancelAppointment.ts";
export { cancelAppointmentMutationOptions } from "./useCancelAppointment.ts";
export { useCancelAppointment } from "./useCancelAppointment.ts";
export { confirmAppointmentMutationKey } from "./useConfirmAppointment.ts";
export { confirmAppointment } from "./useConfirmAppointment.ts";
export { confirmAppointmentMutationOptions } from "./useConfirmAppointment.ts";
export { useConfirmAppointment } from "./useConfirmAppointment.ts";
export { confirmCompletionMutationKey } from "./useConfirmCompletion.ts";
export { confirmCompletion } from "./useConfirmCompletion.ts";
export { confirmCompletionMutationOptions } from "./useConfirmCompletion.ts";
export { useConfirmCompletion } from "./useConfirmCompletion.ts";
export { createAppointmentMutationKey } from "./useCreateAppointment.ts";
export { createAppointment } from "./useCreateAppointment.ts";
export { createAppointmentMutationOptions } from "./useCreateAppointment.ts";
export { useCreateAppointment } from "./useCreateAppointment.ts";
export { disputeAppointmentMutationKey } from "./useDisputeAppointment.ts";
export { disputeAppointment } from "./useDisputeAppointment.ts";
export { disputeAppointmentMutationOptions } from "./useDisputeAppointment.ts";
export { useDisputeAppointment } from "./useDisputeAppointment.ts";
export { getAllAppointmentsQueryKey } from "./useGetAllAppointments.ts";
export { getAllAppointments } from "./useGetAllAppointments.ts";
export { getAllAppointmentsQueryOptions } from "./useGetAllAppointments.ts";
export { useGetAllAppointments } from "./useGetAllAppointments.ts";
export { getAllAppointmentsSuspenseQueryKey } from "./useGetAllAppointmentsSuspense.ts";
export { getAllAppointmentsSuspense } from "./useGetAllAppointmentsSuspense.ts";
export { getAllAppointmentsSuspenseQueryOptions } from "./useGetAllAppointmentsSuspense.ts";
export { useGetAllAppointmentsSuspense } from "./useGetAllAppointmentsSuspense.ts";
export { getAppointmentByIdQueryKey } from "./useGetAppointmentById.ts";
export { getAppointmentById } from "./useGetAppointmentById.ts";
export { getAppointmentByIdQueryOptions } from "./useGetAppointmentById.ts";
export { useGetAppointmentById } from "./useGetAppointmentById.ts";
export { getAppointmentByIdSuspenseQueryKey } from "./useGetAppointmentByIdSuspense.ts";
export { getAppointmentByIdSuspense } from "./useGetAppointmentByIdSuspense.ts";
export { getAppointmentByIdSuspenseQueryOptions } from "./useGetAppointmentByIdSuspense.ts";
export { useGetAppointmentByIdSuspense } from "./useGetAppointmentByIdSuspense.ts";
export { getAvailableSlotsQueryKey } from "./useGetAvailableSlots.ts";
export { getAvailableSlots } from "./useGetAvailableSlots.ts";
export { getAvailableSlotsQueryOptions } from "./useGetAvailableSlots.ts";
export { useGetAvailableSlots } from "./useGetAvailableSlots.ts";
export { getAvailableSlotsSuspenseQueryKey } from "./useGetAvailableSlotsSuspense.ts";
export { getAvailableSlotsSuspense } from "./useGetAvailableSlotsSuspense.ts";
export { getAvailableSlotsSuspenseQueryOptions } from "./useGetAvailableSlotsSuspense.ts";
export { useGetAvailableSlotsSuspense } from "./useGetAvailableSlotsSuspense.ts";
export { getClinicScheduleQueryKey } from "./useGetClinicSchedule.ts";
export { getClinicSchedule } from "./useGetClinicSchedule.ts";
export { getClinicScheduleQueryOptions } from "./useGetClinicSchedule.ts";
export { useGetClinicSchedule } from "./useGetClinicSchedule.ts";
export { getClinicScheduleSuspenseQueryKey } from "./useGetClinicScheduleSuspense.ts";
export { getClinicScheduleSuspense } from "./useGetClinicScheduleSuspense.ts";
export { getClinicScheduleSuspenseQueryOptions } from "./useGetClinicScheduleSuspense.ts";
export { useGetClinicScheduleSuspense } from "./useGetClinicScheduleSuspense.ts";
export { getDisputedAppointmentsQueryKey } from "./useGetDisputedAppointments.ts";
export { getDisputedAppointments } from "./useGetDisputedAppointments.ts";
export { getDisputedAppointmentsQueryOptions } from "./useGetDisputedAppointments.ts";
export { useGetDisputedAppointments } from "./useGetDisputedAppointments.ts";
export { getDisputedAppointmentsSuspenseQueryKey } from "./useGetDisputedAppointmentsSuspense.ts";
export { getDisputedAppointmentsSuspense } from "./useGetDisputedAppointmentsSuspense.ts";
export { getDisputedAppointmentsSuspenseQueryOptions } from "./useGetDisputedAppointmentsSuspense.ts";
export { useGetDisputedAppointmentsSuspense } from "./useGetDisputedAppointmentsSuspense.ts";
export { getDoctorAppointmentsQueryKey } from "./useGetDoctorAppointments.ts";
export { getDoctorAppointments } from "./useGetDoctorAppointments.ts";
export { getDoctorAppointmentsQueryOptions } from "./useGetDoctorAppointments.ts";
export { useGetDoctorAppointments } from "./useGetDoctorAppointments.ts";
export { getDoctorAppointmentsSuspenseQueryKey } from "./useGetDoctorAppointmentsSuspense.ts";
export { getDoctorAppointmentsSuspense } from "./useGetDoctorAppointmentsSuspense.ts";
export { getDoctorAppointmentsSuspenseQueryOptions } from "./useGetDoctorAppointmentsSuspense.ts";
export { useGetDoctorAppointmentsSuspense } from "./useGetDoctorAppointmentsSuspense.ts";
export { getMyAppointmentsQueryKey } from "./useGetMyAppointments.ts";
export { getMyAppointments } from "./useGetMyAppointments.ts";
export { getMyAppointmentsQueryOptions } from "./useGetMyAppointments.ts";
export { useGetMyAppointments } from "./useGetMyAppointments.ts";
export { getMyAppointmentsSuspenseQueryKey } from "./useGetMyAppointmentsSuspense.ts";
export { getMyAppointmentsSuspense } from "./useGetMyAppointmentsSuspense.ts";
export { getMyAppointmentsSuspenseQueryOptions } from "./useGetMyAppointmentsSuspense.ts";
export { useGetMyAppointmentsSuspense } from "./useGetMyAppointmentsSuspense.ts";
export { getVideoTokenQueryKey } from "./useGetVideoToken.ts";
export { getVideoToken } from "./useGetVideoToken.ts";
export { getVideoTokenQueryOptions } from "./useGetVideoToken.ts";
export { useGetVideoToken } from "./useGetVideoToken.ts";
export { getVideoTokenSuspenseQueryKey } from "./useGetVideoTokenSuspense.ts";
export { getVideoTokenSuspense } from "./useGetVideoTokenSuspense.ts";
export { getVideoTokenSuspenseQueryOptions } from "./useGetVideoTokenSuspense.ts";
export { useGetVideoTokenSuspense } from "./useGetVideoTokenSuspense.ts";
export { markCompleteMutationKey } from "./useMarkComplete.ts";
export { markComplete } from "./useMarkComplete.ts";
export { markCompleteMutationOptions } from "./useMarkComplete.ts";
export { useMarkComplete } from "./useMarkComplete.ts";
export { rejectAppointmentMutationKey } from "./useRejectAppointment.ts";
export { rejectAppointment } from "./useRejectAppointment.ts";
export { rejectAppointmentMutationOptions } from "./useRejectAppointment.ts";
export { useRejectAppointment } from "./useRejectAppointment.ts";
export { resolveDisputeMutationKey } from "./useResolveDispute.ts";
export { resolveDispute } from "./useResolveDispute.ts";
export { resolveDisputeMutationOptions } from "./useResolveDispute.ts";
export { useResolveDispute } from "./useResolveDispute.ts";
export { updateClinicScheduleMutationKey } from "./useUpdateClinicSchedule.ts";
export { updateClinicSchedule } from "./useUpdateClinicSchedule.ts";
export { updateClinicScheduleMutationOptions } from "./useUpdateClinicSchedule.ts";
export { useUpdateClinicSchedule } from "./useUpdateClinicSchedule.ts";
