/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/api-client'
import type {
  GetAppointmentsByUserQueryResponse,
  GetAppointmentsByUserPathParams,
  GetAppointmentsByUserQueryParams,
} from '../../types/appointmentsController/GetAppointmentsByUser.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/api-client'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getAppointmentsByUserQueryKey = (
  userId: GetAppointmentsByUserPathParams['userId'],
  params: GetAppointmentsByUserQueryParams
) =>
  [
    { url: '/api/appointments/admin/user/:userId', params: { userId: userId } },
    ...(params ? [params] : []),
  ] as const

export type GetAppointmentsByUserQueryKey = ReturnType<
  typeof getAppointmentsByUserQueryKey
>

/**
 * @description Admin views all appointments for a specific user
 * @summary Get appointments by user
 * {@link /api/appointments/admin/user/:userId}
 */
export async function getAppointmentsByUser(
  userId: GetAppointmentsByUserPathParams['userId'],
  params: GetAppointmentsByUserQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetAppointmentsByUserQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: `/api/appointments/admin/user/${userId}`,
    params,
    ...requestConfig,
  })
  return res.data
}

export function getAppointmentsByUserQueryOptions(
  userId: GetAppointmentsByUserPathParams['userId'],
  params: GetAppointmentsByUserQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = getAppointmentsByUserQueryKey(userId, params)
  return queryOptions<
    GetAppointmentsByUserQueryResponse,
    ResponseErrorConfig<Error>,
    GetAppointmentsByUserQueryResponse,
    typeof queryKey
  >({
    enabled: !!(userId && params),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getAppointmentsByUser(userId, params, config)
    },
  })
}

/**
 * @description Admin views all appointments for a specific user
 * @summary Get appointments by user
 * {@link /api/appointments/admin/user/:userId}
 */
export function useGetAppointmentsByUser<
  TData = GetAppointmentsByUserQueryResponse,
  TQueryData = GetAppointmentsByUserQueryResponse,
  TQueryKey extends QueryKey = GetAppointmentsByUserQueryKey,
>(
  userId: GetAppointmentsByUserPathParams['userId'],
  params: GetAppointmentsByUserQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetAppointmentsByUserQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey =
    queryOptions?.queryKey ?? getAppointmentsByUserQueryKey(userId, params)

  const query = useQuery(
    {
      ...getAppointmentsByUserQueryOptions(userId, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
