/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type {
  GetMyAppointmentsQueryResponse,
  GetMyAppointmentsQueryParams,
} from "../../types/appointmentsController/GetMyAppointments.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getMyAppointmentsSuspenseQueryKey = (
  params: GetMyAppointmentsQueryParams,
) =>
  [
    { url: "/api/appointments/my-appointments" },
    ...(params ? [params] : []),
  ] as const;

export type GetMyAppointmentsSuspenseQueryKey = ReturnType<
  typeof getMyAppointmentsSuspenseQueryKey
>;

/**
 * @description List all appointments for the authenticated patient
 * @summary Get my appointments
 * {@link /api/appointments/my-appointments}
 */
export async function getMyAppointmentsSuspense(
  params: GetMyAppointmentsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetMyAppointmentsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/api/appointments/my-appointments`,
    params,
    ...requestConfig,
  });
  return res.data;
}

export function getMyAppointmentsSuspenseQueryOptions(
  params: GetMyAppointmentsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getMyAppointmentsSuspenseQueryKey(params);
  return queryOptions<
    GetMyAppointmentsQueryResponse,
    ResponseErrorConfig<Error>,
    GetMyAppointmentsQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getMyAppointmentsSuspense(params, config);
    },
  });
}

/**
 * @description List all appointments for the authenticated patient
 * @summary Get my appointments
 * {@link /api/appointments/my-appointments}
 */
export function useGetMyAppointmentsSuspense<
  TData = GetMyAppointmentsQueryResponse,
  TQueryKey extends QueryKey = GetMyAppointmentsSuspenseQueryKey,
>(
  params: GetMyAppointmentsQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetMyAppointmentsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getMyAppointmentsSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getMyAppointmentsSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
