/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type {
  GetVideoTokenQueryResponse,
  GetVideoTokenPathParams,
} from "../../types/appointmentsController/GetVideoToken.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getVideoTokenSuspenseQueryKey = (
  id: GetVideoTokenPathParams["id"],
) =>
  [{ url: "/api/appointments/:id/video-token", params: { id: id } }] as const;

export type GetVideoTokenSuspenseQueryKey = ReturnType<
  typeof getVideoTokenSuspenseQueryKey
>;

/**
 * @description Generate an Agora RTC token for a confirmed appointment's video call
 * @summary Get video call token
 * {@link /api/appointments/:id/video-token}
 */
export async function getVideoTokenSuspense(
  id: GetVideoTokenPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetVideoTokenQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: `/api/appointments/${id}/video-token`,
    ...requestConfig,
  });
  return res.data;
}

export function getVideoTokenSuspenseQueryOptions(
  id: GetVideoTokenPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getVideoTokenSuspenseQueryKey(id);
  return queryOptions<
    GetVideoTokenQueryResponse,
    ResponseErrorConfig<Error>,
    GetVideoTokenQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getVideoTokenSuspense(id, config);
    },
  });
}

/**
 * @description Generate an Agora RTC token for a confirmed appointment's video call
 * @summary Get video call token
 * {@link /api/appointments/:id/video-token}
 */
export function useGetVideoTokenSuspense<
  TData = GetVideoTokenQueryResponse,
  TQueryKey extends QueryKey = GetVideoTokenSuspenseQueryKey,
>(
  id: GetVideoTokenPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetVideoTokenQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getVideoTokenSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getVideoTokenSuspenseQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
