/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetAllAppointmentsQueryResponse, GetAllAppointmentsQueryParams } from "../../types/appointmentsController/GetAllAppointments.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getAllAppointmentsQueryKey = (params: GetAllAppointmentsQueryParams) => [{ url: '/api/appointments/admin/all' }, ...(params ? [params] : [])] as const

export type GetAllAppointmentsQueryKey = ReturnType<typeof getAllAppointmentsQueryKey>

/**
 * @description Admin views all appointments in the system
 * @summary Get all appointments
 * {@link /api/appointments/admin/all}
 */
export async function getAllAppointments(params: GetAllAppointmentsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetAllAppointmentsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/appointments/admin/all`, params, ... requestConfig })  
  return res.data
}

export function getAllAppointmentsQueryOptions(params: GetAllAppointmentsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getAllAppointmentsQueryKey(params)
  return queryOptions<GetAllAppointmentsQueryResponse, ResponseErrorConfig<Error>, GetAllAppointmentsQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getAllAppointments(params, config)
   },
  })
}

/**
 * @description Admin views all appointments in the system
 * @summary Get all appointments
 * {@link /api/appointments/admin/all}
 */
export function useGetAllAppointments<TData = GetAllAppointmentsQueryResponse, TQueryData = GetAllAppointmentsQueryResponse, TQueryKey extends QueryKey = GetAllAppointmentsQueryKey>(params: GetAllAppointmentsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetAllAppointmentsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getAllAppointmentsQueryKey(params)

  const query = useQuery({
   ...getAllAppointmentsQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}