/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetDoctorAppointmentsQueryResponse, GetDoctorAppointmentsQueryParams } from "../../types/appointmentsController/GetDoctorAppointments.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getDoctorAppointmentsQueryKey = (params: GetDoctorAppointmentsQueryParams) => [{ url: '/api/appointments/doctor/my-appointments' }, ...(params ? [params] : [])] as const

export type GetDoctorAppointmentsQueryKey = ReturnType<typeof getDoctorAppointmentsQueryKey>

/**
 * @description List all appointments assigned to the authenticated doctor
 * @summary Get doctor's appointments
 * {@link /api/appointments/doctor/my-appointments}
 */
export async function getDoctorAppointments(params: GetDoctorAppointmentsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetDoctorAppointmentsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/appointments/doctor/my-appointments`, params, ... requestConfig })  
  return res.data
}

export function getDoctorAppointmentsQueryOptions(params: GetDoctorAppointmentsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getDoctorAppointmentsQueryKey(params)
  return queryOptions<GetDoctorAppointmentsQueryResponse, ResponseErrorConfig<Error>, GetDoctorAppointmentsQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getDoctorAppointments(params, config)
   },
  })
}

/**
 * @description List all appointments assigned to the authenticated doctor
 * @summary Get doctor's appointments
 * {@link /api/appointments/doctor/my-appointments}
 */
export function useGetDoctorAppointments<TData = GetDoctorAppointmentsQueryResponse, TQueryData = GetDoctorAppointmentsQueryResponse, TQueryKey extends QueryKey = GetDoctorAppointmentsQueryKey>(params: GetDoctorAppointmentsQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<GetDoctorAppointmentsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getDoctorAppointmentsQueryKey(params)

  const query = useQuery({
   ...getDoctorAppointmentsQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}