/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/api-client'
import type {
  GetAppointmentsByUserQueryResponse,
  GetAppointmentsByUserPathParams,
  GetAppointmentsByUserQueryParams,
} from '../../types/appointmentsController/GetAppointmentsByUser.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/api-client'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getAppointmentsByUserSuspenseQueryKey = (
  userId: GetAppointmentsByUserPathParams['userId'],
  params: GetAppointmentsByUserQueryParams
) =>
  [
    { url: '/api/appointments/admin/user/:userId', params: { userId: userId } },
    ...(params ? [params] : []),
  ] as const

export type GetAppointmentsByUserSuspenseQueryKey = ReturnType<
  typeof getAppointmentsByUserSuspenseQueryKey
>

/**
 * @description Admin views all appointments for a specific user
 * @summary Get appointments by user
 * {@link /api/appointments/admin/user/:userId}
 */
export async function getAppointmentsByUserSuspense(
  userId: GetAppointmentsByUserPathParams['userId'],
  params: GetAppointmentsByUserQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetAppointmentsByUserQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: 'GET',
    url: `/api/appointments/admin/user/${userId}`,
    params,
    ...requestConfig,
  })
  return res.data
}

export function getAppointmentsByUserSuspenseQueryOptions(
  userId: GetAppointmentsByUserPathParams['userId'],
  params: GetAppointmentsByUserQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = getAppointmentsByUserSuspenseQueryKey(userId, params)
  return queryOptions<
    GetAppointmentsByUserQueryResponse,
    ResponseErrorConfig<Error>,
    GetAppointmentsByUserQueryResponse,
    typeof queryKey
  >({
    enabled: !!(userId && params),
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getAppointmentsByUserSuspense(userId, params, config)
    },
  })
}

/**
 * @description Admin views all appointments for a specific user
 * @summary Get appointments by user
 * {@link /api/appointments/admin/user/:userId}
 */
export function useGetAppointmentsByUserSuspense<
  TData = GetAppointmentsByUserQueryResponse,
  TQueryKey extends QueryKey = GetAppointmentsByUserSuspenseQueryKey,
>(
  userId: GetAppointmentsByUserPathParams['userId'],
  params: GetAppointmentsByUserQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetAppointmentsByUserQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey =
    queryOptions?.queryKey ??
    getAppointmentsByUserSuspenseQueryKey(userId, params)

  const query = useSuspenseQuery(
    {
      ...getAppointmentsByUserSuspenseQueryOptions(userId, params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
