/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetDisputedAppointmentsQueryResponse, GetDisputedAppointmentsQueryParams } from "../../types/appointmentsController/GetDisputedAppointments.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getDisputedAppointmentsSuspenseQueryKey = (params: GetDisputedAppointmentsQueryParams) => [{ url: '/api/appointments/admin/disputed' }, ...(params ? [params] : [])] as const

export type GetDisputedAppointmentsSuspenseQueryKey = ReturnType<typeof getDisputedAppointmentsSuspenseQueryKey>

/**
 * @description Admin views all disputed appointments
 * @summary Get disputed appointments
 * {@link /api/appointments/admin/disputed}
 */
export async function getDisputedAppointmentsSuspense(params: GetDisputedAppointmentsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetDisputedAppointmentsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/api/appointments/admin/disputed`, params, ... requestConfig })  
  return res.data
}

export function getDisputedAppointmentsSuspenseQueryOptions(params: GetDisputedAppointmentsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getDisputedAppointmentsSuspenseQueryKey(params)
  return queryOptions<GetDisputedAppointmentsQueryResponse, ResponseErrorConfig<Error>, GetDisputedAppointmentsQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getDisputedAppointmentsSuspense(params, config)
   },
  })
}

/**
 * @description Admin views all disputed appointments
 * @summary Get disputed appointments
 * {@link /api/appointments/admin/disputed}
 */
export function useGetDisputedAppointmentsSuspense<TData = GetDisputedAppointmentsQueryResponse, TQueryKey extends QueryKey = GetDisputedAppointmentsSuspenseQueryKey>(params: GetDisputedAppointmentsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetDisputedAppointmentsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getDisputedAppointmentsSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getDisputedAppointmentsSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}