/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from '@/lib/api-client'
import type {
  GetAuditLogsQueryResponse,
  GetAuditLogsQueryParams,
} from '../../types/auditLogsController/GetAuditLogs.ts'
import type { RequestConfig, ResponseErrorConfig } from '@/lib/api-client'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getAuditLogsQueryKey = (params: GetAuditLogsQueryParams) =>
  [{ url: '/api/admin/audit-logs' }, ...(params ? [params] : [])] as const

export type GetAuditLogsQueryKey = ReturnType<typeof getAuditLogsQueryKey>

/**
 * @description Query audit logs with optional filters
 * @summary Search audit logs
 * {@link /api/admin/audit-logs}
 */
export async function getAuditLogs(
  params: GetAuditLogsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<
    GetAuditLogsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: 'GET', url: `/api/admin/audit-logs`, params, ...requestConfig })
  return res.data
}

export function getAuditLogsQueryOptions(
  params: GetAuditLogsQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {}
) {
  const queryKey = getAuditLogsQueryKey(params)
  return queryOptions<
    GetAuditLogsQueryResponse,
    ResponseErrorConfig<Error>,
    GetAuditLogsQueryResponse,
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getAuditLogs(params, config)
    },
  })
}

/**
 * @description Query audit logs with optional filters
 * @summary Search audit logs
 * {@link /api/admin/audit-logs}
 */
export function useGetAuditLogs<
  TData = GetAuditLogsQueryResponse,
  TQueryData = GetAuditLogsQueryResponse,
  TQueryKey extends QueryKey = GetAuditLogsQueryKey,
>(
  params: GetAuditLogsQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetAuditLogsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof fetch }
  } = {}
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getAuditLogsQueryKey(params)

  const query = useQuery(
    {
      ...getAuditLogsQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey
  }

  query.queryKey = queryKey as TQueryKey

  return query
}
