/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetCategoriesByTypeQueryResponse, GetCategoriesByTypePathParams } from "../../types/GetCategoriesByType.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetCategoriesByTypeUrl(type: GetCategoriesByTypePathParams["type"]) {
  const res = { method: 'GET', url: `/api/exercise-categories/type/${type}` as const }  
  return res
}

/**
 * @description Retrieve all exercise categories of a specific type
 * @summary Get exercise categories by type
 * {@link /api/exercise-categories/type/:type}
 */
export async function getCategoriesByType(type: GetCategoriesByTypePathParams["type"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCategoriesByTypeQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetCategoriesByTypeUrl(type).url.toString(), ... requestConfig })  
  return res.data
}