/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { SearchCategoriesQueryResponse, SearchCategoriesQueryParams } from "../../types/SearchCategories.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getSearchCategoriesUrl() {
  const res = { method: 'GET', url: `/api/exercise-categories/search` as const }  
  return res
}

/**
 * @description Search exercise categories by keyword in name
 * @summary Search exercise categories
 * {@link /api/exercise-categories/search}
 */
export async function searchCategories(params: SearchCategoriesQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<SearchCategoriesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getSearchCategoriesUrl().url.toString(), params, ... requestConfig })  
  return res.data
}