/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { DeleteMyCompanyInfoMutationResponse } from "../../types/DeleteMyCompanyInfo.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getDeleteMyCompanyInfoUrl() {
  const res = { method: 'DELETE', url: `/api/users/me/company-info` as const }  
  return res
}

/**
 * @description Delete your own company information
 * @summary Delete my company information
 * {@link /api/users/me/company-info}
 */
export async function deleteMyCompanyInfo(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteMyCompanyInfoMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : getDeleteMyCompanyInfoUrl().url.toString(), ... requestConfig })  
  return res.data
}