/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetMyNationalHealthInsuranceQueryResponse } from "../../types/GetMyNationalHealthInsurance.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetMyNationalHealthInsuranceUrl() {
  const res = { method: 'GET', url: `/api/users/me/national-health-insurance` as const }  
  return res
}

/**
 * @description Retrieve your own national health insurance information
 * @summary Get my national health insurance
 * {@link /api/users/me/national-health-insurance}
 */
export async function getMyNationalHealthInsurance(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetMyNationalHealthInsuranceQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetMyNationalHealthInsuranceUrl().url.toString(), ... requestConfig })  
  return res.data
}