/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { UpdateMyNationalHealthInsuranceMutationRequest, UpdateMyNationalHealthInsuranceMutationResponse } from "../../types/UpdateMyNationalHealthInsurance.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getUpdateMyNationalHealthInsuranceUrl() {
  const res = { method: 'PUT', url: `/api/users/me/national-health-insurance` as const }  
  return res
}

/**
 * @description Create or update your own national health insurance information
 * @summary Update my national health insurance
 * {@link /api/users/me/national-health-insurance}
 */
export async function updateMyNationalHealthInsurance(data?: UpdateMyNationalHealthInsuranceMutationRequest, config: Partial<RequestConfig<UpdateMyNationalHealthInsuranceMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateMyNationalHealthInsuranceMutationResponse, ResponseErrorConfig<Error>, UpdateMyNationalHealthInsuranceMutationRequest>({ method : "PUT", url : getUpdateMyNationalHealthInsuranceUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}