/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { UpdateMyBasicInfoMutationRequest, UpdateMyBasicInfoMutationResponse } from "../../types/UpdateMyBasicInfo.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getUpdateMyBasicInfoUrl() {
  const res = { method: 'PUT', url: `/api/users/me/basic-info` as const }  
  return res
}

/**
 * @description Update your own basic information (name, email, gender, date of birth)
 * @summary Update my basic info
 * {@link /api/users/me/basic-info}
 */
export async function updateMyBasicInfo(data?: UpdateMyBasicInfoMutationRequest, config: Partial<RequestConfig<UpdateMyBasicInfoMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<UpdateMyBasicInfoMutationResponse, ResponseErrorConfig<Error>, UpdateMyBasicInfoMutationRequest>({ method : "PUT", url : getUpdateMyBasicInfoUrl().url.toString(), data : requestData, ... requestConfig })  
  return res.data
}