/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { createDiscountRequestSchema } from "../createDiscountRequestSchema.ts";
import { discountResponseSchema } from "../discountResponseSchema.ts";
import { z } from "zod/v4";

/**
 * @description OK
 */
export const create200Schema = z.lazy(() => discountResponseSchema)

export const createMutationRequestSchema = z.lazy(() => createDiscountRequestSchema)

export const createMutationResponseSchema = z.lazy(() => create200Schema)