/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { pageableSchema } from "../pageableSchema.ts";
import { pagedModelSchema } from "../pagedModelSchema.ts";
import { z } from "zod/v4";

export const listCourseAssignmentsQueryParamsSchema = z.object({
    "patientId": z.optional(z.coerce.number().int().describe("Filter by patient ID")),
"patientName": z.optional(z.string().describe("Search by patient name (case-insensitive, partial match)")),
"courseId": z.optional(z.coerce.number().int().describe("Filter by course ID")),
"doctorId": z.optional(z.coerce.number().int().describe("Filter by assigning doctor ID (ADMIN/SUPER_ADMIN only)")),
"includeRevoked": z.optional(z.boolean().default(false).describe("Include revoked assignments (default: false)")),
"purchaseStatus": z.optional(z.enum(["PENDING_PURCHASE", "PURCHASED", "EXPIRED"]).describe("Filter by purchase status (PENDING_PURCHASE, PURCHASED, EXPIRED)")),
"startDate": z.optional(z.string().datetime().describe("Filter assignments from date (ISO format: yyyy-MM-dd'T'HH:mm:ss)")),
"endDate": z.optional(z.string().datetime().describe("Filter assignments to date (ISO format: yyyy-MM-dd'T'HH:mm:ss)")),
get "pageable"(){
                return pageableSchema
              }
    })

/**
 * @description OK
 */
export const listCourseAssignments200Schema = z.lazy(() => pagedModelSchema)

export const listCourseAssignmentsQueryResponseSchema = z.lazy(() => listCourseAssignments200Schema)