/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import type {
  CheckPhoneMutationRequest,
  CheckPhoneMutationResponse,
} from "../../types/authenticationController/CheckPhone.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const checkPhoneMutationKey = () =>
  [{ url: "/api/auth/user/check-phone" }] as const;

export type CheckPhoneMutationKey = ReturnType<typeof checkPhoneMutationKey>;

/**
 * @description Verify if a phone number is already registered in the system
 * @summary Check if phone number exists
 * {@link /api/auth/user/check-phone}
 */
export async function checkPhone(
  data: CheckPhoneMutationRequest,
  config: Partial<RequestConfig<CheckPhoneMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    CheckPhoneMutationResponse,
    ResponseErrorConfig<Error>,
    CheckPhoneMutationRequest
  >({
    method: "POST",
    url: `/api/auth/user/check-phone`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function checkPhoneMutationOptions(
  config: Partial<RequestConfig<CheckPhoneMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = checkPhoneMutationKey();
  return mutationOptions<
    CheckPhoneMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CheckPhoneMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return checkPhone(data, config);
    },
  });
}

/**
 * @description Verify if a phone number is already registered in the system
 * @summary Check if phone number exists
 * {@link /api/auth/user/check-phone}
 */
export function useCheckPhone<TContext>(
  options: {
    mutation?: UseMutationOptions<
      CheckPhoneMutationResponse,
      ResponseErrorConfig<Error>,
      { data: CheckPhoneMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<CheckPhoneMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? checkPhoneMutationKey();

  const baseOptions = checkPhoneMutationOptions(config) as UseMutationOptions<
    CheckPhoneMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CheckPhoneMutationRequest },
    TContext
  >;

  return useMutation<
    CheckPhoneMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CheckPhoneMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    CheckPhoneMutationResponse,
    ResponseErrorConfig<Error>,
    { data: CheckPhoneMutationRequest },
    TContext
  >;
}
