/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { RegisterMutationRequest, RegisterMutationResponse } from "../../types/authenticationController/Register.ts";
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from "@/lib/api-client";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { register } from "../../clients/authenticationController/register.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const registerMutationKey = () => [{ url: '/api/auth/user/register' }] as const

export type RegisterMutationKey = ReturnType<typeof registerMutationKey>

export function registerMutationOptions(config: Partial<RequestConfig<RegisterMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = registerMutationKey()
  return mutationOptions<ResponseConfig<RegisterMutationResponse>, ResponseErrorConfig<Error>, {data: RegisterMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return register(data, config)
    },
  })
}

/**
 * @description Register a new mobile user with OTP verification and 6-digit PIN
 * @summary Register mobile user
 * {@link /api/auth/user/register}
 */
export function useRegister<TContext>(options: 
{
  mutation?: UseMutationOptions<ResponseConfig<RegisterMutationResponse>, ResponseErrorConfig<Error>, {data: RegisterMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<RegisterMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? registerMutationKey()

  const baseOptions = registerMutationOptions(config) as UseMutationOptions<ResponseConfig<RegisterMutationResponse>, ResponseErrorConfig<Error>, {data: RegisterMutationRequest}, TContext>

  return useMutation<ResponseConfig<RegisterMutationResponse>, ResponseErrorConfig<Error>, {data: RegisterMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResponseConfig<RegisterMutationResponse>, ResponseErrorConfig<Error>, {data: RegisterMutationRequest}, TContext>
}