/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetAllCategories1QueryResponse } from "../../types/GetAllCategories1.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetAllCategories1Url() {
  const res = { method: 'GET', url: `/api/course-categories` as const }  
  return res
}

/**
 * @description Retrieve a list of all active course categories
 * @summary Get all active course categories
 * {@link /api/course-categories}
 */
export async function getAllCategories1(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetAllCategories1QueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetAllCategories1Url().url.toString(), ... requestConfig })  
  return res.data
}