/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@/lib/api-client";
import type { GetCategoryById1QueryResponse, GetCategoryById1PathParams } from "../../types/GetCategoryById1.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";

function getGetCategoryById1Url(id: GetCategoryById1PathParams["id"]) {
  const res = { method: 'GET', url: `/api/course-categories/${id}` as const }  
  return res
}

/**
 * @description Retrieve a specific course category by its ID
 * @summary Get course category by ID
 * {@link /api/course-categories/:id}
 */
export async function getCategoryById1(id: GetCategoryById1PathParams["id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCategoryById1QueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetCategoryById1Url(id).url.toString(), ... requestConfig })  
  return res.data
}