/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { courseProgressHistoryResponseSchema } from "../courseProgressHistoryResponseSchema.ts";
import { z } from "zod/v4";

export const getCourseProgressHistoryPathParamsSchema = z.object({
  courseId: z.coerce.number().int().describe("Course ID to get history for"),
});

/**
 * @description OK
 */
export const getCourseProgressHistory200Schema = z.array(
  z.lazy(() => courseProgressHistoryResponseSchema),
);

export const getCourseProgressHistoryQueryResponseSchema = z.lazy(
  () => getCourseProgressHistory200Schema,
);
