/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { appointmentStatsResponseSchema } from "../appointmentStatsResponseSchema.ts";
import { z } from "zod/v4";

export const getAppointmentStatsQueryParamsSchema = z.object({
    "groupBy": z.string().default("day").describe("Time grouping: day or week (default: day)"),
"start": z.optional(z.string().datetime().describe("Start of date range (ISO date-time, defaults to 30 days ago)")),
"end": z.optional(z.string().datetime().describe("End of date range (ISO date-time, defaults to now)"))
    })

/**
 * @description OK
 */
export const getAppointmentStats200Schema = z.lazy(() => appointmentStatsResponseSchema)

export const getAppointmentStatsQueryResponseSchema = z.lazy(() => getAppointmentStats200Schema)