/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { lowEffortPatientResponseSchema } from "../lowEffortPatientResponseSchema.ts";
import { z } from "zod/v4";

export const getLowEffortPatientsQueryParamsSchema = z.object({
  threshold: z.coerce
    .number()
    .int()
    .default(50)
    .describe(
      "Effort percentage threshold (default: 50). Patients below this value are included.",
    ),
});

/**
 * @description OK
 */
export const getLowEffortPatients200Schema = z.array(
  z.lazy(() => lowEffortPatientResponseSchema),
);

export const getLowEffortPatientsQueryResponseSchema = z.lazy(
  () => getLowEffortPatients200Schema,
);
