/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@/lib/api-client";
import type {
  DeleteFileMutationRequest,
  DeleteFileMutationResponse,
} from "../../types/fileManagementController/DeleteFile.ts";
import type { RequestConfig, ResponseErrorConfig } from "@/lib/api-client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteFileMutationKey = () => [{ url: "/api/files" }] as const;

export type DeleteFileMutationKey = ReturnType<typeof deleteFileMutationKey>;

/**
 * @description Delete a file from MinIO storage. Requires SUPER_ADMIN, ADMIN or DOCTOR role.
 * @summary Delete a file
 * {@link /api/files}
 */
export async function deleteFile(
  data: DeleteFileMutationRequest,
  config: Partial<RequestConfig<DeleteFileMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    DeleteFileMutationResponse,
    ResponseErrorConfig<Error>,
    DeleteFileMutationRequest
  >({
    method: "DELETE",
    url: `/api/files`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function deleteFileMutationOptions(
  config: Partial<RequestConfig<DeleteFileMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = deleteFileMutationKey();
  return mutationOptions<
    DeleteFileMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DeleteFileMutationRequest },
    typeof mutationKey
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return deleteFile(data, config);
    },
  });
}

/**
 * @description Delete a file from MinIO storage. Requires SUPER_ADMIN, ADMIN or DOCTOR role.
 * @summary Delete a file
 * {@link /api/files}
 */
export function useDeleteFile<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteFileMutationResponse,
      ResponseErrorConfig<Error>,
      { data: DeleteFileMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<DeleteFileMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteFileMutationKey();

  const baseOptions = deleteFileMutationOptions(config) as UseMutationOptions<
    DeleteFileMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DeleteFileMutationRequest },
    TContext
  >;

  return useMutation<
    DeleteFileMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DeleteFileMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteFileMutationResponse,
    ResponseErrorConfig<Error>,
    { data: DeleteFileMutationRequest },
    TContext
  >;
}
