/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { groupResponseSchema } from "../groupResponseSchema.ts";
import { z } from "zod/v4";

export const getGroupByIdPathParamsSchema = z.object({
  id: z.coerce.number().int().describe("Group ID"),
});

/**
 * @description OK
 */
export const getGroupById200Schema = z.lazy(() => groupResponseSchema);

export const getGroupByIdQueryResponseSchema = z.lazy(
  () => getGroupById200Schema,
);
