/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NationalHealthInsuranceResponse } from "../NationalHealthInsuranceResponse.ts";

/**
 * @description OK
*/
export type GetMyNationalInsurance200 = NationalHealthInsuranceResponse;

export type GetMyNationalInsuranceQueryResponse = GetMyNationalInsurance200;

export type GetMyNationalInsuranceQuery = {
    Response: GetMyNationalInsurance200;
    Errors: any;
};