/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { NonCompulsoryHealthInsuranceResponse } from "../NonCompulsoryHealthInsuranceResponse.ts";
import type { UpsertNonCompulsoryHealthInsuranceRequest } from "../UpsertNonCompulsoryHealthInsuranceRequest.ts";

/**
 * @description OK
 */
export type UpsertMyNonCompulsoryInsurance200 =
  NonCompulsoryHealthInsuranceResponse;

export type UpsertMyNonCompulsoryInsuranceMutationRequest =
  UpsertNonCompulsoryHealthInsuranceRequest;

export type UpsertMyNonCompulsoryInsuranceMutationResponse =
  UpsertMyNonCompulsoryInsurance200;

export type UpsertMyNonCompulsoryInsuranceMutation = {
  Response: UpsertMyNonCompulsoryInsurance200;
  Request: UpsertMyNonCompulsoryInsuranceMutationRequest;
  Errors: any;
};
